Repository canonical/juju-dashboard, pull requests merged in 2019-11, with the labels that each got.

#157 Switch UI to a different model on juju switch
  src/components/Terminal/Terminal.js
  src/components/Terminal/setup-terminal.js
Labels: Review: Code +1, Review: QA +1

#165 Models details icons should be rounded
  src/pages/Models/Details/_model-details.scss
Labels: Review: Code +1, Review: QA +1

#159 Use generic Vanilla import instead of specific color settings
  src/components/ButtonToggle/_button-toggle.scss
  src/components/Filter/_filter.scss
  src/components/FilterTags/_filter-tags.scss
  src/components/Header/_header.scss
  src/components/InfoPanel/_info-panel.scss
  src/components/Layout/_layout.scss
  src/components/PrimaryNav/_primary-nav.scss
  src/components/TableList/_table-list.scss
  src/components/Terminal/_terminal.scss
  src/components/UserIcon/_user-icon.scss
  src/pages/Models/Details/_model-details.scss
Labels: Review: Code +1, Review: QA +1

#160 Use vf-animations mixin across all stylesheets
  src/components/FilterTags/_filter-tags.scss
  src/components/Layout/_layout.scss
  src/components/PrimaryNav/_primary-nav.scss
  src/components/Terminal/_terminal.scss
  src/components/UserIcon/_user-icon.scss
  src/pages/Models/Details/_model-details.scss
Labels: Review: Code +1, Review: QA +1

#164 Use a z-index scale
  .stylelintrc
  src/components/FilterTags/_filter-tags.scss
  src/components/Header/_header.scss
  src/components/Layout/_layout.scss
  src/components/UserIcon/_user-icon.scss
  src/scss/custom/_status_icons.scss
  src/scss/functions/_z-index.scss
  src/scss/index.scss
Labels: Review: Code +1, Review: QA +1

#169 Add machine table to model details page
  src/pages/Models/Details/ModelDetails.js
  src/pages/Models/Details/__snapshots__/ModelDetails.test.js.snap
Labels: Review: Code +1, Review: QA +1

#170 Add status list counts to headers on the model list
  src/app/utils.js
  src/components/TableList/TableList.js
  src/components/TableList/__snapshots__/TableList.test.js.snap
  src/pages/Models/Details/__snapshots__/ModelDetails.test.js.snap
Labels: Review: Code +1, Review: QA +1

#167 Add missing colored icons
  src/scss/custom/_status_icons.scss
Labels: Review: Code +1

#176 Swap tables on ModelDetails
  src/pages/Models/Details/ModelDetails.js
  src/pages/Models/Details/__snapshots__/ModelDetails.test.js.snap
Labels: Review: Code +1, Review: QA +1

#174 Sidebar style tweaks
  src/components/Layout/__snapshots__/Layout.test.js.snap
  src/components/PrimaryNav/PrimaryNav.js
  src/components/PrimaryNav/__snapshots__/PrimaryNav.test.js.snap
  src/components/PrimaryNav/_primary-nav.scss
Labels: Review: Code +1, Review: QA +1

#177 Reduce info panel width on smaller screens
  src/components/InfoPanel/_info-panel.scss
  src/pages/Models/Details/_model-details.scss
Labels: Review: Code +1, Review: QA +1

#181 Make sidebar, headers and terminal sticky
  src/components/Header/_header.scss
  src/components/Layout/Layout.js
  src/components/Layout/Layout.test.js
  src/components/Layout/__snapshots__/Layout.test.js.snap
  src/components/Layout/_layout.scss
  src/components/PrimaryNav/_primary-nav.scss
  src/components/Terminal/_terminal.scss
  src/pages/Models/Details/ModelDetails.js
  src/pages/Models/Details/_model-details.scss
  src/pages/Models/Models.js
Labels: Review: Code +1, Review: QA +1

#182 Selected nav should highlight nested urls
  src/components/App/App.js
  src/components/App/__snapshots__/App.test.js.snap
  src/components/Layout/__snapshots__/Layout.test.js.snap
  src/components/PrimaryNav/PrimaryNav.js
  src/components/PrimaryNav/__snapshots__/PrimaryNav.test.js.snap
Labels: Review: Code +1, Review: QA +1

#183 Show cloud provider name in model details
  src/components/InfoPanel/InfoPanel.js
  src/components/InfoPanel/__snapshots__/InfoPanel.test.js.snap
  src/pages/Models/Details/__snapshots__/ModelDetails.test.js.snap
Labels: Review: Code +1, Review: Design +1

#184 Align table columns
  src/components/InfoPanel/_info-panel.scss
  src/components/TableList/TableList.js
  src/components/TableList/__snapshots__/TableList.test.js.snap
  src/pages/Models/Details/ModelDetails.js
  src/pages/Models/Details/__snapshots__/ModelDetails.test.js.snap
  src/pages/Models/Details/_model-details.scss
  src/pages/Models/Models.js
  src/pages/Models/_models.scss
  src/scss/_settings.scss
  src/scss/_utils.scss
  src/scss/custom/_status_icons.scss
  src/scss/custom/_tables.scss
  src/scss/index.scss
Labels: Review: Code +1, Review: QA +1

#186 Truncate machine error messages
  .circleci/config.yml
  run
  src/pages/Models/Details/ModelDetails.js
  src/pages/Models/Details/ModelDetails.test.js
  src/pages/Models/Details/__snapshots__/ModelDetails.test.js.snap
  src/pages/Models/Details/_model-details.scss
Labels: Review: Code +1, Review: QA +1

#189 Remove double border on table rows
  src/pages/Models/Details/_model-details.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#188 Correct status label capitalisation
  src/pages/Models/Details/ModelDetails.js
  src/pages/Models/Details/__snapshots__/ModelDetails.test.js.snap
  src/scss/_utils.scss
  src/scss/custom/_status_icons.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#190 Add dummy link to models listing
  src/components/FilterTags/_filter-tags.scss
  src/components/TableList/TableList.js
  src/components/TableList/__snapshots__/TableList.test.js.snap
Labels: Review: Code +1, Review: QA +1

#194 Remove bottom-border on last table rows
  src/pages/Models/Details/_model-details.scss
Labels: Review: Code +1, Review: QA +1

#192 Improve user icon and dropdown panel
  src/components/UserIcon/UserIcon.js
  src/components/UserIcon/__snapshots__/UserIcon.test.js.snap
  src/components/UserIcon/_user-icon.scss
Labels: Review: Code +1, Review: QA +1

#191 Add tooltips to config icons in Models list
  src/components/TableList/TableList.js
  src/components/TableList/__snapshots__/TableList.test.js.snap
  src/pages/Models/_models.scss
  src/scss/index.scss
Labels: Review: Code +1, Review: QA +1

#196 Use ghost bundle image in the model details
  public/ghost-bundle.svg
  src/components/InfoPanel/InfoPanel.js
  src/components/InfoPanel/__snapshots__/InfoPanel.test.js.snap
  src/pages/Models/Details/__snapshots__/ModelDetails.test.js.snap
Labels: Review: Code +1, Review: Design needed, Review: QA +1

#197 Use npm react components
  package.json
  src/components/MainTable/MainTable.js
  src/components/MainTable/MainTable.test.js
  src/components/MainTable/Table/Table.js
  src/components/MainTable/Table/Table.test.js
  src/components/MainTable/Table/TableCell/TableCell.js
  src/components/MainTable/Table/TableCell/TableCell.test.js
  src/components/MainTable/Table/TableCell/__snapshots__/TableCell.test.js.snap
  src/components/MainTable/Table/TableHeader/TableHeader.js
  src/components/MainTable/Table/TableHeader/TableHeader.test.js
  src/components/MainTable/Table/TableHeader/__snapshots__/TableHeader.test.js.snap
  src/components/MainTable/Table/TableRow/TableRow.js
  src/components/MainTable/Table/TableRow/TableRow.test.js
  src/components/MainTable/Table/TableRow/__snapshots__/TableRow.test.js.snap
  src/components/MainTable/Table/__snapshots__/Table.test.js.snap
  src/components/MainTable/__snapshots__/MainTable.test.js.snap
  src/components/TableList/TableList.js
  src/components/TableList/__snapshots__/TableList.test.js.snap
  src/pages/Models/Details/ModelDetails.js
  src/pages/Models/Details/__snapshots__/ModelDetails.test.js.snap
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#198 Use soft links on Models listing page
  src/components/TableList/TableList.js
  src/components/TableList/__snapshots__/TableList.test.js.snap
Labels: Review: Code +1, Review: QA +1

#195 Display truncated error messages in the model list
  src/app/selectors.js
  src/app/utils.js
  src/components/TableList/TableList.js
  src/components/TableList/__snapshots__/TableList.test.js.snap
  src/components/TableList/_table-list.scss
  src/pages/Models/Details/_model-details.scss
  src/scss/custom/_tables.scss
Labels: Review: Code +1, Review: QA +1

#201 Extract routes into separate component
  src/components/App/App.js
  src/components/App/__snapshots__/App.test.js.snap
  src/components/InfoPanel/InfoPanel.test.js
  src/components/Routes/Routes.js
  src/components/Routes/TestRoute.js
  src/pages/Models/Details/ModelDetails.test.js
Labels: Review: Code +1, Review: QA +1

#202 Tweak info panel breakpoint
  src/pages/Models/Details/_model-details.scss
Labels: Review: Code +1, Review: QA +1

#209 Fix tooltips overflow
  src/components/TableList/TableList.js
  src/components/TableList/__snapshots__/TableList.test.js.snap
  src/scss/_utils.scss
Labels: Review: Code +1, Review: QA +1

#206 Offline images
  src/components/Layout/__snapshots__/Layout.test.js.snap
  src/components/LogIn/LogIn.js
  src/components/LogIn/__snapshots__/LogIn.test.js.snap
  src/components/PrimaryNav/PrimaryNav.js
  src/components/PrimaryNav/__snapshots__/PrimaryNav.test.js.snap
  src/pages/Models/Details/_model-details.scss
  src/static/images/icons/controllers-icon.svg
  src/static/images/icons/logs-icon.svg
  src/static/images/icons/machines-icon.svg
  src/static/images/icons/models-icon.svg
  src/static/images/icons/usage-icon.svg
  src/static/images/logo/logo-black-on-white.svg
  src/static/images/logo/logo-mark.svg
  src/static/images/logo/logo-text.svg
Labels: Review: Code +1, Review: QA +1

#210 Correct weird spacing in models details tables
  src/pages/Models/Details/ModelDetails.js
  src/pages/Models/Details/__snapshots__/ModelDetails.test.js.snap
  src/pages/Models/Details/_model-details.scss
  src/scss/_utils.scss
  src/scss/custom/_tables.scss
Labels: Review: Code +1, Review: QA +1

#213 Convert InfoPanel and ModelDetails to use new modelData selector
  src/app/selectors.js
  src/juju/reducers.js
  src/testing/complete-redux-store-dump.js
Labels: Review: Code +1, Review: QA +1

#214 Add title attribute to truncated error message on models details page
  src/components/TableList/TableList.js
  src/components/TableList/__snapshots__/TableList.test.js.snap
Labels: Review: Code +1, Review: QA +1

#215 Add a model with subordinates to test data
  src/components/TableList/__snapshots__/TableList.test.js.snap
  src/pages/Models/Models.test.js
  src/testing/complete-redux-store-dump.js
Labels: Review: Code needed

#216 Update logout mechanism to allow re-log-in
  src/app/actions.js
  src/app/root.js
  src/app/selectors.js
  src/components/LogIn/LogIn.test.js
  src/components/UserIcon/UserIcon.js
  src/juju/index.js
Labels: Review: Code +1, Review: QA +1

#203 Subordinate units
  src/pages/Models/Details/ModelDetails.js
  src/pages/Models/Details/ModelDetails.test.js
  src/pages/Models/Details/__snapshots__/ModelDetails.test.js.snap
  src/pages/Models/Details/_model-details.scss
  src/static/images/unit-tree.svg
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#217 Update the login UI to include a connecting state
  package.json
  src/app/selectors.js
  src/components/LogIn/LogIn.js
  src/components/LogIn/LogIn.test.js
  src/components/LogIn/__snapshots__/LogIn.test.js.snap
  src/components/LogIn/_login.scss
  src/scss/functions/_z-index.scss
  src/scss/index.scss
  src/static/images/logo/logo-black-on-white.svg
  yarn.lock
Labels: Review: Code +1, Review: Design needed, Review: QA +1

#222 Restyle user icon to match contextual menu pattern
  src/components/UserIcon/UserIcon.js
  src/components/UserIcon/UserIcon.test.js
  src/components/UserIcon/__snapshots__/UserIcon.test.js.snap
  src/components/UserIcon/_user-icon.scss
  src/scss/index.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#221 Synchronise button styles
  src/components/Button/_button.scss
  src/components/ButtonToggle/ButtonToggle.js
  src/components/ButtonToggle/__snapshots__/ButtonToggle.test.js.snap
  src/components/ButtonToggle/_button-toggle.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#232 Collapse external nav if user hovers off and sidebar collapses
  src/components/PrimaryNav/_primary-nav.scss
Labels: Review: Code +1, Review: QA +1

#233 Refactor to use negation :not()
  src/components/PrimaryNav/_primary-nav.scss
Labels: Review: Code +1, Review: QA +1
