Repository canonical/juju-dashboard, pull requests merged in 2019-08, with the labels that each got.

#3 Add team Github templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Review: Code +1

#4 Add Prettier
  .prettierignore
  .prettierrc.json
  package.json
  src/App.js
  src/index.scss
  src/serviceWorker.js
  yarn.lock
Labels: Review: QA needed

#5 Add routing
  package.json
  src/App.js
  src/Nav.js
  yarn.lock
Labels: Review: Code needed

#7 Add basic Nav component
  src/App.js
  src/Nav.js
  src/components/Nav/Nav.js
  src/components/Nav/Nav.test.js
  src/index.scss
Labels: Review: Code +1, Review: QA needed

#9 Remove Prettier override config
  .prettierrc.json
  src/App.js
  src/App.test.js
  src/components/Nav/Nav.js
  src/components/Nav/Nav.test.js
  src/index.js
  src/serviceWorker.js
Labels: Review: Code +1

#11 Add jujulib and connect to JAAS on load.
  package.json
  src/index.js
  src/juju/index.js
  yarn.lock
Labels: Review: Code +1

#10 Tweak side nav designs to match designs
  src/App.js
  src/index.js
  src/scss/_layout.scss
  src/scss/index.scss
Labels: Review: Code +1, Review: QA +1

#14 Add circleci config
  .circleci/config.yml
Labels: Review: Code +1

#15 Basic update to README
  README.md
Labels: Review: Code +1

#16 Switch to using Enzyme for testing
  package.json
  src/components/Nav/Nav.test.js
  src/setupTests.js
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#17 Simple error boundary
  src/App.js
  src/components/ErrorBoundary/ErrorBoundary.js
  src/components/ErrorBoundary/ErrorBoundary.test.js
Labels: Review: Code +1, Review: QA needed

#18 Fix prettier regressions
  .circleci/config.yml
  .prettierrc
  src/components/Nav/Nav.test.js
  src/index.js
  src/juju/index.js
  src/scss/_layout.scss
  src/scss/index.scss
  src/setupTests.js
Labels: Review: Code +1

#20 Add Jest snapshots to existing components
  package.json
  src/components/ErrorBoundary/ErrorBoundary.test.js
  src/components/ErrorBoundary/__snapshots__/ErrorBoundary.test.js.snap
  src/components/Nav/Nav.test.js
  src/components/Nav/__snapshots__/Nav.test.js.snap
  yarn.lock
Labels: Review: Code +1

#21 Add simple Github action to request PR reviews from assignees
  .github/workflows/assignee-to-reviewer-action.yml
Labels: Review: Code +1

#22 Update secondary nav to match designs
  src/App.js
  src/components/PrimaryNav/PrimaryNav.js
  src/components/PrimaryNav/PrimaryNav.test.js
  src/components/PrimaryNav/__snapshots__/PrimaryNav.test.js.snap
  src/components/SecondaryNav/SecondaryNav.js
  src/components/SecondaryNav/SecondaryNav.test.js
  src/components/SecondaryNav/__snapshots__/SecondaryNav.test.js.snap
  src/components/SecondaryNav/_secondary-nav.scss
  src/scss/_layout.scss
  src/scss/index.scss
Labels: Review: Code +1, Review: Design +1, Review: QA needed

#23 Fix vanilla imports
  .env
  package.json
  src/components/SecondaryNav/_secondary-nav.scss
  src/scss/_layout.scss
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#24 Add TableSet component with dummy data to Models component
  src/App.js
  src/components/TableSet/TableSet.js
  src/components/TableSet/TableSet.test.js
  src/components/TableSet/__snapshots__/TableSet.test.js.snap
  src/scss/index.scss
Labels: Review: Code +1, Review: QA +1

#27 Add Eslint
  .circleci/config.yml
  .env
  .eslintignore
  .eslintrc
  .gitignore
  .prettierignore
  package.json
  src/App.test.js
  src/components/ErrorBoundary/ErrorBoundary.js
  src/components/TableSet/TableSet.js
  src/components/TableSet/TableSet.test.js
  src/components/TableSet/__snapshots__/TableSet.test.js.snap
  src/juju/index.js
  src/reducers/root.js
  src/setupTests.js
  yarn.lock
Labels: Review: Code needed, Review: QA needed

#25 Add model list into the redux store
  .eslintrc
  package.json
  src/index.js
  src/juju/actions.js
  src/juju/actions.test.js
  src/juju/index.js
  src/juju/reducers.js
  src/reducers/actions.js
  src/reducers/root.js
  yarn.lock
Labels: Review: Code +1, Review: QA needed

#30 Move App into /components and add snapshot test
  src/App.test.js
  src/components/App/App.js
  src/components/App/App.test.js
  src/components/App/__snapshots__/App.test.js.snap
  src/index.js
Labels: Review: Code +1, Review: QA +1

#31 Do not use index for list keys
  src/components/TableSet/TableSet.js
  src/components/TableSet/__snapshots__/TableSet.test.js.snap
Labels: Review: Code +1, Review: QA +1

#32 Add hooks linting
  .eslintrc
  package.json
  yarn.lock
Labels: Review: Code needed, Review: QA needed

#33 Little cleanup
  package.json
  public/index.html
  public/manifest.json
Labels: Review: Code +1

#35 Revert "Add hooks linting"
  .eslintrc
  package.json
  yarn.lock
Labels: Review: Code +1

#34 Fetch model statuses and store in Redux
  src/index.js
  src/juju/actions.js
  src/juju/index.js
  src/juju/reducers.js
  src/reducers/root.js
Labels: Review: Code +1, Review: QA +1

#36 Use maas ui table components
  .eslintrc
  package.json
  src/components/Table/.DS_Store
  src/components/Table/Table.js
  src/components/Table/Table.test.js
  src/components/Table/TableCell/.DS_Store
  src/components/Table/TableCell/TableCell.js
  src/components/Table/TableCell/TableCell.test.js
  src/components/Table/TableCell/__snapshots__/TableCell.test.js.snap
  src/components/Table/TableHeader/.DS_Store
  src/components/Table/TableHeader/TableHeader.js
  src/components/Table/TableHeader/TableHeader.test.js
  src/components/Table/TableHeader/__snapshots__/TableHeader.test.js.snap
  src/components/Table/TableRow/.DS_Store
  src/components/Table/TableRow/TableRow.js
  src/components/Table/TableRow/TableRow.test.js
  src/components/Table/TableRow/__snapshots__/TableRow.test.js.snap
  src/components/Table/__snapshots__/Table.test.js.snap
  src/components/TableSet/TableSet.js
  src/components/TableSet/__snapshots__/TableSet.test.js.snap
  src/scss/index.scss
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#38 Add .DS_Store to .gitignore
  .gitignore
Labels: Review: Code +1

#42 Display model data from Redux store.
  src/components/App/App.js
  src/components/TableList/TableList.js
Labels: Review: Code +1, Review: QA +1

#43 Add static model details view
  src/components/App/App.js
  src/components/App/__snapshots__/App.test.js.snap
  src/components/Button/Button.js
  src/components/Button/Button.test.js
  src/components/Button/__snapshots__/Button.test.js.snap
  src/components/Button/_button.scss
  src/components/Filter/Filter.js
  src/components/Filter/Filter.test.js
  src/components/Filter/__snapshots__/Filter.test.js.snap
  src/components/Filter/_filter.scss
  src/components/InfoPanel/InfoPanel.js
  src/components/InfoPanel/InfoPanel.test.js
  src/components/InfoPanel/__snapshots__/InfoPanel.test.js.snap
  src/components/InfoPanel/_info-panel.scss
  src/components/Layout/Layout.js
  src/components/Layout/Layout.test.js
  src/components/Layout/__snapshots__/Layout.test.js.snap
  src/components/Layout/_layout.scss
  src/components/Shell/Shell.js
  src/components/Shell/Shell.test.js
  src/components/Shell/__snapshots__/Shell.test.js.snap
  src/components/Shell/_shell.scss
  src/containers/ModelDetails/ModelDetails.js
  src/containers/ModelDetails/ModelDetails.test.js
  src/containers/ModelDetails/__snapshots__/ModelDetails.test.js.snap
  src/containers/ModelDetails/_model-details.scss
  src/scss/index.scss
Labels: Review: Code +1, Review: QA +1

#45 Add the credential name to the model details table.
  src/components/TableList/TableList.js
  src/index.js
  src/juju/actions.js
  src/juju/index.js
  src/juju/reducers.js
  src/reducers/root.js
Labels: Dont merge, Review: Code +1, Review: QA +1
