Repository canonical/juju-dashboard, pull requests merged in 2019-10, with the labels that each got.

#67 Add auth wrapper components & Fetch model UUID on details page
  src/app/selectors.js
  src/components/App/App.js
  src/components/App/__snapshots__/App.test.js.snap
  src/components/IsLoggedIn/IsLoggedIn.js
  src/components/IsLoggedIn/__snapshots__/isLoggedIn.test.js.snap
  src/components/IsLoggedIn/isLoggedIn.test.js
  src/components/Terminal/Terminal.js
  src/juju/actions.js
  src/juju/index.js
  src/pages/Models/Details/ModelDetails.js
  src/pages/Models/Details/ModelDetails.test.js
  src/pages/Models/Details/__snapshots__/ModelDetails.test.js.snap
Labels: Review: Code +1, Review: QA needed

#68 Switch the CLI to the model you're viewing
  src/components/Terminal/Terminal.js
  src/components/Terminal/setup-terminal.js
  src/pages/Models/Details/ModelDetails.js
  src/pages/Models/Details/__snapshots__/ModelDetails.test.js.snap
Labels: Review: Code +1, Review: QA +1

#71 Show the model status using real data
  src/app/selectors.js
  src/components/Terminal/Terminal.js
  src/juju/actions.js
  src/pages/Models/Details/ModelDetails.js
  src/pages/Models/Details/ModelDetails.test.js
  src/pages/Models/Details/__snapshots__/ModelDetails.test.js.snap
Labels: Review: Code +1, Review: QA +1

#73 Refactor login flow
  src/components/App/App.js
  src/components/App/__snapshots__/App.test.js.snap
  src/components/IsLoggedIn/IsLoggedIn.js
  src/components/IsLoggedIn/__snapshots__/isLoggedIn.test.js.snap
  src/components/LogIn/LogIn.js
  src/components/LogIn/LogIn.test.js
  src/components/LogIn/__snapshots__/LogIn.test.js.snap
  src/components/LogIn/_login.scss
  src/components/Login/Login.js
Labels: Review: Code +1, Review: QA +1

#78 Persist login credentials between refresh
  src/index.js
  src/juju/index.js
Labels: Review: Code +1, Review: QA +1

#81 Restyle primary navigation
  src/components/Layout/Layout.js
  src/components/Layout/Layout.test.js
  src/components/Layout/__snapshots__/Layout.test.js.snap
  src/components/Layout/_layout.scss
  src/components/PrimaryNav/PrimaryNav.js
  src/components/PrimaryNav/PrimaryNav.test.js
  src/components/PrimaryNav/__snapshots__/PrimaryNav.test.js.snap
  src/components/PrimaryNav/_primary-nav.scss
  src/components/SecondaryNav/SecondaryNav.js
  src/components/SecondaryNav/SecondaryNav.test.js
  src/components/SecondaryNav/__snapshots__/SecondaryNav.test.js.snap
  src/components/SecondaryNav/_secondary-nav.scss
  src/pages/Controllers/__snapshots__/Controllers.test.js.snap
  src/pages/Logs/__snapshots__/Logs.test.js.snap
  src/pages/Models/Models.js
  src/pages/Models/__snapshots__/Models.test.js.snap
  src/pages/NotFound/__snapshots__/NotFound.test.js.snap
  src/pages/Usage/__snapshots__/Usage.test.js.snap
Labels: Review: Code +1, Review: Design +1

#84 Add dockerfile
  Dockerfile
Labels: Review: Code +1

#87 Grab the macaroons from the correct storage location in the bakery.
  src/app/selectors.js
Labels: Review: Code +1, Review: QA +1

#75 Add real data to Model detail info panel
  src/components/InfoPanel/InfoPanel.js
  src/components/InfoPanel/InfoPanel.test.js
  src/components/InfoPanel/__snapshots__/InfoPanel.test.js.snap
  src/pages/Models/Details/__snapshots__/ModelDetails.test.js.snap
Labels: Review: Code +1, Review: QA +1

#88 Sort models by status and display them in separate tables
  src/components/TableList/TableList.js
  src/components/TableList/__snapshots__/TableList.test.js.snap
  src/components/TableList/_table-list.scss
Labels: Review: Code +1, Review: QA +1

#89 Add nginx to serve in staging
  Dockerfile
  nginx.conf
  package.json
Labels: Review: Code +1, Review: QA +1

#90 Add static UI build for filtering of models
  src/components/ButtonToggle/ButtonToggle.js
  src/components/ButtonToggle/ButtonToggle.test.js
  src/components/ButtonToggle/__snapshots__/ButtonToggle.test.js.snap
  src/components/ButtonToggle/_button-toggle.scss
  src/components/FilterTags/FilterTags.js
  src/components/FilterTags/FilterTags.test.js
  src/components/FilterTags/__snapshots__/FilterTags.test.js.snap
  src/components/FilterTags/_filter-tags.scss
  src/components/Header/Header.js
  src/components/Header/Header.test.js
  src/components/Header/__snapshots__/Header.test.js.snap
  src/components/Header/_header.scss
  src/pages/Models/Details/ModelDetails.js
  src/pages/Models/Models.js
  src/pages/Models/__snapshots__/Models.test.js.snap
  src/pages/Models/_models.scss
  src/scss/index.scss
Labels: Review: Code +1, Review: QA +1

#92 Add check endpoint
  nginx.conf
Labels: Review: Code +1, Review: QA +1

#94 Change port to 80 for prod
  Dockerfile
Labels: Review: Code +1, Review: QA +1

#96 Sidebar styling tweaks
  src/components/FilterTags/_filter-tags.scss
  src/components/Header/_header.scss
  src/components/Layout/_layout.scss
  src/components/PrimaryNav/_primary-nav.scss
Labels: Review: Code +1, Review: QA +1

#93 Remove superfluous role attributes
  src/components/MainTable/Table/TableHeader/TableHeader.js
  src/components/MainTable/Table/TableHeader/__snapshots__/TableHeader.test.js.snap
  src/components/MainTable/Table/TableRow/TableRow.js
  src/components/MainTable/Table/TableRow/__snapshots__/TableRow.test.js.snap
  src/components/TableList/__snapshots__/TableList.test.js.snap
  src/pages/Models/Details/__snapshots__/ModelDetails.test.js.snap
Labels: Review: Code +1

#99 Fix sidebar hover bug
  src/components/PrimaryNav/_primary-nav.scss
Labels: Review: Code +1, Review: QA +1

#97 Add filter panel to input
  src/components/ButtonToggle/ButtonToggle.test.js
  src/components/FilterTags/FilterTags.js
  src/components/FilterTags/FilterTags.test.js
  src/components/FilterTags/__snapshots__/FilterTags.test.js.snap
  src/components/FilterTags/_filter-tags.scss
  src/scss/index.scss
Labels: Review: Code +1, Review: QA +1

#100 Add sidebar icons
  src/components/PrimaryNav/PrimaryNav.js
  src/components/PrimaryNav/__snapshots__/PrimaryNav.test.js.snap
  src/components/PrimaryNav/_primary-nav.scss
Labels: Review: Code +1, Review: QA +1

#103 Add model count summary header
  src/app/selectors.js
  src/pages/Models/Models.js
  src/pages/Models/Models.test.js
  src/pages/Models/__snapshots__/Models.test.js.snap
Labels: Review: Code +1, Review: QA +1

#104 Style model details page
  src/components/Button/_button.scss
  src/components/Filter/_filter.scss
  src/components/FilterTags/FilterTags.js
  src/components/FilterTags/__snapshots__/FilterTags.test.js.snap
  src/components/FilterTags/_filter-tags.scss
  src/components/Header/_header.scss
  src/components/InfoPanel/InfoPanel.js
  src/components/InfoPanel/InfoPanel.test.js
  src/components/InfoPanel/__snapshots__/InfoPanel.test.js.snap
  src/components/InfoPanel/_info-panel.scss
  src/components/Layout/_layout.scss
  src/components/PrimaryNav/_primary-nav.scss
  src/components/Terminal/Terminal.js
  src/components/Terminal/_terminal.scss
  src/pages/Models/Details/ModelDetails.js
  src/pages/Models/Details/__snapshots__/ModelDetails.test.js.snap
  src/pages/Models/Details/_model-details.scss
Labels: Review: Code +1, Review: QA +1, Review: UX needed

#114 Remove Vanilla bug override
  src/scss/index.scss
Labels: Review: Code +1, Review: QA +1

#116 Group model list models using new selectors
  src/app/selectors.js
  src/components/TableList/TableList.js
  src/components/TableList/TableList.test.js
  src/components/TableList/__snapshots__/TableList.test.js.snap
  src/juju/index.js
  src/juju/reducers.js
  src/pages/Models/Models.test.js
Labels: Review: Code +1, Review: QA +1

#111 Update Models listing styling
  src/app/actions.js
  src/app/root.js
  src/app/utils.js
  src/components/TableList/TableList.js
  src/components/TableList/__snapshots__/TableList.test.js.snap
  src/components/TableList/_table-list.scss
  src/components/UserIcon/UserIcon.js
  src/components/UserIcon/UserIcon.test.js
  src/components/UserIcon/__snapshots__/UserIcon.test.js.snap
  src/components/UserIcon/_user-icon.scss
  src/pages/Models/Details/ModelDetails.js
  src/pages/Models/Details/__snapshots__/ModelDetails.test.js.snap
  src/pages/Models/Details/_model-details.scss
  src/pages/Models/Models.js
  src/scss/_status_icons.scss
  src/scss/index.scss
Labels: Review: Code +1, Review: QA +1

#131 Add entity icons to models details page
  src/pages/Models/Details/ModelDetails.js
  src/pages/Models/Details/__snapshots__/ModelDetails.test.js.snap
  src/pages/Models/Details/_model-details.scss
Labels: Review: Code +1, Review: QA +1

#137 Use NavLink to determine is-selected state
  src/components/PrimaryNav/PrimaryNav.js
  src/components/PrimaryNav/PrimaryNav.test.js
  src/components/PrimaryNav/__snapshots__/PrimaryNav.test.js.snap
  src/components/PrimaryNav/_primary-nav.scss
Labels: Review: Code +1, Review: QA +1

#134 Models details collapsible sidebar
  src/app/actions.js
  src/app/root.js
  src/app/selectors.js
  src/components/Layout/Layout.js
  src/components/Layout/Layout.test.js
  src/components/Layout/__snapshots__/Layout.test.js.snap
  src/components/Layout/_layout.scss
  src/components/PrimaryNav/PrimaryNav.js
  src/components/PrimaryNav/__snapshots__/PrimaryNav.test.js.snap
  src/components/PrimaryNav/_primary-nav.scss
  src/hooks/useHover.js
  src/pages/Models/Details/ModelDetails.js
  src/scss/_settings.scss
Labels: Review: Code +1, Review: QA +1

#154 Add blocked notification in sidebar
  src/components/Layout/__snapshots__/Layout.test.js.snap
  src/components/PrimaryNav/PrimaryNav.js
  src/components/PrimaryNav/PrimaryNav.test.js
  src/components/PrimaryNav/__snapshots__/PrimaryNav.test.js.snap
  src/components/PrimaryNav/_primary-nav.scss
Labels: Review: Code +1, Review: QA +1

#155 Float the collapsible sidebar
  src/components/Header/_header.scss
  src/components/Layout/Layout.js
  src/components/Layout/_layout.scss
Labels: Review: Code +1, Review: QA +1
