Repository canonical/juju-dashboard, pull requests merged in 2020-11, with the labels that each got.

#738 Refresh the model status data on submitting a command
  src/app/selectors.js
  src/components/WebCLI/WebCLI.js
  src/components/WebCLI/WebCLI.test.js
  src/components/WebCLI/__snapshots__/WebCLI.test.js.snap
  src/components/WebCLI/connection.js
  src/pages/Models/Details/ModelDetails.js
Labels: Review: Code +1, Review: QA needed

#746 Add custom page titles
  src/hooks/useWindowTitle.js
  src/pages/Controllers/Controllers.js
  src/pages/Models/Details/ModelDetails.js
  src/pages/Models/Details/ModelDetails.test.js
  src/pages/Models/Models.js
  src/pages/Models/Models.test.js
  src/pages/NotFound/NotFound.js
  src/pages/Settings/Settings.js
Labels: Review: Code +1, Review: QA +1

#752 Conditonally load user menu
  src/components/UserMenu/UserMenu.js
Labels: Review: Code +1, Review: QA +1

#753 Hide banner content when inactive
  src/components/Banner/_banner.scss
Labels: Review: Code +1, Review: QA +1

#748 Fix 404 pages
  src/components/App/App.js
  src/components/Routes/Routes.js
  src/pages/NotFound/NotFound.js
  src/pages/NotFound/NotFound.test.js
  src/pages/NotFound/__snapshots__/NotFound.test.js.snap
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#755 Replace Search and filter component
  package.json
  public/index.html
  src/app/selectors.js
  src/components/App/App.js
  src/components/FilterTags/FilterTags.js
  src/components/FilterTags/FilterTags.test.js
  src/components/FilterTags/_filter-tags.scss
  src/components/ModelTableList/CloudGroup.test.js
  src/components/ModelTableList/OwnerGroup.test.js
  src/components/ModelTableList/StatusGroup.test.js
  src/hooks/useModelAttributes.js
  src/index.js
  src/pages/Models/Models.js
  src/pages/Models/_models.scss
  src/scss/index.scss
  yarn.lock
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#761 Add check for controllerData before accessing keys
  src/pages/Controllers/Controllers.js
Labels: Review: Code +1, Review: QA +1

#754 Switch to v2 of the jujulib
  README.md
  craco.config.js
  package.json
  src/app/actions.js
  src/app/check-auth.js
  src/app/jimm-facade.js
  src/app/model-poller.js
  src/app/selectors.js
  src/app/utils.js
  src/components/InfoPanel/InfoPanel.js
  src/components/InfoPanel/InfoPanel.test.js
  src/components/ModelTableList/CloudGroup.js
  src/components/ModelTableList/CloudGroup.test.js
  src/components/ModelTableList/ModelTableList.test.js
  src/components/ModelTableList/OwnerGroup.js
  src/components/ModelTableList/OwnerGroup.test.js
  src/components/ModelTableList/StatusGroup.js
  src/components/ModelTableList/StatusGroup.test.js
  src/components/ModelTableList/shared.js
  src/components/PrimaryNav/PrimaryNav.test.js
  src/components/Topology/Topology.js
  src/components/UserMenu/UserMenu.test.js
  src/components/UserMenu/__snapshots__/UserMenu.test.js.snap
  src/components/panels/AppsPanel/AppsPanel.js
  src/components/panels/MachinesPanel/MachinesPanel.js
  src/components/panels/UnitsPanel/UnitsPanel.js
  src/hooks/useModelAttributes.js
  src/index.js
  src/juju/actions.js
  src/juju/index.js
  src/juju/reducer.js
  src/pages/Controllers/Controllers.js
  src/pages/Controllers/Controllers.test.js
  src/pages/Controllers/__snapshots__/Controllers.test.js.snap
  src/pages/Models/Details/ModelDetails.js
  src/pages/Models/Details/ModelDetails.test.js
  src/pages/Models/Details/generators.js
  src/pages/Models/Models.test.js
  src/testing/complete-redux-store-dump.js
  yarn.lock
Labels: Review: Code +1

#766 Update color of icons to #E5E5E5
  public/ghost-bundle.svg
  src/components/UserMenu/UserMenu.js
  src/components/UserMenu/__snapshots__/UserMenu.test.js.snap
  src/static/images/icons/apps-icon.svg
  src/static/images/icons/controllers-icon.svg
  src/static/images/icons/logs-icon.svg
  src/static/images/icons/machines-icon.svg
  src/static/images/icons/models-icon.svg
  src/static/images/icons/units-icon.svg
  src/static/images/icons/usage-icon.svg
Labels: Review: Code +1, Review: Design +1

#765 Add empty state for model relations view
  src/pages/Models/Details/ModelDetails.js
  src/pages/Models/Details/ModelDetails.test.js
  src/testing/complete-redux-store-dump.js
Labels: Review: Code +1, Review: QA +1

#768 Restyle status strip
  src/components/Counts/Counts.js
  src/components/Counts/Counts.test.js
  src/components/Counts/_counts.scss
  src/components/Layout/Layout.js
  src/components/StatusStrip/StatusStrip.js
  src/components/StatusStrip/StatusStrip.test.js
  src/components/StatusStrip/_status-strip.scss
  src/pages/Models/Details/ModelDetails.js
  src/pages/Models/Details/ModelDetails.test.js
  src/pages/Models/Details/_model-details.scss
  src/pages/Models/Models.js
  src/pages/Models/Models.test.js
  src/pages/Models/_models.scss
  src/scss/custom/_status_icons.scss
  src/scss/index.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#772 Enable Typescript
  .circleci/config.yml
  .eslintrc
  .gitignore
  jsconfig.json
  package.json
  src/react-app-env.d.ts
  tsconfig.json
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#769 Rename status to apps
  src/components/panels/AppsPanel/AppsPanel.js
  src/pages/Models/Details/ModelDetails.js
  src/pages/Models/Details/ModelDetails.test.js
  src/pages/Models/Details/generators.js
Labels: Review: Code +1, Review: QA +1
