Repository canonical/juju-dashboard, pull requests merged in 2020-08, with the labels that each got.

#636 Correctly terminate the controller connections and allow login again.
  src/app/actions.js
  src/app/check-auth.js
  src/app/model-poller.js
  src/app/root.js
  src/app/selectors.js
  src/components/LogIn/LogIn.js
  src/components/UserMenu/UserMenu.js
  src/juju/actions.js
  src/juju/reducer.js
Labels: Review: Code +1, Review: QA +1

#650 Reduce the width of the name in details
  src/pages/Models/Details/_model-details.scss
Labels: Review: Code +1, Review: QA +1

#652 Make the slide panel slide
  src/components/SlidePanel/SlidePanel.js
  src/components/SlidePanel/_slide-panel.scss
  src/pages/Controllers/Controllers.js
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#655 Remove dud links
  src/components/ModelTableList/CloudGroup.js
  src/components/ModelTableList/OwnerGroup.js
  src/components/ModelTableList/StatusGroup.js
  src/pages/Models/Details/generators.js
Labels: Review: Code +1, Review: QA +1

#657 Fix duplicate form field ids
  src/pages/Controllers/Controllers.js
Labels: Review: Code +1

#663 Add keyboard navigation to primary navigation
  src/components/Layout/Layout.js
  src/components/Layout/_layout.scss
Labels: Review: Code +1, Review: QA +1
