Repository canonical/juju-dashboard, pull requests merged in 2020-02, with the labels that each got.

#345 Add error object to error message.
  src/juju/index.js
Labels: Review: Code +1, Review: QA needed

#347 Adjust modal z-index and owners grouping widths
  src/components/InfoPanel/_info-panel.scss
  src/pages/Models/_models.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#346 Increase the size of the icons and darken the relations and application icon outlines
  src/components/Topology/Topology.js
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#349 Filter entities by application on model details
  package.json
  src/components/InfoPanel/InfoPanel.test.js
  src/pages/Models/Details/ModelDetails.js
  src/pages/Models/Details/ModelDetails.test.js
  src/pages/Models/Details/_model-details.scss
  src/pages/Models/Details/generators.js
Labels: Review: Code +1, Review: QA +1

#351 Add filtering interactions to drop-down panel
  src/components/FilterTags/FilterTags.js
  src/components/FilterTags/FilterTags.test.js
  src/components/FilterTags/_filter-tags.scss
Labels: Review: Code +1, Review: QA +1

#358 Update icon models color
  src/static/images/icons/models-icon.svg
Labels: Review: Code +1, Review: QA +1

#361 Add Settings component
  src/app/send-analytics-hook.js
  src/components/App/App.js
  src/components/App/__snapshots__/App.test.js.snap
  src/components/FilterTags/FilterTags.js
  src/components/InfoPanel/InfoPanel.js
  src/components/Routes/Routes.js
  src/components/UserIcon/UserIcon.js
  src/components/UserIcon/__snapshots__/UserIcon.test.js.snap
  src/pages/Settings/Settings.js
  src/pages/Settings/settings.scss
  src/scss/index.scss
Labels: Review: Code +1

#362 Add view filtering to models details pages
  src/components/Filter/Filter.js
  src/components/Filter/_filter.scss
  src/pages/Models/Details/ModelDetails.js
  src/pages/Models/Details/ModelDetails.test.js
Labels: Review: Code +1, Review: QA +1

#368 Filter by dropdown selections
  src/app/selectors.js
  src/components/FilterTags/FilterTags.js
  src/components/FilterTags/FilterTags.test.js
  src/components/ModelTableList/CloudGroup.js
  src/components/ModelTableList/CloudGroup.test.js
  src/components/ModelTableList/ModelTableList.js
  src/components/ModelTableList/ModelTableList.test.js
  src/components/ModelTableList/OwnerGroup.js
  src/components/ModelTableList/OwnerGroup.test.js
  src/components/ModelTableList/StatusGroup.js
  src/components/ModelTableList/StatusGroup.test.js
  src/pages/Models/Models.js
Labels: Review: Code +1, Review: QA +1
