Repository canonical/juju-dashboard, pull requests merged in 2020-10, with the labels that each got.

#702 Fix SlidePanel back button interactions
  src/components/SlidePanel/SlidePanel.js
  src/pages/Models/Details/ModelDetails.js
Labels: Review: Code +1, Review: QA +1

#703 Add Vanilla table sorting to Model list and Details pages
  src/components/ModelTableList/CloudGroup.js
  src/components/ModelTableList/OwnerGroup.js
  src/components/ModelTableList/StatusGroup.js
  src/pages/Models/Details/generators.js
Labels: Review: Code +1, Review: QA +1

#705 Hide empty tables in model status view
  src/components/ModelTableList/StatusGroup.js
  src/components/ModelTableList/StatusGroup.test.js
Labels: Review: Code +1, Review: QA +1, Review: QA needed

#712 Fix focus ring errors styling
  src/scss/index.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#709 Enable panel tables on model details page
  src/app/selectors.js
  src/components/panels/AppsPanel/AppsPanel.js
  src/components/panels/MachinesPanel/MachinesPanel.js
  src/components/panels/MachinesPanel/_machines-panel.scss
  src/components/panels/UnitsPanel/UnitsPanel.js
  src/components/panels/_panels.scss
  src/pages/Models/Details/ModelDetails.js
  src/pages/Models/Details/ModelDetails.test.js
  src/pages/Models/Details/_model-details.scss
  src/pages/Models/Details/generators.js
  src/scss/custom/_status_icons.scss
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#721 Use Vanilla application layout
  src/components/Header/_header.scss
  src/components/Layout/Layout.js
  src/components/Layout/Layout.test.js
  src/components/Layout/_layout.scss
  src/components/LogIn/_login.scss
  src/components/Logo/Logo.js
  src/components/Logo/_logo.scss
  src/components/PrimaryNav/PrimaryNav.js
  src/components/PrimaryNav/PrimaryNav.test.js
  src/components/PrimaryNav/_primary-nav.scss
  src/components/SlidePanel/_slide-panel.scss
  src/components/UserMenu/_user-menu.scss
  src/hooks/useHover.js
  src/index.js
  src/pages/Controllers/_controllers.scss
  src/pages/Models/Details/ModelDetails.js
  src/pages/Models/Details/_model-details.scss
  src/pages/Models/Models.js
  src/scss/_settings.scss
  src/scss/functions/_z-index.scss
  src/scss/index.scss
  src/static/images/logo/jaas-text.svg
  src/testing/complete-redux-store-dump.js
  src/ui/actions.js
  src/ui/index.js
  src/ui/selectors.js
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#720 Update the UI of the Juju Web CLI
  package.json
  src/components/SlidePanel/SlidePanel.js
  src/components/Terminal/Terminal.js
  src/components/Terminal/_terminal.scss
  src/components/Terminal/cleanup-terminal.js
  src/components/Terminal/setup-terminal.js
  src/components/Terminal/xterm-addon-juju.js
  src/components/Terminal/xterm-addon-terminado.js
  src/components/WebCLI/Output.js
  src/components/WebCLI/WebCLI.js
  src/components/WebCLI/WebCLI.test.js
  src/components/WebCLI/__snapshots__/WebCLI.test.js.snap
  src/components/WebCLI/_webcli.scss
  src/pages/Models/Details/ModelDetails.js
  yarn.lock
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#730 Add feature flag for WebCLI
  public/config.js
  src/pages/Models/Details/ModelDetails.js
Labels: Review: Code +1, Review: QA +1

#736 Update IP address on register controllers
  src/pages/Controllers/Controllers.js
Labels: Review: Code +1, Review: QA needed

#734 Update z-index of modal
  src/components/InfoPanel/_info-panel.scss
Labels: Review: Code +1, Review: QA +1

#731 Use event listener hook
  src/components/FilterTags/FilterTags.js
  src/components/InfoPanel/InfoPanel.js
  src/components/SlidePanel/SlidePanel.js
  src/hooks/useEventListener.js
Labels: Review: Code +1, Review: QA +1

#735 Update site wide offline banner
  src/components/Banner/Banner.js
  src/components/Banner/Banner.test.js
  src/components/Banner/_banner.scss
  src/components/Layout/Layout.js
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#737 Remove unused components and routes
  src/components/PrimaryNav/PrimaryNav.js
  src/components/Routes/Routes.js
  src/pages/Logs/Logs.js
  src/pages/Logs/Logs.test.js
  src/pages/Logs/__snapshots__/Logs.test.js.snap
  src/pages/Usage/Usage.js
  src/pages/Usage/Usage.test.js
  src/pages/Usage/__snapshots__/Usage.test.js.snap
Labels: Review: Code +1, Review: QA +1
