Repository canonical/juju-dashboard, pull requests merged in 2020-03, with the labels that each got.

#381 Make is-provisioning error red
  src/scss/custom/_status_icons.scss
Labels: Review: Code +1, Review: QA +1

#385 Support user pass login flow
  craco.config.js
  src/app/actions.js
  src/app/check-auth.js
  src/app/model-poller.js
  src/app/root.js
  src/app/selectors.js
  src/app/use-config-hook.js
  src/app/utils.js
  src/components/App/App.js
  src/components/App/App.test.js
  src/components/App/__snapshots__/App.test.js.snap
  src/components/LogIn/LogIn.js
  src/components/LogIn/LogIn.test.js
  src/components/LogIn/__snapshots__/LogIn.test.js.snap
  src/index.js
  src/juju/actions.js
  src/juju/index.js
  src/setupTests.js
  src/testing/complete-redux-store-dump.js
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#386 Hide status filters in Model Details
  src/pages/Models/Details/ModelDetails.js
Labels: Review: Code +1, Review: QA +1

#390 Make the Topology responsive
  src/components/InfoPanel/_info-panel.scss
  src/components/Topology/Topology.js
Labels: Review: Code +1, Review: QA +1

#393 Do not munge function names to allow for gating thunks by authentication
  craco.config.js
Labels: Review: Code +1, Review: QA +1

#395 Support URL basename
  src/components/App/App.js
  src/components/App/App.test.js
  src/components/Routes/Routes.js
Labels: Review: Code +1, Review: QA +1

#396 Povide config template file for Juju core
  public/config.js.go
  src/index.js
Labels: Review: Code +1

#394 Resize terminal
  src/components/Terminal/Terminal.js
  src/components/Terminal/_terminal.scss
Labels: Review: Code +1, Review: QA +1

#400 Move and rename analytics hook
  src/components/FilterTags/FilterTags.js
  src/components/InfoPanel/InfoPanel.js
  src/components/Routes/Routes.js
  src/components/UserMenu/UserMenu.js
  src/hooks/useAnalytics.js
Labels: Review: Code +1, Review: QA +1
