Repository canonical/juju-dashboard, pull requests merged in 2020-06, with the labels that each got.

#536 chore: Add juju commands for using the dashboard.
  README.md
Labels: Review: Code +1

#539 fix: Logging out now shows the log-in UI again.
  src/app/actions.js
  src/app/root.js
Labels: Review: Code +1, Review: QA +1

#541 formatting and cleanup.
  README.md
Labels: Review: Code +1

#540 Use agent status instead of instance status in machine table
  src/pages/Models/Details/generators.js
  src/scss/custom/_status_icons.scss
Labels: Review: Code +1, Review: QA +1

#533 Render the controller name in the model table
  src/app/selectors.js
  src/components/ModelTableList/CloudGroup.js
  src/components/ModelTableList/ModelTableList.test.js
  src/components/ModelTableList/OwnerGroup.js
  src/components/ModelTableList/StatusGroup.js
  src/components/ModelTableList/shared.js
Labels: Review: Code +1, Review: QA +1

#563 Disable controller charts if no data provided
  src/components/DonutChart/DonutChart.js
  src/components/DonutChart/DonutChart.test.js
  src/pages/Controllers/ControllerChart/ControllerChart.js
  src/pages/Controllers/ControllerChart/_controller-chart.scss
Labels: Review: Code +1, Review: QA +1

#568 Expanded the readme documentation for QAs
  README.md
Labels: Review: Code +1

#566 Stop pinger on error and enhance Sentry errors
  package.json
  src/app/model-poller.js
  src/index.js
  src/juju/index.js
Labels: Review: Code +1, Review: QA needed

#569 Added 'Writing React components' and 'Writing tests' content to the README.
  README.md
Labels: Review: Code +1

#576 Remove the 'configuration' header in the model list tables and move the column next to the model name.
  src/components/ModelTableList/CloudGroup.js
  src/components/ModelTableList/OwnerGroup.js
  src/components/ModelTableList/StatusGroup.js
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#580 Convert JAAS Dashboard to Juju Dashboard.
  .eslintrc
  package.json
  public/config.js
  public/config.js.go
  public/index.html
  public/manifest.json
  scripts/generate-release-tarball
  scripts/generate-version-file
  src/components/Layout/Layout.js
  src/index.js
Labels: Review: Code +1, Review: QA +1

#579 Fix lint config for installed dependencies.
  .eslintrc
  package.json
  src/app/root.js
  src/components/InfoPanel/InfoPanel.js
  src/components/UserMenu/UserMenu.js
  src/components/UserMenu/__snapshots__/UserMenu.test.js.snap
  src/juju/reducer.js
  src/pages/Models/Details/ModelDetails.test.js
  src/pages/Models/Models.test.js
  src/ui/index.js
  yarn.lock
Labels: Review: Code +1, Review: QA +1
