Repository canonical/juju-dashboard, pull requests merged in 2020-09, with the labels that each got.

#658 Add apps panel to models details page
  src/app/utils.js
  src/components/Filter/Filter.js
  src/components/Filter/_filter.scss
  src/components/SlidePanel/SlidePanel.js
  src/components/SlidePanel/SlidePanel.test.js
  src/components/SlidePanel/_slide-panel.scss
  src/pages/Models/Details/ModelDetails.js
  src/pages/Models/Details/ModelDetails.test.js
  src/pages/Models/Details/_model-details.scss
  src/pages/Models/Details/generators.js
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#672 Allow custom classes to be passed into the slide panel
  src/components/SlidePanel/SlidePanel.js
  src/components/SlidePanel/SlidePanel.test.js
  src/pages/Controllers/Controllers.js
  src/pages/Controllers/_controllers.scss
  src/pages/Models/Details/ModelDetails.js
  src/pages/Models/Details/_model-details.scss
Labels: Review: Code +1, Review: QA +1

#673 Show all controllers in the controller lists
  src/app/actions.js
  src/app/check-auth.js
  src/app/model-poller.js
  src/pages/Controllers/Controllers.js
  src/pages/Controllers/_controllers.scss
Labels: Review: Code +1, Review: QA +1

#678 Convert filter buttons into a ButtonGroup to toggle tables in the Model Details view...and more...
  src/components/ButtonGroup/ButtonGroup.js
  src/components/ButtonGroup/ButtonGroup.test.js
  src/components/ButtonGroup/_button-group.scss
  src/components/FilterTags/FilterTags.js
  src/components/LogIn/LogIn.js
  src/components/ModelGroupToggle/ModelGroupToggle.js
  src/components/ModelGroupToggle/ModelGroupToggle.test.js
  src/hooks/useQueryString.js
  src/pages/Models/Details/ModelDetails.js
  src/pages/Models/Details/ModelDetails.test.js
  src/pages/Models/Details/_model-details.scss
  src/pages/Models/Models.js
  src/pages/Models/Models.test.js
Labels: Review: Code +1, Review: QA +1

#675 Hook up the terminal UI to the new Juju commands backend for the web cli.
  src/app/selectors.js
  src/components/Terminal/Terminal.js
  src/components/Terminal/setup-terminal.js
  src/components/Terminal/xterm-addon-juju.js
  src/pages/Models/Details/ModelDetails.js
Labels: Review: Code needed, Review: QA +1

#681 Add entity counts to each view in the model details page
  .gitignore
  src/app/utils.js
  src/components/Counts/Counts.js
  src/components/Counts/Counts.test.js
  src/components/Counts/_counts.scss
  src/components/InfoPanel/_info-panel.scss
  src/pages/Models/Details/ModelDetails.js
  src/pages/Models/Details/ModelDetails.test.js
  src/pages/Models/Details/_model-details.scss
Labels: Review: Code +1, Review: Design needed, Review: QA +1, Review: UX +1

#682 Refactor apps panel
  package.json
  src/app/selectors.js
  src/app/utils.js
  src/components/App/App.js
  src/components/ButtonGroup/ButtonGroup.test.js
  src/components/SlidePanel/SlidePanel.js
  src/components/SlidePanel/_slide-panel.scss
  src/components/panels/AppsPanel/AppsPanel.js
  src/components/panels/AppsPanel/_apps-panel.scss
  src/hooks/useQueryString.js
  src/pages/Models/Details/ModelDetails.js
  src/pages/Models/Details/ModelDetails.test.js
  src/pages/Models/Details/_model-details.scss
  src/pages/Models/Details/generators.js
  src/pages/Models/Models.js
  src/pages/Models/Models.test.js
  yarn.lock
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#691 Update controllers header element
  src/pages/Controllers/_controllers.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#690 Revise panel
  src/components/SlidePanel/_slide-panel.scss
  src/pages/Models/Details/ModelDetails.js
  src/pages/Models/Details/_model-details.scss
  src/pages/Models/Details/generators.js
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#686 Add an offline banner
  src/components/Banner/Banner.js
  src/components/Banner/Banner.test.js
  src/components/Banner/_banner.scss
  src/components/Layout/Layout.js
  src/hooks/useOffline.js
Labels: Review: Code +1, Review: QA +1

#696 Add machines and units panels to model details pages
  src/app/utils.js
  src/components/InfoPanel/InfoPanel.js
  src/components/SlidePanel/_slide-panel.scss
  src/components/panels/AppsPanel/AppsPanel.js
  src/components/panels/AppsPanel/_apps-panel.scss
  src/components/panels/MachinesPanel/MachinesPanel.js
  src/components/panels/MachinesPanel/_machines-panel.scss
  src/components/panels/UnitsPanel/UnitsPanel.js
  src/components/panels/UnitsPanel/_units-panel.scss
  src/components/panels/_panels.scss
  src/hooks/useModelStatus.js
  src/pages/Models/Details/ModelDetails.js
  src/pages/Models/Details/ModelDetails.test.js
  src/pages/Models/Details/_model-details.scss
  src/pages/Models/Details/generators.js
Labels: Review: Code +1, Review: QA +1

#693 MVP to render the cross model relations and offers
  src/pages/Models/Details/ModelDetails.js
  src/pages/Models/Details/generators.js
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1
