Repository canonical/juju-dashboard, pull requests merged in 2020-01, with the labels that each got.

#269 Add status icon to owners grouping tables
  src/components/ModelTableList/OwnerGroup.js
  src/components/ModelTableList/OwnerGroup.test.js
  src/components/ModelTableList/StatusGroup.test.js
  src/components/ModelTableList/__snapshots__/OwnerGroup.test.js.snap
  src/components/ModelTableList/__snapshots__/StatusGroup.test.js.snap
Labels: Review: Code +1, Review: QA +1

#274 Update run script to 3.4.3
  run
Labels: Review: Code +1, Review: QA +1

#272 Persist model grouping via URL
  package.json
  src/components/ModelGroupToggle/ModelGroupToggle.js
  src/components/ModelGroupToggle/ModelGroupToggle.test.js
  src/components/ModelTableList/OwnerGroup.js
  src/components/ModelTableList/StatusGroup.js
  src/components/ModelTableList/__snapshots__/OwnerGroup.test.js.snap
  src/components/ModelTableList/__snapshots__/StatusGroup.test.js.snap
  src/pages/Models/Models.js
  src/pages/Models/Models.test.js
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#276 Add a report a bug link to the navigation
  src/components/Layout/__snapshots__/Layout.test.js.snap
  src/components/PrimaryNav/PrimaryNav.js
  src/components/PrimaryNav/__snapshots__/PrimaryNav.test.js.snap
  src/components/PrimaryNav/_primary-nav.scss
  src/static/images/icons/bug-icon.svg
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#280 Add basepath to router
  .env
  src/components/App/App.js
  src/components/App/__snapshots__/App.test.js.snap
Labels: Review: Code +1, Review: QA +1

#271 Add model data counts to top of the controller view
  src/app/selectors.js
  src/app/utils.js
  src/pages/Controllers/Controllers.js
  src/pages/Controllers/Controllers.test.js
  src/pages/Models/Models.js
Labels: Review: Code +1, Review: QA +1

#281 Multistage dockerfile
  Dockerfile
  nginx.conf
Labels: Review: Code needed, Review: QA needed

#292 Populate filter panel with real data from models
  src/app/selectors.js
  src/app/utils.js
  src/components/FilterTags/FilterTags.js
  src/components/FilterTags/FilterTags.test.js
  src/components/FilterTags/__snapshots__/FilterTags.test.js.snap
  src/components/FilterTags/_filter-tags.scss
  src/components/ModelTableList/shared.js
  src/pages/Models/Models.js
Labels: Review: Code +1, Review: QA +1

#283 Create a component for graphs for controllers overview
  package.json
  src/app/selectors.js
  src/app/utils.js
  src/components/DonutChart/DonutChart.js
  src/components/Layout/__snapshots__/Layout.test.js.snap
  src/components/ModelTableList/StatusGroup.test.js
  src/components/ModelTableList/__snapshots__/CloudGroup.test.js.snap
  src/components/ModelTableList/__snapshots__/OwnerGroup.test.js.snap
  src/components/ModelTableList/__snapshots__/StatusGroup.test.js.snap
  src/components/PrimaryNav/PrimaryNav.test.js
  src/components/PrimaryNav/__snapshots__/PrimaryNav.test.js.snap
  src/pages/Controllers/ControllerChart/ControllerChart.js
  src/pages/Controllers/ControllerChart/ControllerChart.test.js
  src/pages/Controllers/ControllerChart/_controller-chart.scss
  src/pages/Controllers/ControllerOverview/ControllerOverview.js
  src/pages/Controllers/ControllerOverview/_controller-overview.scss
  src/pages/Controllers/Controllers.js
  src/pages/Controllers/Controllers.test.js
  src/pages/Models/Models.test.js
  yarn.lock
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#302 Update Model / Controller icons
  src/static/images/icons/controllers-icon.svg
  src/static/images/icons/models-icon.svg
Labels: Review: Code +1, Review: QA +1

#301 Switch region/cloud in status tables
  src/components/ModelTableList/StatusGroup.js
  src/components/ModelTableList/__snapshots__/StatusGroup.test.js.snap
Labels: Review: Code +1, Review: QA +1

#303 Responsive cleanup
  src/components/Layout/__snapshots__/Layout.test.js.snap
  src/components/PrimaryNav/PrimaryNav.js
  src/components/PrimaryNav/PrimaryNav.test.js
  src/components/PrimaryNav/__snapshots__/PrimaryNav.test.js.snap
  src/components/PrimaryNav/_primary-nav.scss
  src/components/UserIcon/UserIcon.js
  src/components/UserIcon/__snapshots__/UserIcon.test.js.snap
  src/pages/Controllers/Controllers.js
  src/pages/Logs/Logs.js
  src/pages/Logs/__snapshots__/Logs.test.js.snap
  src/pages/Models/Details/ModelDetails.js
  src/pages/Models/Details/_model-details.scss
  src/pages/Models/_models.scss
  src/pages/Usage/Usage.js
  src/pages/Usage/__snapshots__/Usage.test.js.snap
  src/scss/index.scss
Labels: Review: Code needed, Review: QA needed

#304 Position applications in the topology with x,y coordinates
  src/components/InfoPanel/InfoPanel.js
  src/components/InfoPanel/__snapshots__/InfoPanel.test.js.snap
  src/components/InfoPanel/_info-panel.scss
  src/components/Topology/Topology.js
  src/pages/Models/Details/__snapshots__/ModelDetails.test.js.snap
Labels: Review: Code +1, Review: QA +1

#310 Position unplaced applications on the topology
  src/components/Topology/Topology.js
Labels: Review: Code +1, Review: QA +1

#314 Render JAAS instead of the controller UUID
  src/components/ModelTableList/CloudGroup.js
  src/components/ModelTableList/OwnerGroup.js
  src/components/ModelTableList/StatusGroup.js
  src/components/ModelTableList/__snapshots__/CloudGroup.test.js.snap
  src/components/ModelTableList/__snapshots__/OwnerGroup.test.js.snap
  src/components/ModelTableList/__snapshots__/StatusGroup.test.js.snap
  src/components/ModelTableList/shared.js
Labels: Review: Code +1, Review: QA +1

#315 Update deps
  package.json
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#312 Draw a relation lines on the Topology
  src/components/Topology/Topology.js
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#319 Reduce the reliance on snapshots
  src/components/Button/Button.test.js
  src/components/Button/__snapshots__/Button.test.js.snap
  src/components/Filter/Filter.test.js
  src/components/Filter/__snapshots__/Filter.test.js.snap
  src/components/FilterTags/FilterTags.test.js
  src/components/FilterTags/__snapshots__/FilterTags.test.js.snap
  src/components/Header/Header.test.js
  src/components/Header/__snapshots__/Header.test.js.snap
  src/components/InfoPanel/InfoPanel.test.js
  src/components/InfoPanel/__snapshots__/InfoPanel.test.js.snap
  src/components/Layout/Layout.test.js
  src/components/Layout/__snapshots__/Layout.test.js.snap
  src/components/ModelGroupToggle/ModelGroupToggle.test.js
  src/components/ModelGroupToggle/__snapshots__/ModelGroupToggle.test.js.snap
  src/components/ModelTableList/CloudGroup.test.js
  src/components/ModelTableList/OwnerGroup.test.js
  src/components/ModelTableList/StatusGroup.test.js
  src/components/ModelTableList/__snapshots__/CloudGroup.test.js.snap
  src/components/ModelTableList/__snapshots__/OwnerGroup.test.js.snap
  src/components/ModelTableList/__snapshots__/StatusGroup.test.js.snap
  src/components/PrimaryNav/PrimaryNav.test.js
  src/components/PrimaryNav/__snapshots__/PrimaryNav.test.js.snap
  src/pages/Models/Details/ModelDetails.test.js
  src/pages/Models/Details/__snapshots__/ModelDetails.test.js.snap
Labels: Review: Code +1

#322 Set browserslist production to latest
  package.json
Labels: Review: Code +1

#323 Stop munging of the Annotations facade.
  craco.config.js
Labels: Review: Code +1, Review: QA needed

#329 Click to expand topology
  src/components/InfoPanel/InfoPanel.js
  src/components/InfoPanel/InfoPanel.test.js
  src/components/InfoPanel/_info-panel.scss
  src/scss/index.scss
Labels: Review: Code +1, Review: QA +1

#331 Fix back button navigation with model grouping
  src/pages/Models/Models.js
Labels: Review: Code +1, Review: QA +1

#333 Fix up config icon layout issues
  src/components/ModelTableList/shared.js
  src/pages/Models/Details/_model-details.scss
  src/pages/Models/_models.scss
  src/static/images/icons/apps-icon.svg
  src/static/images/icons/units-icon.svg
Labels: Review: Code +1, Review: QA +1

#335 Fix icon colors in sidebar
  src/components/PrimaryNav/PrimaryNav.js
  src/static/images/icons/controllers-icon--selected.svg
  src/static/images/icons/controllers-icon.svg
  src/static/images/icons/logs-icon--selected.svg
  src/static/images/icons/models-icon--selected.svg
  src/static/images/icons/models-icon.svg
  src/static/images/icons/usage-icon--selected.svg
Labels: Review: Code +1, Review: QA +1

#337 Upgrade dependencies
  package.json
  yarn.lock
Labels: Review: Code +1, Review: QA +1
