Repository canonical/juju-dashboard, pull requests merged in 2020-07, with the labels that each got.

#581 Match the logo link with the logo
  src/components/PrimaryNav/PrimaryNav.js
  src/components/PrimaryNav/PrimaryNav.test.js
Labels: Review: Code +1, Review: QA +1

#582 Change the store column value for local charms
  src/pages/Models/Details/ModelDetails.test.js
  src/pages/Models/Details/generators.js
Labels: Review: Code +1, Review: QA +1

#585 Wait for config.js before bootstrap.
  .gitignore
  src/index.js
Labels: Priority: Critical, Review: Code +1, Review: QA +1

#590 Make all links external if juju
  src/components/PrimaryNav/PrimaryNav.js
Labels: Review: Code +1, Review: QA needed

#588 Remove space-on-right bug from models details
  src/components/Header/_header.scss
Labels: Review: Code +1, Review: QA +1

#597 Convert the error messages on the model list page into links.
  src/components/ModelTableList/StatusGroup.js
  src/components/ModelTableList/_model-table-list.scss
  src/components/ModelTableList/shared.js
Labels: Review: Code +1, Review: QA +1

#600 Model list error link no longer falls back to the model name.
  src/components/ModelTableList/CloudGroup.js
  src/components/ModelTableList/OwnerGroup.js
  src/components/ModelTableList/StatusGroup.js
  src/components/ModelTableList/_model-table-list.scss
  src/components/ModelTableList/shared.js
Labels: Review: Code +1, Review: QA +1

#594 Add the ability to register additional controllers
  package.json
  src/app/actions.js
  src/app/check-auth.js
  src/app/model-poller.js
  src/app/root.js
  src/app/selectors.js
  src/components/DonutChart/DonutChart.js
  src/components/Header/_header.scss
  src/components/Layout/Layout.js
  src/components/LogIn/LogIn.js
  src/components/LogIn/__snapshots__/LogIn.test.js.snap
  src/components/ModelTableList/ModelTableList.js
  src/components/SlidePanel/SlidePanel.js
  src/components/SlidePanel/_slide-panel.scss
  src/components/UserMenu/UserMenu.js
  src/components/UserMenu/UserMenu.test.js
  src/index.js
  src/juju/actions.js
  src/juju/actions.test.js
  src/juju/index.js
  src/juju/reducer.js
  src/pages/Controllers/ControllerChart/ControllerChart.js
  src/pages/Controllers/ControllerChart/ControllerChart.test.js
  src/pages/Controllers/ControllerChart/_controller-chart.scss
  src/pages/Controllers/ControllerOverview/ControllerOverview.js
  src/pages/Controllers/ControllerOverview/_controller-overview.scss
  src/pages/Controllers/Controllers.js
  src/pages/Controllers/Controllers.test.js
  src/pages/Controllers/__snapshots__/Controllers.test.js.snap
  src/pages/Controllers/_controllers.scss
  src/scss/index.scss
  src/testing/complete-redux-store-dump.js
Labels: Review: Code +1, Review: QA +1

#619 Use e.g. for example, not ex)
  README.md
  src/app/utils.js
  src/components/ModelTableList/StatusGroup.js
  src/pages/Controllers/Controllers.js
Labels: Review: Code needed, Review: QA needed

#622 Add dockerfile and konf/site.yaml for demos
  Dockerfile
  konf/site.yaml
Labels: Review: QA +1

#621 Format code snippets in form help text
  src/pages/Controllers/Controllers.js
  src/pages/Controllers/_controllers.scss
Labels: Review: Code +1, Review: QA +1

#623 Register controller UX tweaks
  src/app/model-poller.js
  src/pages/Controllers/Controllers.js
  src/pages/Controllers/_controllers.scss
Labels: Review: Code +1, Review: QA +1

#625 Allow the user menu to be toggled without authentication.
  src/app/check-auth.js
Labels: Review: Code +1, Review: QA +1

#627 Connect to and start polling models when registering a new controller
  src/app/model-poller.js
  src/app/selectors.js
  src/juju/actions.js
  src/juju/index.js
  src/pages/Controllers/Controllers.js
Labels: Review: Code +1, Review: QA +1

#634 Fix: Controller page console errors and JAAS controller name display
  src/app/model-poller.js
  src/juju/index.js
  src/pages/Controllers/Controllers.js
Labels: Review: Code +1, Review: QA +1
