Repository canonical/juju-dashboard, pull requests merged in 2020-04, with the labels that each got.

#407 Remove the Prettier overrides and auto-update code
  .prettierrc
  src/app/actions.js
  src/app/check-auth.js
  src/app/model-poller.js
  src/app/root.js
  src/app/selectors.js
  src/app/utils.js
  src/components/ErrorBoundary/ErrorBoundary.js
  src/components/Filter/Filter.js
  src/components/FilterTags/FilterTags.js
  src/components/InfoPanel/InfoPanel.js
  src/components/Layout/Layout.js
  src/components/LogIn/LogIn.js
  src/components/LogIn/LogIn.test.js
  src/components/ModelGroupToggle/ModelGroupToggle.js
  src/components/ModelGroupToggle/ModelGroupToggle.test.js
  src/components/ModelTableList/CloudGroup.js
  src/components/ModelTableList/CloudGroup.test.js
  src/components/ModelTableList/ModelTableList.test.js
  src/components/ModelTableList/OwnerGroup.js
  src/components/ModelTableList/OwnerGroup.test.js
  src/components/ModelTableList/StatusGroup.js
  src/components/ModelTableList/StatusGroup.test.js
  src/components/PrimaryNav/PrimaryNav.js
  src/components/Routes/Routes.js
  src/components/Terminal/Terminal.js
  src/components/Terminal/setup-terminal.js
  src/components/Terminal/xterm-addon-terminado.js
  src/components/Topology/Topology.js
  src/components/UserMenu/UserMenu.js
  src/hooks/useAnalytics.js
  src/index.js
  src/juju/actions.js
  src/juju/actions.test.js
  src/juju/index.js
  src/juju/reducers.js
  src/pages/Controllers/ControllerOverview/ControllerOverview.js
  src/pages/Controllers/Controllers.js
  src/pages/Controllers/Controllers.test.js
  src/pages/Models/Details/ModelDetails.js
  src/pages/Models/Details/generators.js
  src/pages/Models/Models.js
  src/pages/Models/Models.test.js
  src/pages/Settings/Settings.js
  src/scss/functions/_z-index.scss
  src/serviceWorker.js
  src/testing/utils.js
Labels: Review: Code +1

#408 Fix topology modal window
  src/components/InfoPanel/InfoPanel.js
  src/components/InfoPanel/_info-panel.scss
Labels: Review: Code +1, Review: QA +1

#409 Close topology on Escape key click
  src/components/InfoPanel/InfoPanel.js
Labels: Review: Code +1, Review: QA +1

#410 Topology tweaks
  src/components/InfoPanel/InfoPanel.js
Labels: Review: Code +1, Review: QA needed

#406 Add table empty state to models tables
  src/components/ModelTableList/StatusGroup.js
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#416 Set maximum terminal height on drag
  src/components/Terminal/Terminal.js
  src/components/Terminal/_terminal.scss
Labels: Review: Code +1, Review: QA +1

#413 Collapse sidebar on all screens less than 1400px
  src/app/utils.js
  src/components/InfoPanel/InfoPanel.js
  src/components/Layout/Layout.js
Labels: Review: Code +1, Review: QA +1

#428 Fix memory leak on layout resize
  src/components/Layout/Layout.js
Labels: Review: Code +1, Review: QA +1

#429 Remove the env conditional on GA
  src/components/App/App.js
  src/hooks/useAnalytics.js
Labels: Review: Code +1, Review: QA +1

#432 Update renovate config to sync with other projects.
  renovate.json
Labels: Review: Code +1

#422 Prevent body scroll
  package.json
  src/components/Terminal/Terminal.js
  src/components/Terminal/_terminal.scss
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#442 Modify height calculation to avoid the terminal jumping when resizing
  src/components/Terminal/Terminal.js
Labels: Review: Code +1, Review: QA +1

#444 Create a link to go back to the old GUI
  src/components/PrimaryNav/PrimaryNav.js
  src/components/PrimaryNav/_primary-nav.scss
Labels: Review: Code +1, Review: Design needed, Review: QA +1

#437 Populate controller table with model counts
  craco.config.js
  src/app/jimm-facade.js
  src/app/model-poller.js
  src/components/UserMenu/UserMenu.test.js
  src/juju/index.js
  src/pages/Controllers/Controllers.js
  src/pages/Controllers/Controllers.test.js
  src/pages/Controllers/__snapshots__/Controllers.test.js.snap
  src/testing/complete-redux-store-dump.js
Labels: Review: Code +1, Review: QA +1

#441 Change spacing between logo circle and text
  src/components/PrimaryNav/_primary-nav.scss
  src/static/images/logo/juju-text.svg
Labels: Review: Code +1, Review: QA +1

#451 Display the application version from the package.json
  package.json
  src/app/actions.js
  src/app/check-auth.js
  src/app/root.js
  src/app/selectors.js
  src/components/PrimaryNav/PrimaryNav.js
  src/components/PrimaryNav/PrimaryNav.test.js
  src/index.js
  src/testing/complete-redux-store-dump.js
Labels: Review: Code +1, Review: QA +1

#454 Add Discourse link
  src/components/Layout/Layout.js
Labels: Review: Code +1, Review: QA +1

#455 Add missing “to” to release notification
  src/components/Layout/Layout.js
Labels: Review: Code needed

#456 Add event tracking when clicking link to return to old GUI
  src/components/PrimaryNav/PrimaryNav.js
Labels: Review: Code +1

#458 Use state to set localStorage for notification
  src/components/Layout/Layout.js
  src/hooks/useLocalStorage.js
Labels: Review: Code +1, Review: QA +1

#460 Update localstorage uses in components to use the new useLocalStorage hook
  src/components/App/App.js
  src/pages/Settings/Settings.js
Labels: Review: Code +1, Review: QA +1

#466 Temporarily remove the terminal component from rendering.
  src/pages/Models/Details/ModelDetails.js
  src/pages/Models/Details/ModelDetails.test.js
Labels: Review: Code +1, Review: QA +1
