Repository canonical/juju-dashboard, pull requests merged in 2020-05, with the labels that each got.

#471 Send error to sentry if ErrorBoundary is triggered.
  src/components/ErrorBoundary/ErrorBoundary.js
Labels: Review: Code +1, Review: QA needed

#478 Show the version number and beta label in Juju.
  src/components/PrimaryNav/PrimaryNav.js
Labels: Review: Code +1, Review: QA +1

#476 Handle non-admins accessing the Controller view
  src/app/model-poller.js
  src/app/selectors.js
  src/app/utils.js
  src/juju/index.js
  src/pages/Controllers/Controllers.js
  src/pages/Controllers/Controllers.test.js
  src/pages/Controllers/__snapshots__/Controllers.test.js.snap
  src/testing/complete-redux-store-dump.js
Labels: Review: Code +1, Review: QA +1

#474 Generate release build tarball
  .gitignore
  package.json
  scripts/generate-release-tarball
  scripts/generate-version-file
Labels: Review: Code +1, Review: QA +1

#479 bump version.
  package.json
Labels: Review: QA +1

#480 Set correct spacing for 'no models' table caption.
  src/components/ModelTableList/_model-table-list.scss
Labels: Review: Code +1, Review: QA +1

#483 Add full stop and make affirmative action explicit.
  src/pages/Controllers/Controllers.js
  src/pages/Controllers/__snapshots__/Controllers.test.js.snap
Labels: Review: Code +1, Review: QA +1

#487 Tweak hr styling
  src/components/PrimaryNav/PrimaryNav.js
  src/components/PrimaryNav/_primary-nav.scss
Labels: Review: Code +1, Review: QA +1

#490 fix: Correct model detail double padding
  src/components/InfoPanel/_info-panel.scss
  src/pages/Models/Details/_model-details.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#496 fix(model details): Prevent entity icons from expanding to height of table row
  src/pages/Models/Details/_model-details.scss
Labels: Review: Code +1, Review: QA +1

#489 style(settings): Update styling of settings page
  src/pages/Settings/Settings.js
  src/pages/Settings/settings.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#495 (style) Align filter tags to filter menu
  src/components/FilterTags/_filter-tags.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#493 fix: Stop notification overlaying sidebar
  src/components/Layout/_layout.scss
Labels: Review: Code +1, Review: QA +1

#499 fix: Hide release notification until user logged in
  src/components/Layout/Layout.js
Labels: Review: Code +1, Review: QA +1

#503 fix(style): remove small gap between thead and tbody
  src/scss/custom/_tables.scss
Labels: Review: Code +1, Review: QA needed

#502 feat(controllers): show controller data on controller page for single controller environments
  package.json
  src/juju/actions.js
  src/juju/index.js
  src/pages/Controllers/Controllers.js
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#501 fix(model details): correctly display the modelName in the expanded model topology view
  src/components/InfoPanel/InfoPanel.js
Labels: Review: Code +1, Review: QA +1

#494 fix(model details): remove redundant table header
  src/pages/Models/Details/generators.js
  src/scss/_utils.scss
Labels: Review: Code +1, Review: QA +1

#507 Render any login error messages.
  src/app/actions.js
  src/app/check-auth.js
  src/app/model-poller.js
  src/app/root.js
  src/app/selectors.js
  src/components/LogIn/LogIn.js
  src/components/LogIn/LogIn.test.js
  src/components/LogIn/_login.scss
  src/juju/index.js
Labels: Review: Code needed, Review: Design +1

#520 Resolve a number of UI issues
  package.json
  src/app/utils.js
  src/components/InfoPanel/InfoPanel.js
  src/components/InfoPanel/_info-panel.scss
  src/components/LogIn/LogIn.js
  src/pages/Models/Details/ModelDetails.js
  src/pages/Models/Details/ModelDetails.test.js
  src/pages/Models/Details/_model-details.scss
  src/pages/Models/Details/generators.js
Labels: Review: Code +1, Review: Design needed, Review: QA +1

#529 Topology no longer tries to render applications that don't exist.
  src/components/Topology/Topology.js
Labels: Priority: High, Review: Code +1, Review: QA +1

#521 Align tables columns in the machine details
  .stylelintrc
  src/components/Filter/_filter.scss
  src/components/Header/_header.scss
  src/components/ModelTableList/shared.js
  src/pages/Models/Details/ModelDetails.js
  src/pages/Models/Details/_model-details.scss
  src/pages/Models/Details/generators.js
  src/pages/Models/_models.scss
  src/scss/_utils.scss
  src/scss/index.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#528 Fix rendering of local charm name and icon
  package.json
  src/app/utils.js
  src/components/FilterTags/FilterTags.test.js
  src/components/ModelTableList/CloudGroup.test.js
  src/components/ModelTableList/OwnerGroup.test.js
  src/components/ModelTableList/StatusGroup.test.js
  src/components/PrimaryNav/_primary-nav.scss
  src/pages/Models/Details/ModelDetails.js
  src/pages/Models/Details/ModelDetails.test.js
  src/pages/Models/Details/generators.js
  src/pages/Models/Models.test.js
  src/static/images/icons/default-charm-icon.svg
  src/testing/complete-redux-store-dump.js
Labels: Priority: High, Review: Code +1, Review: Design +1, Review: QA +1

#509 Expand the readme to add instructions on accessing via nested vms.
  README.md
Labels: Review: Code needed
