Repository canonical/juju-dashboard, pull requests merged in 2021-07, with the labels that each got.

#1081 Sharing styling tweaks
  .gitignore
  src/app/utils/utils.js
  src/components/ShareCard/ShareCard.tsx
  src/components/ShareCard/_share-card.scss
  src/panels/ShareModelPanel/ShareModel.test.tsx
  src/panels/ShareModelPanel/ShareModel.tsx
  src/panels/ShareModelPanel/share-model.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#1082 Refactor the icon in the sharing heading
  src/panels/ShareModelPanel/ShareModel.tsx
  src/panels/ShareModelPanel/share-model.scss
Labels: Review: Code +1, Review: QA +1

#1095 Update deps.
  package.json
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#1099 Connect to the all model watcher when viewing a model details page
  src/juju/index.js
  src/pages/EntityDetails/Model/Model.js
Labels: Review: Code +1, Review: QA +1

#1100 Type AllWatcher deltas and setup dispatch of the deltas.
  src/app/check-auth.js
  src/juju/actions.js
  src/juju/index.js
  src/juju/reducer.js
  src/juju/types.ts
  src/juju/watchers.ts
  src/pages/EntityDetails/Model/Model.js
Labels: Review: Code +1 (with changes)
