Repository canonical/juju-dashboard, pull requests merged in 2021-01, with the labels that each got.

#805 Add Remote Apps and Offers to the model details page
  src/components/InfoPanel/InfoPanel.js
  src/components/panels/AppsPanel/_apps-panel.scss
  src/components/panels/LocalAppsPanel/LocalAppsPanel.js
  src/components/panels/MachinesPanel/MachinesPanel.js
  src/components/panels/OffersPanel/OffersPanel.tsx
  src/components/panels/RemoteAppsPanel/RemoteAppsPanel.tsx
  src/components/panels/UnitsPanel/UnitsPanel.js
  src/components/panels/_panels.scss
  src/components/panels/shared.tsx
  src/pages/Models/Details/ModelDetails.js
  src/pages/Models/Details/ModelDetails.test.js
  src/pages/Models/Details/_model-details.scss
  src/pages/Models/Details/generators.js
Labels: Review: Code +1, Review: QA +1

#818 Add sidenav width override
  src/scss/index.scss
Labels: Review: Code +1, Review: QA +1

#819 Upgrade jujulib to 2.0.0-beta.3
  package.json
  yarn.lock
Labels: Review: Code needed, Review: QA needed

#817 Add apps icon list to machines table
  src/pages/Models/Details/ModelDetails.test.js
  src/pages/Models/Details/_model-details.scss
  src/pages/Models/Details/generators.js
Labels: Review: Code +1, Review: QA +1

#820 Use Vanilla icons across the app
  src/components/InfoPanel/InfoPanel.js
  src/components/InfoPanel/InfoPanel.test.js
  src/components/ModelTableList/shared.js
  src/components/PrimaryNav/PrimaryNav.js
  src/components/PrimaryNav/_primary-nav.scss
  src/components/UserMenu/UserMenu.js
  src/components/UserMenu/UserMenu.test.js
  src/components/UserMenu/__snapshots__/UserMenu.test.js.snap
  src/components/UserMenu/_user-menu.scss
  src/components/panels/MachinesPanel/MachinesPanel.js
  src/components/panels/MachinesPanel/_machines-panel.scss
  src/components/panels/UnitsPanel/UnitsPanel.js
  src/components/panels/UnitsPanel/_units-panel.scss
  src/components/panels/_panels.scss
  src/scss/index.scss
  src/static/images/icons/apps-icon.svg
  src/static/images/icons/controllers-icon--selected.svg
  src/static/images/icons/controllers-icon.svg
  src/static/images/icons/fullscreen-icon.svg
  src/static/images/icons/logs-icon--selected.svg
  src/static/images/icons/logs-icon.svg
  src/static/images/icons/machines-icon.svg
  src/static/images/icons/models-icon--selected.svg
  src/static/images/icons/models-icon.svg
  src/static/images/icons/units-icon.svg
  src/static/images/icons/usage-icon--selected.svg
  src/static/images/icons/usage-icon.svg
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#824 Check tag in extractCredentialName exists before splitting
  package.json
  src/app/utils.js
Labels: Review: Code +1

#822 Always collapse sidebar on model details pages
  src/components/Layout/Layout.js
  src/components/Layout/Layout.test.js
  src/components/Layout/_layout.scss
Labels: Review: Code +1, Review: QA +1

#815 Create configuration panel UI
  .gitignore
  package.json
  public/config.js
  src/app/utils.js
  src/components/SlidePanel/SlidePanel.js
  src/components/panels/ConfigPanel/BooleanConfig.tsx
  src/components/panels/ConfigPanel/ConfigPanel.tsx
  src/components/panels/ConfigPanel/TextAreaConfig.tsx
  src/components/panels/ConfigPanel/_config-panel.scss
  src/components/panels/LocalAppsPanel/LocalAppsPanel.js
  src/components/panels/LocalAppsPanel/_local-apps-panel.scss
  src/components/panels/OffersPanel/OffersPanel.tsx
  src/components/panels/RemoteAppsPanel/RemoteAppsPanel.tsx
  src/juju/index.js
  src/pages/Models/Details/ModelDetails.js
  src/scss/index.scss
  src/static/images/bulb.svg
  src/types.ts
  yarn.lock
Labels: Review: Code needed, Review: Design +1, Review: QA needed

#825 Add UI for edit config if the charm has no configuration options
  package.json
  src/components/panels/ConfigPanel/ConfigPanel.test.tsx
  src/components/panels/ConfigPanel/ConfigPanel.tsx
  src/components/panels/ConfigPanel/__snapshots__/ConfigPanel.test.tsx.snap
  src/components/panels/ConfigPanel/_config-panel.scss
  src/static/images/bulb.svg
  src/static/images/no-config-params.svg
  src/testing/utils.js
  src/testing/utils.ts
  yarn.lock
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#828 Switch Header component to Typescript
  src/components/Header/Header.js
  src/components/Header/Header.test.tsx
  src/components/Header/Header.tsx
Labels: Review: Code +1, Review: QA +1

#827 Remove multiple scroll bars from slide panels
  src/components/SlidePanel/_slide-panel.scss
Labels: Review: Code +1, Review: QA +1

#829 Remove units view and panel from model details
  src/components/panels/UnitsPanel/UnitsPanel.js
  src/pages/Models/Details/ModelDetails.js
  src/pages/Models/Details/ModelDetails.test.js
Labels: Review: Code +1, Review: QA +1

#830 Add top padding to panels in model details
  src/components/panels/_panels.scss
Labels: Review: Code +1, Review: QA +1

#838 Bump @canonical/jujulib to 2.0.0-beta.4
  package.json
  yarn.lock
Labels: Review: Code needed, Review: QA needed

#837 Convert InfoPanel to Typescript
  package.json
  src/components/InfoPanel/InfoPanel.tsx
  src/declarations/global.d.ts
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#836 Revert function typing in header
  src/components/Header/Header.tsx
Labels: Review: Code +1, Review: QA +1

#839 Mobile support for the config panel
  src/components/panels/ConfigPanel/BooleanConfig.tsx
  src/components/panels/ConfigPanel/ConfigPanel.tsx
  src/components/panels/ConfigPanel/TextAreaConfig.tsx
  src/components/panels/ConfigPanel/_config-panel.scss
  src/components/panels/LocalAppsPanel/_local-apps-panel.scss
Labels: Review: Code +1, Review: Design needed, Review: QA needed

#843 Add UI for viewing and editing charm configuration
  .gitignore
  package.json
  public/config.js
  src/app/utils.js
  src/components/InfoPanel/InfoPanel.tsx
  src/components/SlidePanel/SlidePanel.js
  src/components/panels/ConfigPanel/BooleanConfig.tsx
  src/components/panels/ConfigPanel/ConfigPanel.test.tsx
  src/components/panels/ConfigPanel/ConfigPanel.tsx
  src/components/panels/ConfigPanel/TextAreaConfig.tsx
  src/components/panels/ConfigPanel/__snapshots__/ConfigPanel.test.tsx.snap
  src/components/panels/ConfigPanel/_config-panel.scss
  src/components/panels/LocalAppsPanel/LocalAppsPanel.js
  src/components/panels/LocalAppsPanel/_local-apps-panel.scss
  src/components/panels/OffersPanel/OffersPanel.tsx
  src/components/panels/RemoteAppsPanel/RemoteAppsPanel.tsx
  src/juju/index.js
  src/pages/Models/Details/ModelDetails.js
  src/scss/_settings.scss
  src/scss/index.scss
  src/static/images/bulb.svg
  src/static/images/no-config-params.svg
  src/testing/config-response.js
  src/testing/utils.js
  src/testing/utils.ts
  src/types.ts
  yarn.lock
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX -1

#844 Add animations to the configuration UI
  src/animations/FadeIn.tsx
  src/components/panels/ConfigPanel/BooleanConfig.tsx
  src/components/panels/ConfigPanel/ConfigPanel.tsx
  src/components/panels/ConfigPanel/TextAreaConfig.tsx
  src/components/panels/ConfigPanel/_config-panel.scss
Labels: Review: Code +1, Review: Design needed, Review: QA +1

#834 Refactor model details
  src/app/utils.js
  src/components/Routes/Routes.js
  src/components/panels/LocalAppsPanel/LocalAppsPanel.js
  src/components/panels/MachinesPanel/MachinesPanel.js
  src/pages/ModelDetails/ModelDetails.js
  src/pages/ModelDetails/ModelDetails.test.js
  src/pages/ModelDetails/_model-details.scss
  src/pages/ModelDetails/generators.js
Labels: Review: Code +1, Review: QA +1

#845 Render the config panel based on the URL.
  src/components/SlidePanel/SlidePanel.js
  src/components/panels/ConfigPanel/ConfigPanel.test.tsx
  src/components/panels/ConfigPanel/ConfigPanel.tsx
  src/components/panels/LocalAppsPanel/LocalAppsPanel.js
  src/pages/ModelDetails/ModelDetails.js
Labels: Review: Code +1, Review: QA +1

#846 Refactor to move all panels to top level src
  src/app/utils.js
  src/pages/ModelDetails/ModelDetails.js
  src/panels/ConfigPanel/BooleanConfig.tsx
  src/panels/ConfigPanel/ConfigPanel.test.tsx
  src/panels/ConfigPanel/ConfigPanel.tsx
  src/panels/ConfigPanel/TextAreaConfig.tsx
  src/panels/ConfigPanel/__snapshots__/ConfigPanel.test.tsx.snap
  src/panels/ConfigPanel/_config-panel.scss
  src/panels/LocalAppsPanel/LocalAppsPanel.js
  src/panels/LocalAppsPanel/_local-apps-panel.scss
  src/panels/MachinesPanel/MachinesPanel.js
  src/panels/OffersPanel/OffersPanel.tsx
  src/panels/RemoteAppsPanel/RemoteAppsPanel.tsx
  src/panels/UnitsPanel/UnitsPanel.js
  src/panels/_panels.scss
  src/panels/shared.tsx
  src/tables/tableHeaders.js
  src/tables/tableRows.js
Labels: Review: Code +1, Review: QA +1
