Repository canonical/juju-dashboard, pull requests merged in 2021-02, with the labels that each got.

#854 Add a confirmation dialog to config action buttons.
  package.json
  src/components/ConfirmationModal/ConfirmationModal.tsx
  src/components/ConfirmationModal/_confirmation-modal.scss
  src/components/Layout/Layout.js
  src/components/PrimaryNav/PrimaryNav.test.js
  src/components/SlidePanel/SlidePanel.js
  src/index.js
  src/pages/Controllers/Controllers.test.js
  src/pages/ModelDetails/ModelDetails.js
  src/panels/ConfigPanel/ConfigPanel.test.tsx
  src/panels/ConfigPanel/ConfigPanel.tsx
  src/panels/ConfigPanel/_config-panel.scss
  src/panels/LocalAppsPanel/LocalAppsPanel.js
  src/types.ts
  src/ui/actions.js
  src/ui/actions.ts
  src/ui/index.js
  src/ui/index.ts
  src/ui/selectors.ts
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#861 Make controller tables display conditional on content
  src/pages/Controllers/Controllers.js
  src/pages/ModelDetails/ModelDetails.js
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#855 Add model counts as chips
  src/app/selectors.js
  src/app/utils/utils.js
  src/app/utils/utils.test.js
  src/components/ChipGroup/ChipGroup.test.tsx
  src/components/ChipGroup/ChipGroup.tsx
  src/components/ChipGroup/_chip-group.scss
  src/components/InfoPanel/InfoPanel.tsx
  src/components/ModelTableList/CloudGroup.js
  src/components/ModelTableList/OwnerGroup.js
  src/components/ModelTableList/StatusGroup.js
  src/components/ModelTableList/shared.js
  src/components/StatusStrip/StatusStrip.js
  src/components/StatusStrip/StatusStrip.test.js
  src/components/StatusStrip/_status-strip.scss
  src/components/Topology/Topology.js
  src/components/UserMenu/UserMenu.js
  src/hooks/useModelAttributes.js
  src/juju/index.js
  src/pages/Controllers/ControllerChart/ControllerChart.js
  src/pages/ModelDetails/ModelDetails.js
  src/pages/ModelDetails/ModelDetails.test.js
  src/pages/ModelDetails/_model-details.scss
  src/pages/Models/Models.js
  src/pages/Models/Models.test.js
  src/pages/Models/_models.scss
  src/panels/ConfigPanel/BooleanConfig.tsx
  src/panels/ConfigPanel/ConfigPanel.tsx
  src/panels/ConfigPanel/TextAreaConfig.tsx
  src/panels/LocalAppsPanel/LocalAppsPanel.js
  src/panels/MachinesPanel/MachinesPanel.js
  src/panels/UnitsPanel/UnitsPanel.js
  src/tables/tableRows.js
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#874 Remove release banner
  src/components/Layout/Layout.js
  src/testing/complete-redux-store-dump.js
Labels: Review: Code +1, Review: QA +1

#869 Try and fetch the users user/pass to support environments without an identity provider
  src/juju/index.js
Labels: Review: Code +1, Review: QA +1

#873 Make WebCLI full width
  src/components/WebCLI/_webcli.scss
Labels: Review: Code +1, Review: QA +1

#876 Overlay panels over webcli, if enabled
  src/components/Header/_header.scss
  src/components/SlidePanel/_slide-panel.scss
Labels: Review: Code +1, Review: QA +1

#878 Switch 'Register Controller' panel to use Vanilla panel
  src/animations/FadeIn.tsx
  src/animations/FadeUpIn.tsx
  src/animations/SlideInOut.tsx
  src/app/check-auth.js
  src/components/Aside/Aside.test.tsx
  src/components/Aside/Aside.tsx
  src/components/Aside/_aside.scss
  src/components/Banner/Banner.test.tsx
  src/components/Banner/Banner.tsx
  src/components/Button/Button.test.tsx
  src/components/Button/Button.tsx
  src/components/ButtonGroup/ButtonGroup.test.tsx
  src/components/ButtonGroup/ButtonGroup.tsx
  src/components/ConfirmationModal/ConfirmationModal.tsx
  src/components/Header/Header.tsx
  src/components/Layout/Layout.js
  src/components/Layout/Layout.test.js
  src/components/Layout/_layout.scss
  src/components/RegisterController/RegisterController.js
  src/components/RegisterController/register-controller.scss
  src/components/Routes/Routes.js
  src/pages/Controllers/Controllers.js
  src/pages/Controllers/Controllers.test.js
  src/pages/Controllers/_controllers.scss
  src/pages/NotFound/NotFound.test.js
  src/panels/ConfigPanel/BooleanConfig.tsx
  src/panels/ConfigPanel/ConfigPanel.tsx
  src/panels/ConfigPanel/TextAreaConfig.tsx
  src/panels/OffersPanel/OffersPanel.tsx
  src/panels/RemoteAppsPanel/RemoteAppsPanel.tsx
  src/panels/_panels.scss
  src/panels/panels.tsx
  src/ui/actions.ts
  src/ui/selectors.ts
Labels: Review: Code +1, Review: QA needed

#879 Explicity add modelName as route param
  src/components/InfoPanel/InfoPanel.test.js
  src/components/InfoPanel/InfoPanel.tsx
  src/components/ModelTableList/CloudGroup.js
  src/components/ModelTableList/ModelTableList.js
  src/components/ModelTableList/ModelTableList.test.js
  src/components/ModelTableList/OwnerGroup.js
  src/components/ModelTableList/StatusGroup.js
  src/components/ModelTableList/shared.js
  src/components/Routes/Routes.tsx
  src/components/Routes/TestRoute.tsx
  src/hooks/useAnalytics.tsx
  src/hooks/useModelStatus.js
  src/layout/BaseLayout/BaseLayout.test.tsx
  src/layout/BaseLayout/BaseLayout.tsx
  src/layout/BaseLayout/_base-layout.scss
  src/layout/EntityLayout.tsx
  src/pages/Controllers/Controllers.js
  src/pages/EntityDetails/EntityDetails.js
  src/pages/EntityDetails/EntityDetails.test.js
  src/pages/EntityDetails/_entity-details.scss
  src/pages/Models/Models.js
  src/pages/NotFound/NotFound.js
  src/pages/Settings/Settings.js
  src/panels/LocalAppsPanel/LocalAppsPanel.js
  src/panels/MachinesPanel/MachinesPanel.js
  src/panels/UnitsPanel/UnitsPanel.js
Labels: Review: Code +1, Review: QA +1

#884 Add application details page
  src/components/ChipGroup/ChipGroup.tsx
  src/components/Header/_header.scss
  src/components/Routes/Routes.tsx
  src/declarations/global.d.ts
  src/juju/index.js
  src/layout/BaseLayout/BaseLayout.tsx
  src/layout/EntityLayout.tsx
  src/pages/ControllersIndex/ControllerChart/ControllerChart.js
  src/pages/ControllersIndex/ControllerChart/ControllerChart.test.js
  src/pages/ControllersIndex/ControllerChart/_controller-chart.scss
  src/pages/ControllersIndex/ControllerOverview/ControllerOverview.js
  src/pages/ControllersIndex/ControllerOverview/_controller-overview.scss
  src/pages/ControllersIndex/ControllersIndex.js
  src/pages/ControllersIndex/ControllersIndex.test.js
  src/pages/ControllersIndex/__snapshots__/ControllersIndex.test.js.snap
  src/pages/ControllersIndex/_controllers.scss
  src/pages/EntityDetails/App/App.js
  src/pages/EntityDetails/EntityDetails.js
  src/pages/EntityDetails/EntityDetails.test.js
  src/pages/EntityDetails/Model/Model.js
  src/pages/EntityDetails/Model/Model.test.js
  src/pages/EntityDetails/_entity-details.scss
  src/pages/EntityDetails/counts.js
  src/pages/ModelsIndex/ModelsIndex.js
  src/pages/ModelsIndex/ModelsIndex.test.js
  src/pages/ModelsIndex/_models.scss
Labels: Review: Code +1, Review: QA +1

#883 Added analytics pings for opening and saving charm config.
  src/panels/ConfigPanel/ConfigPanel.tsx
Labels: Review: Code +1, Review: QA +1

#886 Update offline banner wording for consistency
  src/layout/BaseLayout/BaseLayout.tsx
Labels: Review: Code needed, Review: QA needed
