Repository canonical/juju-dashboard, pull requests merged in 2021-06, with the labels that each got.

#1021 Fail gracefully when action logs includes missing applications
  package.json
  src/pages/EntityDetails/Model/ActionLogs/ActionLogs.test.js
  src/pages/EntityDetails/Model/ActionLogs/ActionLogs.tsx
Labels: Review: Code +1, Review: Design needed, Review: QA +1

#1023 Collapse user menu when active if side nav collapses
  src/components/UserMenu/_user-menu.scss
  src/layout/BaseLayout/BaseLayout.test.tsx
  src/layout/BaseLayout/BaseLayout.tsx
  src/layout/BaseLayout/_base-layout.scss
  src/scss/_settings.scss
Labels: Review: Code +1, Review: QA +1

#1024 Add focus state and simple animations to sharing cards
  src/animations/SlideDownFadeOut.tsx
  src/components/ShareCard/ShareCard.test.tsx
  src/components/ShareCard/ShareCard.tsx
  src/components/ShareCard/_share-card.scss
  src/panels/ShareModelPanel/ShareModel.test.tsx
  src/panels/ShareModelPanel/ShareModel.tsx
  src/panels/ShareModelPanel/share-model.scss
Labels: Review: Code +1 (with changes), Review: QA +1

#1025 Support user authentication via macaroons for the Juju web cli.
  package.json
  src/components/WebCLI/WebCLI.js
  src/components/WebCLI/WebCLI.test.js
  yarn.lock
Labels: Review: Code +1 (with changes), Review: QA +1

#1042 Revert removal of mobile navigation bar
  src/layout/BaseLayout/BaseLayout.test.tsx
  src/layout/BaseLayout/BaseLayout.tsx
Labels: Review: Code +1, Review: QA +1

#1039 Update webCLI documentation link.
  src/components/WebCLI/WebCLI.js
  src/components/WebCLI/WebCLI.test.js
  src/components/WebCLI/__snapshots__/WebCLI.test.js.snap
Labels: Review: Code +1 (with changes), Review: QA +1

#1043 Update to Node v16.x
  Dockerfile
Labels: Review: Code +1, Review: QA +1

#1044 Add build-essential for vanilla framework build.
  Dockerfile
Labels: Review: Code +1, Review: QA +1

#1026 Add Toast notifications to sharing UI
  package.json
  src/components/ShareCard/ShareCard.tsx
  src/components/ToastCard/ToastCard.test.tsx
  src/components/ToastCard/ToastCard.tsx
  src/components/ToastCard/_toast-card.scss
  src/layout/BaseLayout/BaseLayout.tsx
  src/panels/ConfigPanel/_config-panel.scss
  src/panels/ShareModelPanel/ShareModel.tsx
  yarn.lock
Labels: Review: Code +1 (with changes), Review: QA +1

#1045 Sharing view toggles on small screens
  src/components/Aside/_aside.scss
  src/panels/ShareModelPanel/ShareModel.test.tsx
  src/panels/ShareModelPanel/ShareModel.tsx
  src/panels/ShareModelPanel/share-model.scss
Labels: Review: Code +1, Review: QA +1

#1047 Add undo action to remove share user toasts
  src/components/ToastCard/ToastCard.test.tsx
  src/components/ToastCard/ToastCard.tsx
  src/components/ToastCard/_toast-card.scss
  src/juju/index.js
  src/panels/ShareModelPanel/ShareModel.tsx
Labels: Review: Code +1, Review: QA +1

#1050 Update button text from 'Share model' to 'Model access'
  src/pages/EntityDetails/Model/Model.js
  src/pages/EntityDetails/Model/Model.test.js
Labels: Review: Code +1 (with changes), Review: QA +1

#1054 Improve specificity of button to show sharing close panel
  src/panels/ShareModelPanel/ShareModel.tsx
  src/panels/ShareModelPanel/share-model.scss
Labels: Review: Code +1, Review: QA +1

#1063 Fix alignment button on mobile share button
  src/panels/ShareModelPanel/share-model.scss
Labels: Review: Code needed, Review: QA needed

#1062 Conditionally render sharing model access button only if access
  src/pages/EntityDetails/Model/Model.js
Labels: Review: Code +1, Review: QA +1

#1056 Share from models index page
  src/components/InfoPanel/InfoPanel.test.js
  src/components/ModelTableList/CloudGroup.js
  src/components/ModelTableList/CloudGroup.test.js
  src/components/ModelTableList/ModelTableList.test.js
  src/components/ModelTableList/OwnerGroup.js
  src/components/ModelTableList/OwnerGroup.test.js
  src/components/ModelTableList/StatusGroup.js
  src/components/ModelTableList/StatusGroup.test.js
  src/components/ModelTableList/_model-table-list.scss
  src/components/ModelTableList/shared.js
  src/components/PanelHeader/PanelHeader.test.tsx
  src/components/PanelHeader/PanelHeader.tsx
  src/hooks/useModelStatus.js
  src/pages/EntityDetails/_entity-details.scss
  src/pages/ModelsIndex/_models.scss
  src/panels/ShareModelPanel/ShareModel.tsx
Labels: Review: Code +1 (with changes), Review: Design +1, Review: QA +1

#1065 Restrict model index visibility to Access button on row hover
  src/app/utils/utils.js
  src/app/utils/utils.test.js
  src/components/ModelTableList/CloudGroup.js
  src/components/ModelTableList/CloudGroup.test.js
  src/components/ModelTableList/OwnerGroup.js
  src/components/ModelTableList/OwnerGroup.test.js
  src/components/ModelTableList/StatusGroup.js
  src/components/ModelTableList/StatusGroup.test.js
  src/components/ModelTableList/_model-table-list.scss
  src/hooks/useActiveUser.tsx
  src/pages/EntityDetails/Model/Model.js
Labels: Review: Code +1, Review: QA +1

#1067 Check for model users before calling info
  src/components/ModelTableList/CloudGroup.js
  src/components/ModelTableList/OwnerGroup.js
  src/components/ModelTableList/StatusGroup.js
  src/pages/EntityDetails/Model/Model.js
Labels: Review: Code +1, Review: QA +1

#1070 Ensure owner share card always appears first
  src/panels/ShareModelPanel/ShareModel.tsx
Labels: Review: Code +1, Review: QA +1

#1068 Return to share list when adding new user on mobile
  src/panels/ShareModelPanel/ShareModel.tsx
  src/panels/ShareModelPanel/share-model.scss
Labels: Review: Code +1, Review: QA +1

#1075 Add status update to share component
  src/components/ShareCard/ShareCard.test.tsx
  src/components/ShareCard/ShareCard.tsx
  src/components/ShareCard/_share-card.scss
  src/juju/index.js
  src/panels/ShareModelPanel/ShareModel.tsx
Labels: Review: Code +1, Review: QA +1

#1069 Improve share error handling
  src/juju/index.js
  src/panels/ShareModelPanel/ShareModel.tsx
Labels: Review: Code +1, Review: QA +1
