Repository canonical/juju-dashboard, pull requests merged in 2021-08, with the labels that each got.

#1112 Updates docker yarn run to use --production
  Dockerfile
  package.json
Labels: Review: QA +1, Review: Code +1

#1110 Store and display model info delta
  package.json
  src/app/check-auth.js
  src/app/utils/utils.js
  src/juju/actions.js
  src/juju/index.js
  src/juju/model-selectors.ts
  src/juju/reducer.js
  src/juju/types.ts
  src/juju/watchers.ts
  src/pages/EntityDetails/Model/Model.js
  src/pages/EntityDetails/Model/Model.test.js
  src/testing/redux-factory.ts
  src/types.ts
  yarn.lock
Labels: Review: QA +1, Review: Code +1 (with changes)

#1115 Store the remaining change deltas in the redux store.
  src/juju/types.ts
  src/juju/watchers.ts
  src/testing/redux-factory.ts
Labels: Review: QA +1, Review: Code +1 (with changes)

#1117 Add missing deltas and simplify delta parsing
  src/juju/types.ts
  src/juju/watchers.ts
Labels: Review: QA +1, Review: Code +1

#1121 Persist the connection for the model watcher when viewing the model details
  Dockerfile
  src/components/Routes/Routes.tsx
  src/components/Routes/TestRoute.tsx
  src/juju/index.js
  src/juju/model-selectors.ts
  src/pages/EntityDetails/Model/Model.js
  src/pages/ModelDetails/ModelDetails.tsx
  src/testing/redux-factory.ts
  src/types.ts
Labels: Review: QA +1, Review: Code +1

#1116 Fail silently if we're unable to make a fullStatus request
  src/juju/index.js
Labels: Review: QA +1, Review: Code +1

#1124 Convert the model details pages to use the new watcher data
  src/app/utils/utils.js
  src/components/EntityInfo/EntityInfo.tsx
  src/juju/model-selectors.ts
  src/juju/types.ts
  src/juju/watchers.ts
  src/pages/EntityDetails/App/App.test.js
  src/pages/EntityDetails/App/App.tsx
  src/pages/EntityDetails/Machine/Machine.js
  src/pages/EntityDetails/Machine/Machine.tsx
  src/pages/EntityDetails/Model/Model.tsx
  src/pages/EntityDetails/Unit/Unit.js
  src/pages/EntityDetails/Unit/Unit.tsx
  src/pages/EntityDetails/counts.ts
  src/pages/ModelDetails/ModelDetails.tsx
  src/tables/tableHeaders.tsx
  src/tables/tableRows.js
  src/testing/redux-factory.ts
Labels: Review: QA +1, Review: Code +1

#1129 Fix some issues related to data availability.
  src/juju/types.ts
  src/pages/EntityDetails/App/App.tsx
  src/tables/tableRows.js
Labels: Review: Code +1
