Repository canonical/juju-dashboard, pull requests merged in 2021-04, with the labels that each got.

#939 Add checkbox column to the unit list.
  src/app/utils/utils.js
  src/components/ButtonGroup/ButtonGroup.test.tsx
  src/components/ButtonGroup/ButtonGroup.tsx
  src/components/EntityInfo/EntityInfo.tsx
  src/components/FormikFormData/FormikFormData.test.js
  src/components/FormikFormData/FormikFormData.tsx
  src/hooks/useTableRowClick.tsx
  src/pages/EntityDetails/App/App.js
  src/pages/EntityDetails/App/App.test.js
  src/pages/EntityDetails/App/App.tsx
  src/pages/EntityDetails/EntityDetails.js
  src/pages/EntityDetails/Model/Model.js
  src/pages/EntityDetails/_entity-details.scss
  src/panels/_panels.scss
  src/tables/tableHeaders.tsx
  src/tables/tableRows.js
Labels: Review: Code +1, Review: QA +1

#940 Add actions button row interactions
  src/app/utils/utils.js
  src/components/ConfirmationModal/_confirmation-modal.scss
  src/pages/EntityDetails/App/App.test.js
  src/pages/EntityDetails/App/App.tsx
  src/pages/EntityDetails/_entity-details.scss
  src/panels/ActionsPanel/ActionsPanel.test.js
  src/panels/ActionsPanel/ActionsPanel.tsx
  src/panels/ActionsPanel/_actions-panel.scss
  src/static/images/run-action-icon.svg
Labels: Review: Code +1 (with changes), Review: QA +1

#950 Bump the jaaslib to 0.6.1
  package.json
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#953 Wrap content in the entity panel if info is too long
  src/components/EntityInfo/_entity-info.scss
Labels: Review: Code +1, Review: QA +1

#951 Indicate the provider type throughout entity details
  src/pages/EntityDetails/App/App.tsx
  src/pages/EntityDetails/Model/Model.js
  src/pages/EntityDetails/Unit/Unit.js
Labels: Review: Code +1, Review: QA +1

#958 Display the version of an application correctly on the application list
  src/tables/tableHeaders.tsx
  src/tables/tableRows.js
Labels: Review: Code +1, Review: QA +1

#957 Add a provider icon to the model list
  src/components/ModelTableList/OwnerGroup.js
  src/components/ModelTableList/StatusGroup.js
  src/components/ModelTableList/StatusGroup.test.js
  src/components/ModelTableList/shared.js
  src/pages/EntityDetails/_entity-details.scss
  src/static/images/logo/cloud/aws.svg
  src/static/images/logo/cloud/azure.svg
  src/static/images/logo/cloud/gce.svg
  src/static/images/logo/cloud/kubernetes.svg
Labels: Review: Code +1 (with changes), Review: Design +1, Review: QA +1

#962 Remove machines for k8s
  src/pages/EntityDetails/App/App.tsx
  src/pages/EntityDetails/EntityDetails.js
  src/pages/EntityDetails/Unit/Unit.js
  src/tables/tableHeaders.tsx
  src/tables/tableRows.js
Labels: Review: Code +1, Review: QA +1

#961 General improvements to the table data displayed
  src/tables/tableHeaders.tsx
  src/tables/tableRows.js
Labels: Review: Code +1, Review: QA +1

#960 Render the action logs output to the Actions Logs page
  src/app/utils/utils.js
  src/components/PrimaryNav/PrimaryNav.js
  src/juju/index.js
  src/pages/EntityDetails/App/App.test.js
  src/pages/EntityDetails/App/App.tsx
  src/pages/EntityDetails/EntityDetails.js
  src/pages/EntityDetails/Model/ActionLogs/ActionLogs.test.js
  src/pages/EntityDetails/Model/ActionLogs/ActionLogs.tsx
  src/pages/EntityDetails/Model/Model.js
  src/pages/EntityDetails/Model/Model.test.js
  src/pages/EntityDetails/_entity-details.scss
  src/scss/custom/_status_icons.scss
  src/static/images/action-logs-icon.svg
  src/testing/list-operations-api-response.json
Labels: Review: Code +1 (with changes), Review: QA +1

#969 Add empty state for action logs
  src/pages/EntityDetails/Model/ActionLogs/ActionLogs.tsx
Labels: Review: Code +1, Review: QA +1

#971 Fix a number of issues
  package.json
  src/pages/EntityDetails/App/App.test.js
  src/pages/EntityDetails/App/App.tsx
  src/pages/EntityDetails/Unit/Unit.js
  src/pages/EntityDetails/_entity-details.scss
  src/pages/EntityDetails/counts.js
  src/panels/ConfigPanel/ConfigPanel.tsx
Labels: Review: Code +1 (with changes), Review: QA +1

#975 Fetch charm icon from charmhub for charms deployed from there
  package.json
  src/app/utils/utils.js
  src/tables/tableRows.js
Labels: Review: Code +1, Review: QA +1

#982 Fix bug in executing and displaying actions in Juju 2.9
  package.json
  src/juju/index.js
  src/pages/EntityDetails/Model/ActionLogs/ActionLogs.tsx
Labels: Review: Code +1, Review: QA +1

#984 Fix close button position in the offline banner
  src/components/Banner/_banner.scss
Labels: Review: Code +1, Review: QA +1

#983 Add Sharing panel to model detail pages
  package.json
  src/app/selectors.js
  src/app/utils/utils.js
  src/app/utils/utils.test.js
  src/components/Aside/Aside.tsx
  src/components/Aside/_aside.scss
  src/pages/EntityDetails/Model/Model.js
  src/panels/ShareModelPanel/ShareModel.test.tsx
  src/panels/ShareModelPanel/ShareModel.tsx
  src/panels/ShareModelPanel/share-model.scss
  src/panels/panels.tsx
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#986 Update readme to remove usage of the run script
  README.md
Labels: Review: Code needed
