Repository canonical/juju-dashboard, pull requests merged in 2021-03, with the labels that each got.

#892 Switch button group with tabs in model details
  src/components/Header/_header.scss
  src/components/SlidePanel/_slide-panel.scss
  src/pages/ControllersIndex/ControllersIndex.js
  src/pages/ControllersIndex/_controllers.scss
  src/pages/EntityDetails/EntityDetails.js
  src/pages/EntityDetails/Model/Model.test.js
  src/pages/EntityDetails/_entity-details.scss
  src/pages/ModelsIndex/ModelsIndex.js
  src/pages/ModelsIndex/_models.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#895 Improve the responsive navigation styling
  src/components/Header/_header.scss
  src/pages/ControllersIndex/ControllersIndex.js
  src/pages/EntityDetails/_entity-details.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#894 Update button group styling
  src/components/ButtonGroup/_button-group.scss
  src/pages/ModelsIndex/_models.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#897 Implement the breadcrumb component in the header
  src/app/utils/utils.js
  src/components/Breadcrumb/Breadcrumb.test.tsx
  src/components/Breadcrumb/Breadcrumb.tsx
  src/pages/EntityDetails/EntityDetails.js
  src/pages/EntityDetails/_entity-details.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#904 Address the navigations design polish comments
  src/components/Breadcrumb/Breadcrumb.tsx
  src/components/Breadcrumb/_breadcrumbs.scss
  src/components/Header/_header.scss
  src/components/PrimaryNav/_primary-nav.scss
  src/pages/EntityDetails/EntityDetails.js
  src/pages/EntityDetails/Model/Model.test.js
  src/pages/EntityDetails/_entity-details.scss
  src/pages/ModelsIndex/_models.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#900 Update dockerfile to use serve instead of http.server
  Dockerfile
Labels: Review: Code +1, Review: QA +1

#915 Update breadcrumbs to support unit details
  src/components/Breadcrumb/Breadcrumb.test.tsx
  src/components/Breadcrumb/Breadcrumb.tsx
  src/components/Routes/Routes.tsx
  src/hooks/useTableRowClick.tsx
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#918 Populate actions list with real data
  src/components/PanelHeader/PanelHeader.tsx
  src/components/RadioInputBox/RadioInputBox.tsx
  src/components/RadioInputBox/_radio-input-box.scss
  src/juju/index.js
  src/pages/EntityDetails/App/App.js
  src/panels/ActionsPanel/ActionsPanel.tsx
  src/panels/ActionsPanel/_actions-panel.scss
  src/panels/RegisterController/RegisterController.js
Labels: Review: Code +1, Review: UX +1

#920 Fix the unit row click from machines
  src/hooks/useTableRowClick.tsx
  src/pages/EntityDetails/Machine/Machine.js
Labels: Review: Code +1, Review: QA +1

#921 Split out NotFound component
  src/components/NotFound/NotFound.test.tsx
  src/components/NotFound/NotFound.tsx
  src/components/Routes/Routes.tsx
  src/pages/NotFound/NotFound.js
  src/pages/PageNotFound/PageNotFound.js
  src/pages/PageNotFound/PageNotFound.test.js
Labels: Review: Code +1, Review: QA +1

#909 Add ContentReveal to Models entity view
  src/components/App/App.js
  src/components/ChipGroup/ChipGroup.test.tsx
  src/components/ChipGroup/ChipGroup.tsx
  src/components/ContentReveal/ContentReveal.test.tsx
  src/components/ContentReveal/ContentReveal.tsx
  src/components/ContentReveal/_content-reveal.scss
  src/pages/EntityDetails/Model/Model.js
  src/pages/EntityDetails/counts.js
Labels: Review: Code +1, Review: QA +1

#916 Panel improvements
  src/components/Aside/_aside.scss
  src/components/LogIn/LogIn.js
  src/components/LogIn/LogIn.test.js
  src/panels/panels.test.tsx
  src/panels/panels.tsx
Labels: Review: Code needed, Review: QA needed

#924 Fix aside styling and animations
  src/animations/SlideInOut.tsx
  src/components/Aside/Aside.tsx
  src/components/Aside/_aside.scss
  src/layout/BaseLayout/_base-layout.scss
Labels: Review: Code +1, Review: QA +1

#926 Add interactivity to selecting an action in the Actions panel
  src/components/RadioInputBox/DescriptionSummary.test.js
  src/components/RadioInputBox/DescriptionSummary.tsx
  src/components/RadioInputBox/RadioInputBox.tsx
  src/components/RadioInputBox/__snapshots__/DescriptionSummary.test.js.snap
  src/components/RadioInputBox/_radio-input-box.scss
  src/panels/ActionsPanel/ActionsPanel.tsx
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#930 Wrap the section button-group at a higher breakpoint
  src/pages/ModelsIndex/_models.scss
Labels: Review: Code +1, Review: QA +1

#932 Execute action when selecting an action and hitting submit
  .prettierignore
  package.json
  src/components/LoadingHandler/LoadingHandler.test.js
  src/components/LoadingHandler/LoadingHandler.tsx
  src/components/LoadingHandler/_loading-handler.scss
  src/components/RadioInputBox/OptionInputs.test.js
  src/components/RadioInputBox/OptionInputs.tsx
  src/components/RadioInputBox/RadioInputBox.test.js
  src/components/RadioInputBox/RadioInputBox.tsx
  src/components/RadioInputBox/__snapshots__/OptionInputs.test.js.snap
  src/juju/index.js
  src/panels/ActionsPanel/ActionOptions.test.tsx
  src/panels/ActionsPanel/ActionOptions.tsx
  src/panels/ActionsPanel/ActionsPanel.test.js
  src/panels/ActionsPanel/ActionsPanel.tsx
  src/panels/ActionsPanel/_actions-panel.scss
  src/setupTests.js
  src/testing/actions-list-api-response.json
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#936 Add a confirmation dialog before submitting an action.
  src/components/ConfirmationModal/ConfirmationModal.test.js
  src/components/ConfirmationModal/ConfirmationModal.tsx
  src/components/ConfirmationModal/_confirmation-modal.scss
  src/panels/ActionsPanel/ActionsPanel.test.js
  src/panels/ActionsPanel/ActionsPanel.tsx
  src/panels/ActionsPanel/_actions-panel.scss
  src/panels/ConfigPanel/ConfigPanel.tsx
Labels: Review: Code +1, Review: QA +1
