Repository canonical/juju-dashboard, pull requests merged in 2022-10, with the labels that each got.

#1273 Upgrade bakery dependency.
  package.json
  yarn.lock
Labels: Review: QA needed, Review: Code needed

#1275 Set up GitHub actions
  .circleci/config.yml
  .github/workflows/actions.yml
Labels: Review: Code +1

#1236 Get missing action logs
  src/juju/index.js
  src/pages/EntityDetails/Model/ActionLogs/ActionLogs.test.js
  src/pages/EntityDetails/Model/ActionLogs/ActionLogs.tsx
  src/pages/EntityDetails/Model/ActionLogs/_action-logs.scss
  src/testing/list-actions-api-response.json
Labels: Review: QA needed, Review: Code needed

#1276 add support for juju 3.0 beta4
  package.json
  src/juju/index.js
  yarn.lock
Labels: Review: QA +1

#1278 Upgrade to vanilla 3.0 and react-components 0.37
  package.json
  src/components/Aside/Aside.tsx
  src/components/Aside/_aside.scss
  src/components/Banner/_banner.scss
  src/components/ButtonGroup/_button-group.scss
  src/components/ChipGroup/_chip-group.scss
  src/components/ConfirmationModal/ConfirmationModal.tsx
  src/components/ConfirmationModal/_confirmation-modal.scss
  src/components/Filter/Filter.js
  src/components/Filter/Filter.test.js
  src/components/Filter/_filter.scss
  src/components/Header/_header.scss
  src/components/InfoPanel/InfoPanel.tsx
  src/components/InfoPanel/_info-panel.scss
  src/components/LoadingHandler/LoadingHandler.test.js
  src/components/LoadingHandler/LoadingHandler.tsx
  src/components/LogIn/LogIn.js
  src/components/Logo/Logo.js
  src/components/ModelTableList/CloudGroup.js
  src/components/ModelTableList/OwnerGroup.js
  src/components/ModelTableList/StatusGroup.js
  src/components/ModelTableList/_model-table-list.scss
  src/components/PrimaryNav/PrimaryNav.js
  src/components/PrimaryNav/_primary-nav.scss
  src/components/SlidePanel/SlidePanel.js
  src/components/SlidePanel/_slide-panel.scss
  src/components/WebCLI/_webcli.scss
  src/declarations/global.d.ts
  src/layout/BaseLayout/BaseLayout.tsx
  src/layout/BaseLayout/_base-layout.scss
  src/pages/ControllersIndex/ControllerChart/_controller-chart.scss
  src/pages/ControllersIndex/ControllersIndex.js
  src/pages/EntityDetails/App/App.tsx
  src/pages/EntityDetails/Machine/Machine.tsx
  src/pages/EntityDetails/Model/ActionLogs/ActionLogs.tsx
  src/pages/EntityDetails/Model/Model.tsx
  src/pages/EntityDetails/Unit/Unit.tsx
  src/pages/EntityDetails/_entity-details.scss
  src/pages/ModelsIndex/ModelsIndex.js
  src/pages/ModelsIndex/_models.scss
  src/pages/Settings/Settings.js
  src/pages/Settings/settings.scss
  src/panels/ActionsPanel/ActionsPanel.tsx
  src/panels/ConfigPanel/ConfigPanel.tsx
  src/panels/ConfigPanel/_config-panel.scss
  src/panels/_panels.scss
  src/scss/_breakpoints.scss
  src/scss/custom/_tables.scss
  src/scss/index.scss
  yarn.lock
Labels: Review: QA +1, Review: Code +1 (with changes)
