Repository canonical/juju-dashboard, pull requests merged in 2023-11, with the labels that each got.

#1650 Use the apps renovate config
  .github/workflows/actions.yml
  renovate.json
Labels: Review: Code +1

#1651 Include ReBAC Admin package
  HACKING.md
  package.json
  src/components/PrimaryNav/PrimaryNav.test.tsx
  src/components/PrimaryNav/PrimaryNav.tsx
  src/components/Routes/Routes.tsx
  src/juju/watchers.ts
  src/pages/Permissions/Permissions.test.tsx
  src/pages/Permissions/Permissions.tsx
  src/pages/Permissions/index.ts
  src/urls.ts
  yarn.lock
Labels: Review: QA +1, Review: Code +1 (with changes)

#1653 WD-7282 - fix: Display dashboard with 0 controllers
  src/juju/api.test.ts
  src/juju/api.ts
  src/juju/jimm/JIMMV3.ts
  src/pages/ControllersIndex/ControllersIndex.tsx
  src/store/juju/selectors.test.ts
  src/store/juju/selectors.ts
Labels: Review: QA +1, Review: Code +1

#1654 WD-7354 - fix: Fix Audit Logs filter
  src/components/AuditLogsTable/AuditLogsTable.test.tsx
  src/juju/jimm/JIMMV3.ts
  src/store/juju/selectors.test.ts
  src/store/juju/selectors.ts
  src/testing/factories/juju/jimm.ts
Labels: Review: QA +1, Review: Code +1

#1657 WD-7498 - Remove horizontal scrolling from controllers
  src/components/ModelTableList/_model-table-list.scss
  src/pages/ControllersIndex/ControllerOverview/_controller-overview.scss
  src/pages/ControllersIndex/ControllersIndex.tsx
  src/pages/ControllersIndex/_controllers.scss
  src/pages/EntityDetails/_entity-details.scss
  src/scss/custom/_tables.scss
Labels: Review: QA +1, Review: Code +1

#1658 WD-7495 - Make model tables responsive
  src/components/ModelTableList/CloudGroup.test.tsx
  src/components/ModelTableList/CloudGroup.tsx
  src/components/ModelTableList/OwnerGroup.test.tsx
  src/components/ModelTableList/OwnerGroup.tsx
  src/components/ModelTableList/StatusGroup.test.tsx
  src/components/ModelTableList/StatusGroup.tsx
  src/components/ModelTableList/_model-table-list.scss
  src/components/ModelTableList/shared.test.tsx
  src/components/ModelTableList/shared.tsx
  src/pages/ControllersIndex/ControllersIndex.tsx
  src/pages/EntityDetails/App/App.tsx
  src/pages/EntityDetails/Machine/Machine.tsx
  src/pages/EntityDetails/Model/Model.tsx
  src/pages/EntityDetails/Unit/Unit.tsx
  src/pages/Logs/Logs.tsx
  src/store/juju/selectors.test.ts
  src/store/juju/selectors.ts
Labels: Review: QA +1, Review: Code +1

#1659 WD-7606 - feat: Remove "Access" column in controllers table
  src/pages/ControllersIndex/ControllersIndex.test.tsx
  src/pages/ControllersIndex/ControllersIndex.tsx
Labels: Review: QA +1, Review: Code +1

#1660 WD-7607 - fix: Specify cloud info for JIMM controllers
  src/pages/ControllersIndex/ControllersIndex.test.tsx
  src/pages/ControllersIndex/ControllersIndex.tsx
Labels: Review: QA +1, Review: Code +1 (with changes)

#1661 WD-7494 - Make action logs table responsive
  src/components/Status/Status.test.tsx
  src/components/Status/Status.tsx
  src/pages/EntityDetails/Model/Logs/ActionLogs/ActionLogs.test.tsx
  src/pages/EntityDetails/Model/Logs/ActionLogs/ActionLogs.tsx
  src/pages/EntityDetails/Model/Logs/ActionLogs/_action-logs.scss
  src/scss/_utils.scss
  src/scss/custom/_status_icons.scss
Labels: Review: QA +1, Review: Code +1

#1662 WD-7613 - Make integrations tables responsive
  src/pages/ControllersIndex/_controllers.scss
  src/pages/EntityDetails/Model/Model.test.tsx
  src/pages/EntityDetails/Model/Model.tsx
  src/pages/EntityDetails/_entity-details.scss
Labels: Review: QA +1, Review: Code +1

#1666 WD-7645 - refactor: Remove hardcoded public JAAS UUID
  src/components/ModelTableList/ModelTableList.test.tsx
  src/components/ModelTableList/shared.test.tsx
  src/components/ModelTableList/shared.tsx
  src/pages/ControllersIndex/ControllersIndex.test.tsx
  src/pages/ControllersIndex/ControllersIndex.tsx
  src/store/juju/utils/controllers.test.ts
  src/store/juju/utils/controllers.ts
Labels: Review: QA +1, Review: Code +1

#1667 WD-7500 - Make machines table responsive
  src/pages/EntityDetails/_entity-details.scss
  src/tables/tableRows.tsx
Labels: Review: QA +1, Review: Code +1

#1668 WD-7503 - Make unit tables responsive
  src/pages/EntityDetails/App/App.test.tsx
  src/pages/EntityDetails/App/App.tsx
  src/pages/EntityDetails/Machine/Machine.tsx
  src/pages/EntityDetails/Unit/Unit.tsx
  src/pages/EntityDetails/_entity-details.scss
  src/tables/tableRows.tsx
Labels: Review: QA +1, Review: Code +1 (with changes)
