Repository canonical/juju-dashboard, pull requests merged in 2023-03, with the labels that each got.

#1396 WD-2379 - Include custom icons in CSS
  src/pages/EntityDetails/App/App.tsx
  src/pages/EntityDetails/Model/ApplicationsTab/ApplicationsTab.tsx
  src/pages/EntityDetails/_entity-details.scss
  src/scss/custom/_icons.scss
  src/scss/index.scss
  src/static/images/action-logs-icon.svg
  src/static/images/run-action-icon.svg
  src/static/images/unit-tree.svg
Labels: Review: QA +1, Review: Code +1

#1394 WD-2356 - Support boolean action options
  src/components/RadioInputBox/OptionInputs.test.tsx
  src/components/RadioInputBox/OptionInputs.tsx
  src/panels/ActionsPanel/ActionsPanel.test.tsx
  src/panels/ActionsPanel/ActionsPanel.tsx
  src/panels/ActionsPanel/CharmActionsPanel.tsx
Labels: Review: QA +1, Review: Code +1

#1391 WD-2350 - Fix "no models" appearing while loading
  src/pages/ModelsIndex/ModelsIndex.test.tsx
  src/pages/ModelsIndex/ModelsIndex.tsx
  src/store/juju/selectors.test.ts
  src/store/juju/selectors.ts
Labels: Review: QA +1, Review: Code +1

#1390 WD-2351- Display controller endpoint configuration errors.
  public/config.js
  public/config.js.go
  src/index.tsx
Labels: Review: QA +1, Review: Code +1

#1392 WD-2349 - Default CLI help
  src/components/WebCLI/Output.js
  src/components/WebCLI/WebCLI.test.tsx
  src/components/WebCLI/WebCLI.tsx
  src/components/WebCLI/__snapshots__/WebCLI.test.tsx.snap
  src/components/WebCLI/_webcli.scss
Labels: Review: QA +1, Review: Code +1

#1399 WD-2410 - Compensate for WebCLI
  src/components/WebCLI/_webcli.scss
  src/layout/BaseLayout/_base-layout.scss
  src/pages/EntityDetails/EntityDetails.test.tsx
  src/pages/EntityDetails/EntityDetails.tsx
  src/scss/_variables.scss
Labels: Review: QA +1, Review: Code +1

#1403 WD-2427 - Unit local app title
  src/pages/EntityDetails/Machine/Machine.tsx
  src/pages/EntityDetails/Model/ApplicationsTab/ApplicationsTab.tsx
  src/pages/EntityDetails/Unit/Unit.tsx
  src/tables/tableHeaders.tsx
Labels: Review: QA +1, Review: Code +1

#1402 WD-2426 - Fix status responses with null annotations
  src/juju/api.ts
Labels: Review: Code +1

#1400 WD-2424 - Display unknown action log dates
  src/pages/EntityDetails/Model/ActionLogs/ActionLogs.test.tsx
  src/pages/EntityDetails/Model/ActionLogs/ActionLogs.tsx
Labels: Review: QA +1, Review: Code +1

#1410 Show action payload in details
  src/components/utils.tsx
  src/pages/EntityDetails/Model/ActionLogs/ActionLogs.test.tsx
  src/pages/EntityDetails/Model/ActionLogs/ActionLogs.tsx
  src/pages/EntityDetails/Model/ActionLogs/_action-logs.scss
Labels: Review: QA +1, Review: Code +1

#1412 WD-2514 - Fix config title truncation
  src/panels/ConfigPanel/ConfigPanel.tsx
  src/panels/ConfigPanel/_config-panel.scss
Labels: Review: QA +1, Review: Code +1

#1406 WD-2457 - Add help about admins executing actions
  src/panels/ShareModelPanel/ShareModel.tsx
Labels: Review: QA needed, Review: Code +1

#1401 WD-2425 - Display the controller region and cloud
  src/juju/api.ts
  src/store/juju/thunks.ts
  src/store/middleware/check-auth.ts
Labels: Review: QA +1, Review: Code +1

#1409 WD-2458 - Fix config panel scrolling
  src/components/Header/_header.scss
  src/components/SlidePanel/_slide-panel.scss
  src/panels/ConfigPanel/ConfigPanel.tsx
  src/panels/ConfigPanel/_config-panel.scss
  src/scss/_variables.scss
Labels: Review: QA +1, Review: Code +1

#1405 WD-2456 - Remove custom th spacing for controllers
  src/pages/ControllersIndex/_controllers.scss
Labels: Review: QA needed, Review: Code +1

#1414 Fix resizing the CLI on mobile
  src/components/WebCLI/Output.tsx
  src/components/WebCLI/WebCLI.tsx
  src/components/WebCLI/_webcli.scss
  src/layout/BaseLayout/_base-layout.scss
  src/scss/_variables.scss
Labels: Review: QA +1, Review: Code +1

#1413 Fix the actions help
  src/panels/ShareModelPanel/ShareModel.tsx
Labels: Review: QA needed, Review: Code +1

#1398 WD-2409- Display copy button for ip addresses
  src/scss/custom/_tables.scss
  src/tables/tableRows.tsx
Labels: Review: QA +1, Review: Code +1

#1415 WD-2575 - Improve chart props
  package.json
  src/components/DonutChart/DonutChart.test.tsx
  src/components/DonutChart/DonutChart.tsx
  src/pages/ControllersIndex/ControllerChart/ControllerChart.test.tsx
  src/pages/ControllersIndex/ControllerChart/ControllerChart.tsx
  src/pages/ControllersIndex/ControllerOverview/ControllerOverview.tsx
  yarn.lock
Labels: Review: Code +1

#1397 Notify controller juju version updates
  package.json
  src/components/PrimaryNav/PrimaryNav.js
  src/components/PrimaryNav/PrimaryNav.test.tsx
  src/components/PrimaryNav/PrimaryNav.tsx
  src/components/PrimaryNav/_primary-nav.scss
  src/juju/api.ts
  src/pages/ControllersIndex/ControllersIndex.test.tsx
  src/pages/ControllersIndex/ControllersIndex.tsx
  src/pages/ControllersIndex/__snapshots__/ControllersIndex.test.tsx.snap
  src/store/juju/types.ts
  yarn.lock
Labels: Review: QA +1, Review: Code +1

#1416 WD-2610 - Improve the error boundary
  src/components/ErrorBoundary/ErrorBoundary.js
  src/components/ErrorBoundary/ErrorBoundary.test.tsx
  src/components/ErrorBoundary/ErrorBoundary.tsx
  src/components/ErrorBoundary/__snapshots__/ErrorBoundary.test.tsx.snap
Labels: Review: QA +1, Review: Code +1

#1420 Show dashboard notification update icon
  src/components/PrimaryNav/PrimaryNav.test.tsx
  src/components/PrimaryNav/PrimaryNav.tsx
  src/pages/ControllersIndex/ControllersIndex.test.tsx
Labels: Review: QA +1, Review: Code +1

#1425 WD-2640 - Fix resizing the header
  src/components/ButtonGroup/ButtonGroup.test.tsx
  src/components/ButtonGroup/ButtonGroup.tsx
  src/components/ButtonGroup/_button-group.scss
  src/pages/ModelsIndex/ModelsIndex.tsx
  src/pages/ModelsIndex/_models.scss
Labels: Review: QA +1, Review: Code +1

#1423 WD-2639 - Fix revoking permissions
  src/panels/ShareModelPanel/ShareModel.test.tsx
  src/panels/ShareModelPanel/ShareModel.tsx
Labels: Review: QA +1, Review: Code +1

#1422 WD-2612 - Add links to apps/units with errors
  src/components/ModelTableList/StatusGroup.test.tsx
  src/components/ModelTableList/StatusGroup.tsx
  src/scss/_utils.scss
  src/store/juju/utils/models.test.ts
  src/store/juju/utils/models.ts
Labels: Review: QA +1, Review: Code +1

#1426 WD-2663 - Fix lockup
  src/components/PrimaryNav/PrimaryNav.test.tsx
  src/components/PrimaryNav/PrimaryNav.tsx
Labels: Review: QA +1, Review: Code +1, Priority: Critical

#1427 WD-2669 - Fix breadcrumbs width
  src/components/Breadcrumb/Breadcrumb.tsx
  src/components/hooks.test.tsx
  src/components/hooks.ts
  src/pages/EntityDetails/EntityDetails.test.tsx
  src/pages/EntityDetails/EntityDetails.tsx
  src/pages/EntityDetails/_entity-details.scss
Labels: Review: QA +1, Review: Code +1

#1428 WD-2688 - Handle absolute controller API urls
  src/index.test.tsx
  src/index.tsx
Labels: Review: QA +1, Review: Code +1

#1430 WD-2691 - Use small Vanilla font size
  src/components/Button/Button.test.tsx
  src/components/Button/Button.tsx
  src/components/Button/_button.scss
  src/components/ConfirmationModal/_confirmation-modal.scss
  src/components/ModelTableList/_model-table-list.scss
  src/components/PrimaryNav/_primary-nav.scss
  src/components/RadioInputBox/_radio-input-box.scss
  src/components/ShareCard/_share-card.scss
  src/pages/Settings/settings.scss
  src/panels/ConfigPanel/_config-panel.scss
  src/panels/ShareModelPanel/share-model.scss
Labels: Review: Code +1

#1434 WD-2759 - Fix the size of the topology on mobile
  src/components/InfoPanel/_info-panel.scss
  src/components/Topology/Topology.tsx
Labels: Review: QA +1, Review: Code +1

#1432 WD-2736 - Scroll to config errors
  src/components/ScrollOnRender/ScrollOnRender.test.tsx
  src/components/ScrollOnRender/ScrollOnRender.tsx
  src/components/ScrollOnRender/index.ts
  src/components/SlidePanel/SlidePanel.js
  src/components/SlidePanel/SlidePanel.tsx
  src/hooks/useScrollOnRender.test.ts
  src/hooks/useScrollOnRender.ts
  src/pages/EntityDetails/EntityDetails.tsx
  src/panels/ConfigPanel/ConfigPanel.tsx
Labels: Review: QA +1, Review: Code +1

#1433 WD-2757- WebCLI history
  src/components/WebCLI/WebCLI.test.tsx
  src/components/WebCLI/WebCLI.tsx
Labels: Review: QA +1, Review: Code +1

#1437 WD-2808 - Prevent unnecessary topology rerenders
  src/components/Topology/Topology.tsx
Labels: Review: QA +1, Review: Code +1

#1438 WD-2831 - Refactor EntityDetails
  src/pages/EntityDetails/App/App.tsx
  src/pages/EntityDetails/EntityDetails.test.tsx
  src/pages/EntityDetails/EntityDetails.tsx
  src/pages/EntityDetails/Machine/Machine.tsx
  src/pages/EntityDetails/Model/Model.test.tsx
  src/pages/EntityDetails/Model/Model.tsx
  src/pages/EntityDetails/Unit/Unit.tsx
  src/pages/ModelDetails/ModelDetails.tsx
Labels: Review: QA +1, Review: Code +1

#1435 WD-2773 - Fix additional model access
  src/components/ModelTableList/CloudGroup.js
  src/components/ModelTableList/CloudGroup.test.tsx
  src/components/ModelTableList/OwnerGroup.js
  src/components/ModelTableList/OwnerGroup.test.tsx
  src/components/ModelTableList/StatusGroup.test.tsx
  src/components/ModelTableList/StatusGroup.tsx
  src/hooks/useActiveUser.tsx
  src/juju/api.ts
  src/pages/EntityDetails/Model/Model.test.tsx
  src/pages/EntityDetails/Model/Model.tsx
  src/panels/ShareModelPanel/ShareModel.test.tsx
  src/store/juju/reducers.test.ts
  src/store/juju/selectors.test.ts
  src/store/juju/selectors.ts
  src/store/juju/slice.ts
  src/store/juju/types.ts
  src/testing/factories/juju/juju.ts
Labels: Review: QA +1, Review: Code +1

#1443 WD-2910 - Display model access
  src/pages/EntityDetails/Model/Model.tsx
  src/store/general/selectors.test.ts
  src/store/general/selectors.ts
  src/store/juju/selectors.test.ts
  src/store/juju/selectors.ts
Labels: Review: QA +1, Review: Code +1

#1440 WD-2857 - Sticky entity details sidebar
  src/components/InfoPanel/_info-panel.scss
  src/components/ModelTableList/StatusGroup.tsx
  src/components/Topology/Topology.tsx
  src/layout/BaseLayout/_base-layout.scss
  src/pages/EntityDetails/Model/ActionLogs/ActionLogs.tsx
  src/pages/EntityDetails/Model/Model.tsx
  src/pages/EntityDetails/_entity-details.scss
  src/scss/_vanilla-overrides.scss
Labels: Review: QA +1, Review: Code +1

#1444 WD-2928 - Fix custom filters
  src/components/ModelTableList/CloudGroup.js
  src/components/ModelTableList/ModelTableList.test.tsx
  src/components/ModelTableList/OwnerGroup.js
  src/components/ModelTableList/StatusGroup.tsx
  src/components/ModelTableList/shared.test.tsx
  src/components/ModelTableList/shared.tsx
  src/store/juju/selectors.test.ts
  src/store/juju/selectors.ts
  src/store/juju/types.ts
  src/store/juju/utils/models.ts
  src/testing/factories/juju/juju.ts
Labels: Review: QA +1, Review: Code +1

#1442 WD-2883 - Replace use-query-params
  package.json
  src/components/App/App.js
  src/components/InfoPanel/InfoPanel.test.tsx
  src/components/ModelTableList/CloudGroup.js
  src/components/ModelTableList/CloudGroup.test.tsx
  src/components/ModelTableList/ModelTableList.test.tsx
  src/components/ModelTableList/OwnerGroup.js
  src/components/ModelTableList/OwnerGroup.test.tsx
  src/components/ModelTableList/StatusGroup.test.tsx
  src/components/ModelTableList/StatusGroup.tsx
  src/components/ModelTableList/shared.tsx
  src/components/PanelHeader/PanelHeader.test.tsx
  src/components/PanelHeader/PanelHeader.tsx
  src/components/hooks.test.tsx
  src/hooks/useModelStatus.ts
  src/hooks/useQueryParams.test.tsx
  src/hooks/useQueryParams.ts
  src/layout/BaseLayout/BaseLayout.test.tsx
  src/pages/ControllersIndex/ControllersIndex.test.tsx
  src/pages/ControllersIndex/ControllersIndex.tsx
  src/pages/EntityDetails/App/App.test.tsx
  src/pages/EntityDetails/App/App.tsx
  src/pages/EntityDetails/EntityDetails.test.tsx
  src/pages/EntityDetails/EntityDetails.tsx
  src/pages/EntityDetails/Model/ApplicationsTab/ApplicationsTab.test.tsx
  src/pages/EntityDetails/Model/ApplicationsTab/ApplicationsTab.tsx
  src/pages/EntityDetails/Model/Model.test.tsx
  src/pages/EntityDetails/Model/Model.tsx
  src/pages/ModelsIndex/ModelsIndex.test.tsx
  src/pages/ModelsIndex/ModelsIndex.tsx
  src/pages/PageNotFound/PageNotFound.test.tsx
  src/panels/ActionsPanel/ActionsPanel.test.tsx
  src/panels/ActionsPanel/ActionsPanel.tsx
  src/panels/ActionsPanel/CharmActionsPanel.tsx
  src/panels/CharmsPanel/ChamsPanel.tsx
  src/panels/CharmsPanel/CharmsPanel.test.tsx
  src/panels/ShareModelPanel/ShareModel.test.tsx
  src/panels/panels.test.tsx
  src/panels/panels.tsx
  yarn.lock
Labels: Review: QA +1, Review: Code +1

#1441 WD-2882 - Add URL definition
  src/components/Breadcrumb/Breadcrumb.tsx
  src/components/ModelTableList/StatusGroup.tsx
  src/components/ModelTableList/shared.tsx
  src/components/PrimaryNav/PrimaryNav.tsx
  src/components/Routes/Routes.tsx
  src/components/UserMenu/UserMenu.js
  src/hooks/useTableRowClick.tsx
  src/pages/ControllersIndex/ControllersIndex.tsx
  src/pages/EntityDetails/App/App.tsx
  src/pages/EntityDetails/EntityDetails.tsx
  src/pages/EntityDetails/Model/ActionLogs/ActionLogs.tsx
  src/pages/EntityDetails/Model/ApplicationsTab/ApplicationsTab.tsx
  src/pages/ModelDetails/ModelDetails.tsx
  src/pages/PageNotFound/PageNotFound.tsx
  src/panels/RegisterController/RegisterController.tsx
  src/urls.ts
  src/utils/argPath.test.ts
  src/utils/argPath.ts
  src/utils/index.ts
Labels: Review: QA +1, Review: Code +1
