Repository canonical/juju-dashboard, pull requests merged in 2023-02, with the labels that each got.

#1370 WD-1401 - Migrate panels to TypeScript
  src/pages/EntityDetails/Model/ActionLogs/ActionLogs.test.tsx
  src/panels/RegisterController/RegisterController.tsx
Labels: Review: Code +1

#1367 WD-1199 - Create app slice
  src/app/action-types.ts
  src/app/actions.js
  src/components/LogIn/LogIn.tsx
  src/components/UserMenu/UserMenu.js
  src/components/WebCLI/WebCLI.js
  src/components/WebCLI/WebCLI.test.tsx
  src/hooks/useLocalStorage.ts
  src/index.tsx
  src/juju/api.ts
  src/juju/bakery.ts
  src/juju/jimm-facade.ts
  src/panels/RegisterController/RegisterController.tsx
  src/panels/ShareModelPanel/ShareModel.tsx
  src/store/app/actions.test.ts
  src/store/app/actions.ts
  src/store/app/index.ts
  src/store/app/thunks.test.ts
  src/store/app/thunks.ts
  src/store/middleware/check-auth.js
  src/store/middleware/model-poller.test.ts
  src/store/middleware/model-poller.ts
  src/types.ts
Labels: Review: QA needed, Review: Code needed

#1374 WD-1470 - Replace test JSON with factories
  src/components/App/App.test.tsx
  src/components/Breadcrumb/Breadcrumb.test.tsx
  src/components/EntityInfo/EntityInfo.test.tsx
  src/components/PrimaryNav/PrimaryNav.test.tsx
  src/components/UserMenu/UserMenu.test.tsx
  src/components/WebCLI/WebCLI.test.tsx
  src/layout/BaseLayout/BaseLayout.test.tsx
  src/pages/PageNotFound/PageNotFound.test.tsx
  src/panels/ConfigPanel/ConfigPanel.test.tsx
  src/panels/panels.test.tsx
  src/types.ts
Labels: Review: Code +1

#1375 WD-1484 - Migrate page components to TypeScript
  src/app/selectors.js
  src/components/ChipGroup/ChipGroup.tsx
  src/layout/BaseLayout/BaseLayout.tsx
  src/pages/ControllersIndex/ControllerChart/ControllerChart.tsx
  src/pages/ControllersIndex/ControllerOverview/ControllerOverview.tsx
  src/pages/ControllersIndex/ControllersIndex.tsx
  src/pages/EntityDetails/App/App.tsx
  src/pages/EntityDetails/EntityDetails.tsx
  src/pages/ModelsIndex/ModelsIndex.tsx
  src/pages/Settings/Settings.tsx
  src/store/middleware/model-poller.test.ts
  src/types.ts
Labels: Review: Code +1

#1285 Truncate long usernames in the access panel.
  Dockerfile
  renovate.json
  src/components/ShareCard/ShareCard.test.tsx
  src/components/ShareCard/ShareCard.tsx
  src/components/ShareCard/_share-card.scss
  src/components/ToastCard/_toast-card.scss
  src/pages/EntityDetails/App/App.tsx
  src/pages/EntityDetails/counts.ts
  src/scss/_vanilla-overrides.scss
  src/scss/index.scss
  src/tables/tableRows.tsx
Labels: Review: QA +1, Review: Code +1

#1366 WD-1180 - Create Juju slice
  src/app/selectors.js
  src/components/InfoPanel/InfoPanel.tsx
  src/hooks/useModelAttributes.ts
  src/juju/action-types.ts
  src/juju/actions.js
  src/juju/actions.test.js
  src/juju/api.ts
  src/juju/reducer.js
  src/juju/types.ts
  src/juju/watchers.ts
  src/pages/ControllersIndex/ControllerOverview/ControllerOverview.tsx
  src/pages/ControllersIndex/ControllersIndex.tsx
  src/pages/EntityDetails/App/App.test.tsx
  src/pages/EntityDetails/App/App.tsx
  src/pages/EntityDetails/EntityDetails.tsx
  src/pages/EntityDetails/Machine/Machine.tsx
  src/pages/EntityDetails/Model/Model.test.tsx
  src/pages/EntityDetails/Model/Model.tsx
  src/pages/EntityDetails/Unit/Unit.tsx
  src/pages/ModelDetails/ModelDetails.tsx
  src/pages/ModelsIndex/ModelsIndex.tsx
  src/store/app/thunks.test.ts
  src/store/app/thunks.ts
  src/store/juju/actions.test.ts
  src/store/juju/index.ts
  src/store/juju/reducers.test.ts
  src/store/juju/selectors.test.ts
  src/store/juju/selectors.ts
  src/store/juju/slice.ts
  src/store/juju/thunks.test.ts
  src/store/juju/thunks.ts
  src/store/juju/types.ts
  src/store/middleware/check-auth.ts
  src/store/middleware/model-poller.test.ts
  src/store/middleware/model-poller.ts
  src/store/store.ts
  src/tables/tableRows.tsx
  src/testing/factories/juju/juju.ts
  src/types.ts
Labels: Review: Code +1

#1279 replace p-radio with RadioInput from react-components
  index.html
  src/components/RadioInputBox/_radio-input-box.scss
  src/components/ShareCard/ShareCard.test.tsx
  src/components/ShareCard/ShareCard.tsx
  src/components/ShareCard/_share-card.scss
  src/panels/ConfigPanel/BooleanConfig.tsx
  src/panels/ConfigPanel/_config-panel.scss
  src/panels/ShareModelPanel/ShareModel.tsx
  src/panels/ShareModelPanel/share-model.scss
  src/scss/_settings.scss
Labels: Review: QA +1, Review: Code +1

#1376 Upgrade jujulib
  package.json
  src/juju/api.ts
  src/pages/ModelDetails/ModelDetails.tsx
  src/store/general/reducers.test.ts
  src/store/general/selectors.test.ts
  src/store/general/selectors.ts
  src/store/general/types.ts
  src/store/juju/types.ts
  src/store/middleware/model-poller.ts
  yarn.lock
Labels: Review: QA +1, Review: Code +1

#1368 WD-1230 - Split app utils and selectors
  src/app/selectors.js
  src/components/InfoPanel/InfoPanel.tsx
  src/components/ModelTableList/CloudGroup.js
  src/components/ModelTableList/ModelTableList.test.tsx
  src/components/ModelTableList/OwnerGroup.js
  src/components/ModelTableList/StatusGroup.js
  src/components/ModelTableList/shared.js
  src/components/PrimaryNav/PrimaryNav.js
  src/components/ShareCard/ShareCard.tsx
  src/components/Topology/Topology.js
  src/components/UserMenu/UserMenu.js
  src/components/utils.test.tsx
  src/components/utils.tsx
  src/hooks/useModelAttributes.ts
  src/hooks/useModelStatus.ts
  src/juju/api.ts
  src/juju/types.ts
  src/layout/BaseLayout/BaseLayout.tsx
  src/pages/ControllersIndex/ControllerChart/ControllerChart.tsx
  src/pages/ControllersIndex/ControllerOverview/ControllerOverview.tsx
  src/pages/EntityDetails/App/App.tsx
  src/pages/EntityDetails/EntityDetails.tsx
  src/pages/EntityDetails/Machine/Machine.tsx
  src/pages/EntityDetails/Model/ActionLogs/ActionLogs.tsx
  src/pages/EntityDetails/Model/Model.tsx
  src/pages/EntityDetails/Unit/Unit.tsx
  src/pages/ModelDetails/ModelDetails.tsx
  src/pages/ModelsIndex/ModelsIndex.tsx
  src/panels/ActionsPanel/ActionsPanel.tsx
  src/panels/ConfigPanel/BooleanConfig.tsx
  src/panels/ConfigPanel/ConfigPanel.tsx
  src/panels/ConfigPanel/TextAreaConfig.tsx
  src/panels/OffersPanel/OffersPanel.tsx
  src/panels/RemoteAppsPanel/RemoteAppsPanel.tsx
  src/panels/ShareModelPanel/ShareModel.tsx
  src/store/juju/reducers.test.ts
  src/store/juju/selectors.test.ts
  src/store/juju/selectors.ts
  src/store/juju/slice.ts
  src/store/juju/types.ts
  src/store/juju/utils/models.test.ts
  src/store/juju/utils/models.ts
  src/tables/tableRows.tsx
  src/testing/complete-redux-store-dump.js
Labels: Review: QA +1, Review: Code +1

#1379 WD-2030 - Replace controller test data with factories
  src/components/ModelTableList/CloudGroup.test.tsx
  src/components/ModelTableList/ModelTableList.test.tsx
  src/components/ModelTableList/OwnerGroup.test.tsx
  src/components/ModelTableList/StatusGroup.test.tsx
  src/components/PrimaryNav/PrimaryNav.test.tsx
  src/pages/ControllersIndex/ControllersIndex.test.tsx
  src/pages/ControllersIndex/__snapshots__/ControllersIndex.test.tsx.snap
  src/pages/ModelsIndex/ModelsIndex.test.tsx
  src/store/app/thunks.test.ts
  src/store/juju/reducers.test.ts
  src/store/juju/thunks.test.ts
  src/store/middleware/model-poller.test.ts
  src/testing/complete-redux-store-dump.js
  src/testing/factories/juju/juju.ts
Labels: Review: Code +1

#1380 WD-2042 - Create model info factory
  src/components/ModelTableList/CloudGroup.test.tsx
  src/components/ModelTableList/OwnerGroup.test.tsx
  src/components/ModelTableList/StatusGroup.test.tsx
  src/pages/ControllersIndex/ControllersIndex.test.tsx
  src/store/juju/reducers.test.ts
  src/store/juju/selectors.test.ts
  src/testing/complete-redux-store-dump.js
  src/testing/factories/juju/juju.ts
Labels: Review: Code +1

#1382 WD-2043 - Add model watcher factories
  src/components/InfoPanel/InfoPanel.test.tsx
  src/juju/types.ts
  src/pages/EntityDetails/App/App.test.tsx
  src/pages/EntityDetails/Model/Model.test.tsx
  src/store/juju/reducers.test.ts
  src/store/juju/selectors.test.ts
  src/testing/factories/index.ts
  src/testing/factories/juju/juju.ts
  src/testing/factories/juju/model-watcher.ts
Labels: Review: Code +1

#1383 WD-1200 - Add factories for model data
  src/testing/factories/juju/juju.ts
Labels: Review: Code +1

#1384 WD-1201 - Replace juju data with factories
  .prettierignore
  src/components/InfoPanel/InfoPanel.test.tsx
  src/components/ModelTableList/CloudGroup.test.tsx
  src/components/ModelTableList/ModelTableList.test.tsx
  src/components/ModelTableList/OwnerGroup.test.tsx
  src/components/ModelTableList/StatusGroup.test.tsx
  src/components/PrimaryNav/PrimaryNav.test.tsx
  src/pages/ControllersIndex/ControllersIndex.test.tsx
  src/pages/EntityDetails/App/App.test.tsx
  src/pages/EntityDetails/EntityDetails.test.tsx
  src/pages/EntityDetails/Model/ActionLogs/ActionLogs.test.tsx
  src/pages/EntityDetails/Model/Model.test.tsx
  src/pages/ModelsIndex/ModelsIndex.test.tsx
  src/panels/ActionsPanel/ActionsPanel.test.tsx
  src/panels/ShareModelPanel/ShareModel.test.tsx
  src/store/app/thunks.test.ts
  src/store/juju/reducers.test.ts
  src/store/juju/selectors.test.ts
  src/store/juju/thunks.test.ts
  src/store/juju/types.ts
  src/store/middleware/model-poller.test.ts
  src/testing/complete-redux-store-dump.js
  src/testing/factories/juju/juju.ts
Labels: Review: Code +1

#1385 WD-2115 - Test factories cleanup
  src/components/ChipGroup/ChipGroup.tsx
  src/components/utils.tsx
  src/juju/api.ts
  src/pages/EntityDetails/counts.ts
  src/pages/ModelDetails/ModelDetails.tsx
  src/panels/ActionsPanel/ActionsPanel.tsx
  src/store/middleware/model-poller.ts
  src/store/store.ts
  src/tables/tableRows.tsx
Labels: Review: Code +1

#1378 WD-1958 - Applications search
  package.json
  src/components/ChipGroup/ChipGroup.tsx
  src/components/SearchBox/SearchBox.tsx
  src/juju/api.ts
  src/pages/EntityDetails/EntityDetails.test.tsx
  src/pages/EntityDetails/EntityDetails.tsx
  src/pages/EntityDetails/Model/ApplicationsTab/ApplicationsTab.test.tsx
  src/pages/EntityDetails/Model/ApplicationsTab/ApplicationsTab.tsx
  src/pages/EntityDetails/Model/ApplicationsTab/useTableSelect.tsx
  src/pages/EntityDetails/Model/Model.test.tsx
  src/pages/EntityDetails/Model/Model.tsx
  src/pages/EntityDetails/_entity-details.scss
  src/pages/EntityDetails/counts.ts
  src/panels/ActionsPanel/ActionsPanel.tsx
  src/panels/ActionsPanel/CharmActionsPanel.tsx
  src/panels/CharmsPanel/ChamsPanel.tsx
  src/panels/CharmsPanel/CharmsPanel.test.tsx
  src/panels/CharmsPanel/_charms-panel.scss
  src/panels/ConfigPanel/ConfigPanel.test.tsx
  src/panels/panels.tsx
  src/store/juju/reducers.test.ts
  src/store/juju/selectors.ts
  src/store/juju/slice.ts
  src/store/juju/types.ts
  src/store/middleware/check-auth.ts
  src/tables/tableHeaders.tsx
  src/testing/factories/juju/ApplicationV15.ts
  src/testing/factories/juju/Charms.ts
  src/testing/factories/juju/juju.ts
  yarn.lock
Labels: Review: QA +1, Review: Code +1

#1387 Fix logout
  src/components/LogIn/LogIn.test.tsx
  src/components/LogIn/LogIn.tsx
  src/store/app/thunks.test.ts
  src/store/app/thunks.ts
  src/store/general/actions.test.ts
  src/store/general/reducers.test.ts
  src/store/general/slice.ts
  src/store/middleware/check-auth.ts
Labels: Review: QA +1, Review: Code +1

#1388 Missing/empty models
  src/pages/EntityDetails/EntityDetails.test.tsx
  src/pages/EntityDetails/EntityDetails.tsx
  src/pages/ModelsIndex/ModelsIndex.test.tsx
  src/pages/ModelsIndex/ModelsIndex.tsx
  src/store/juju/reducers.test.ts
  src/store/juju/selectors.test.ts
  src/store/juju/selectors.ts
  src/store/juju/slice.ts
  src/store/juju/types.ts
  src/store/middleware/model-poller.ts
  src/testing/factories/juju/juju.ts
Labels: Review: QA +1, Review: Code +1
