Repository canonical/juju-dashboard, pull requests merged in 2023-07, with the labels that each got.

#1512 WD-5004 - fix: Broken docs links
  CONTRIBUTING.md
  HACKING.md
  README.md
  RELEASING.md
Labels: Review: QA +1, Review: Code +1 (with changes)

#1514 WD-5018 - fix: CLI docs link
  src/components/ErrorBoundary/ErrorBoundary.tsx
  src/components/PrimaryNav/PrimaryNav.tsx
  src/components/WebCLI/WebCLI.tsx
  src/components/WebCLI/__snapshots__/WebCLI.test.tsx.snap
  src/urls.ts
Labels: Review: QA +1, Review: Code +1 (with changes)

#1520 WD-5039 - fix: Short panels don't stretch
  src/panels/ConfigPanel/_config-panel.scss
Labels: Review: QA +1, Review: Code +1

#1524 WD-5050 - fix: Clicking outside action confirmation has error
  src/panels/ActionsPanel/ActionsPanel.tsx
  src/panels/ActionsPanel/CharmActionsPanel.tsx
  src/panels/ConfigPanel/ConfigPanel.tsx
Labels: Review: QA +1, Review: Code +1

#1509 Remove AdditionalProperties types
  src/components/RelationIcon/RelationIcon.tsx
  src/juju/api.ts
  src/juju/types.ts
  src/juju/watchers.ts
  src/pages/EntityDetails/Model/ActionLogs/ActionLogs.tsx
  src/store/juju/selectors.ts
  src/store/middleware/model-poller.ts
  src/testing/factories/juju/ActionV7.ts
  src/testing/factories/juju/Application.ts
  src/testing/factories/juju/model-watcher.ts
  src/types.ts
Labels: Review: QA +1, Review: Code +1

#1528 WD-5038 - fix: Closing panels clears all query params (new solution)
  src/components/Panel/Panel.test.tsx
  src/components/Panel/Panel.tsx
  src/components/PanelHeader/PanelHeader.test.tsx
  src/components/PanelHeader/PanelHeader.tsx
  src/hooks/useQueryParams.ts
  src/panels/ActionsPanel/ActionsPanel.tsx
  src/panels/ActionsPanel/CharmActionsPanel.tsx
  src/panels/CharmsPanel/CharmsPanel.tsx
  src/panels/ConfigPanel/ConfigPanel.tsx
  src/panels/RegisterController/RegisterController.tsx
  src/panels/ShareModelPanel/ShareModel.tsx
  src/panels/hooks.test.tsx
  src/panels/hooks.ts
  src/panels/utils.test.tsx
  src/panels/utils.tsx
Labels: Review: QA +1, Review: Code +1

#1535 Rename Logs tab
  src/components/ButtonGroup/ButtonGroup.tsx
  src/components/ButtonGroup/_button-group.scss
  src/pages/EntityDetails/App/App.test.tsx
  src/pages/EntityDetails/App/App.tsx
  src/pages/EntityDetails/EntityDetails.test.tsx
  src/pages/EntityDetails/EntityDetails.tsx
  src/pages/EntityDetails/Model/Logs/ActionLogs/ActionLogs.test.tsx
  src/pages/EntityDetails/Model/Logs/ActionLogs/ActionLogs.tsx
  src/pages/EntityDetails/Model/Logs/ActionLogs/_action-logs.scss
  src/pages/EntityDetails/Model/Logs/ActionLogs/index.ts
  src/pages/EntityDetails/Model/Logs/Logs.test.tsx
  src/pages/EntityDetails/Model/Logs/Logs.tsx
  src/pages/EntityDetails/Model/Logs/_logs.scss
  src/pages/EntityDetails/Model/Logs/index.ts
  src/pages/EntityDetails/Model/Model.tsx
  src/pages/EntityDetails/_entity-details.scss
  src/pages/ModelsIndex/ModelsIndex.test.tsx
  src/pages/ModelsIndex/ModelsIndex.tsx
Labels: Review: QA +1, Review: Code +1

#1530 WD-5130 - Fix demo proxy settings
  Dockerfile
Labels: Review: QA +1, Review: Code +1

#1468 WD-2833 - Sort action logs
  package.json
  src/pages/EntityDetails/Model/Logs/ActionLogs/ActionLogs.test.tsx
  src/pages/EntityDetails/Model/Logs/ActionLogs/ActionLogs.tsx
  src/pages/EntityDetails/Model/Logs/ActionLogs/_action-logs.scss
  yarn.lock
Labels: Review: QA +1, Review: Code +1

#1540 WD-5227 - Add fake audit log data
  .github/workflows/actions.yml
  src/pages/Logs/audit-logs-fake-data.ts
Labels: Review: Code +1

#1531 WD-5134 - feat: Skip charm selection if only one charm is available
  src/juju/api.test.ts
  src/juju/api.ts
  src/pages/EntityDetails/Model/ApplicationsTab/ApplicationsTab.test.tsx
  src/pages/EntityDetails/Model/ApplicationsTab/ApplicationsTab.tsx
  src/panels/ActionsPanel/CharmActionsPanel.test.tsx
  src/panels/ActionsPanel/CharmActionsPanel.tsx
  src/panels/CharmsAndActionsPanel/CharmActionsPanelTitle/CharmActionsPanelTitle.test.tsx
  src/panels/CharmsAndActionsPanel/CharmActionsPanelTitle/CharmActionsPanelTitle.tsx
  src/panels/CharmsAndActionsPanel/CharmActionsPanelTitle/index.ts
  src/panels/CharmsAndActionsPanel/CharmsAndActionsPanel.test.tsx
  src/panels/CharmsAndActionsPanel/CharmsAndActionsPanel.tsx
  src/panels/CharmsAndActionsPanel/index.ts
  src/panels/CharmsPanel/CharmsPanel.test.tsx
  src/panels/CharmsPanel/CharmsPanel.tsx
  src/panels/Panels.test.tsx
  src/panels/Panels.tsx
Labels: Review: QA +1, Review: Code +1 (with changes)

#1542 WD-5283 - Change ButtonGroup to Vanilla Segmented Controls
  src/components/ButtonGroup/ButtonGroup.test.tsx
  src/components/ButtonGroup/ButtonGroup.tsx
  src/components/ButtonGroup/_button-group.scss
  src/components/SegmentedControl/SegmentedControl.test.tsx
  src/components/SegmentedControl/SegmentedControl.tsx
  src/components/SegmentedControl/index.ts
  src/pages/EntityDetails/App/App.test.tsx
  src/pages/EntityDetails/App/App.tsx
  src/pages/EntityDetails/Model/Logs/Logs.test.tsx
  src/pages/EntityDetails/Model/Logs/Logs.tsx
  src/pages/ModelsIndex/ModelsIndex.test.tsx
  src/pages/ModelsIndex/ModelsIndex.tsx
  src/pages/ModelsIndex/_models.scss
Labels: Review: QA +1, Review: Code +1

#1527 WD-5051 - Split application tab sub components
  src/pages/EntityDetails/EntityDetails.test.tsx
  src/pages/EntityDetails/EntityDetails.tsx
  src/pages/EntityDetails/Model/ApplicationsTab/ApplicationsTab.test.tsx
  src/pages/EntityDetails/Model/ApplicationsTab/ApplicationsTab.tsx
  src/pages/EntityDetails/Model/ApplicationsTab/LocalAppsTable/AppSearchBox/AppSearchBox.test.tsx
  src/pages/EntityDetails/Model/ApplicationsTab/LocalAppsTable/AppSearchBox/AppSearchBox.tsx
  src/pages/EntityDetails/Model/ApplicationsTab/LocalAppsTable/AppSearchBox/index.ts
  src/pages/EntityDetails/Model/ApplicationsTab/LocalAppsTable/LocalAppsTable.test.tsx
  src/pages/EntityDetails/Model/ApplicationsTab/LocalAppsTable/LocalAppsTable.tsx
  src/pages/EntityDetails/Model/ApplicationsTab/LocalAppsTable/index.ts
  src/pages/EntityDetails/Model/ApplicationsTab/LocalAppsTable/useTableSelect.tsx
  src/pages/EntityDetails/Model/ApplicationsTab/SearchResults/SearchResults.test.tsx
  src/pages/EntityDetails/Model/ApplicationsTab/SearchResults/SearchResults.tsx
  src/pages/EntityDetails/Model/ApplicationsTab/SearchResults/index.ts
  src/pages/EntityDetails/Model/Model.tsx
Labels: Review: QA +1, Review: Code +1

#1541 WD-5214 - feat: Add logs table to model logs view
  src/components/AuditLogsTable/AuditLogsTable.test.tsx
  src/components/AuditLogsTable/AuditLogsTable.tsx
  src/components/AuditLogsTable/index.ts
  src/components/ModelTableList/ModelDetailsLink/ModelDetailsLink.tsx
  src/components/ModelTableList/StatusGroup.tsx
  src/components/WebCLI/WebCLI.tsx
  src/components/utils.tsx
  src/pages/EntityDetails/Model/Logs/AuditLogs/AuditLogs.test.tsx
  src/pages/EntityDetails/Model/Logs/AuditLogs/AuditLogs.tsx
  src/pages/EntityDetails/Model/Logs/Logs.test.tsx
  src/pages/EntityDetails/Model/Model.test.tsx
  src/panels/ShareModelPanel/ShareModel.tsx
  src/store/juju/selectors.ts
  src/store/juju/utils/models.ts
  src/utils/getUserName.test.ts
  src/utils/getUserName.ts
Labels: Review: QA +1, Review: Code +1 (with changes)

#1545 WD-5215 - feat: Hide model column from table in model logs view
  src/components/AuditLogsTable/AuditLogsTable.test.tsx
  src/components/AuditLogsTable/AuditLogsTable.tsx
  src/pages/EntityDetails/Model/ApplicationsTab/ApplicationsTab.test.tsx
Labels: Review: QA +1, Review: Code +1
