Repository canonical/juju-dashboard, pull requests merged in 2023-12, with the labels that each got.

#1669 WD-7504 - Make local apps table responsive
  src/pages/EntityDetails/_entity-details.scss
  src/scss/custom/_status_icons.scss
  src/tables/tableRows.tsx
Labels: Review: QA +1, Review: Code +1 (with changes)

#1671 WD-7715 - feat: Remove Settings page; WD-7716 - feat: Add analyticsEnabled config option
  public/config.js
  public/config.js.go
  src/components/App/App.test.tsx
  src/components/App/App.tsx
  src/components/Routes/Routes.tsx
  src/components/UserMenu/UserMenu.tsx
  src/hooks/useAnalytics.test.ts
  src/hooks/useAnalytics.tsx
  src/pages/PageNotFound/PageNotFound.tsx
  src/pages/Settings/Settings.test.tsx
  src/pages/Settings/Settings.tsx
  src/pages/Settings/settings.scss
  src/store/general/selectors.test.ts
  src/store/general/selectors.ts
  src/store/general/types.ts
  src/testing/factories/general.ts
  src/urls.ts
Labels: Review: QA +1, Review: Code +1

#1670 WD-7502 - Make cross model tables responsive
  src/pages/EntityDetails/_entity-details.scss
Labels: Review: QA +1, Review: Code +1

#1673 WD-7767 - feat: Enable Sentry only if analyticsEnabled is true
  src/components/ErrorBoundary/ErrorBoundary.tsx
  src/index.tsx
  src/store/middleware/model-poller.ts
Labels: Review: Code +1
