Repository canonical/juju-dashboard, pull requests merged in 2023-09, with the labels that each got.

#1607 Tag to username util
  src/components/ModelTableList/ModelDetailsLink/ModelDetailsLink.tsx
  src/components/ModelTableList/StatusGroup.tsx
  src/components/WebCLI/WebCLI.tsx
  src/panels/ShareModelPanel/ShareModel.tsx
  src/store/juju/selectors.ts
  src/store/juju/utils/models.ts
  src/utils/getUserName.test.ts
  src/utils/getUserName.ts
Labels: Review: Code +1

#1608 Merge branch 'main' into cross-model-queries
  src/components/ModelTableList/StatusGroup.tsx
  src/components/WebCLI/WebCLI.tsx
  src/panels/ShareModelPanel/ShareModel.tsx
  src/store/juju/selectors.ts
  src/store/juju/utils/models.ts
  src/utils/getUserName.test.ts
  src/utils/getUserName.ts
Labels: Review: Code needed

#1603 WD-6051 - Scroll the history menu
  src/pages/AdvancedSearch/CodeSnippetBlock/CodeSnippetBlock.tsx
  src/pages/AdvancedSearch/SearchForm/SearchHistoryMenu/SearchHistoryMenu.tsx
Labels: Review: QA +1, Review: Code +1

#1605 WD-6094 - Display JIMM errors
  src/store/middleware/model-poller.test.ts
  src/store/middleware/model-poller.ts
Labels: Review: QA +1, Review: Code +1

#1604 Versioned JIMM facades
  src/juju/api.ts
  src/juju/jimm/JIMMV3.test.ts
  src/juju/jimm/JIMMV3.ts
  src/juju/jimm/index.ts
  src/juju/types.ts
Labels: Review: QA +1, Review: Code +1

#1606 Add JIMM v4 class
  src/juju/api.ts
  src/juju/jimm/JIMMV3.test.ts
  src/juju/jimm/JIMMV3.ts
  src/juju/jimm/JIMMV4.test.ts
  src/juju/jimm/JIMMV4.ts
  src/juju/jimm/index.ts
  src/juju/types.ts
  src/pages/AdvancedSearch/CodeSnippetBlock/CodeSnippetBlock.tsx
  src/pages/AdvancedSearch/ErrorsBlock/ErrorsBlock.tsx
  src/store/juju/slice.ts
  src/store/juju/types.ts
  src/store/middleware/model-poller.ts
Labels: Review: QA +1, Review: Code +1

#1600 WD-5822 - feat: Map unit-key tree data to links
  src/components/AppLink/AppLink.test.tsx
  src/components/AppLink/AppLink.tsx
  src/components/AppLink/index.js
  src/components/MachineLink/MachineLink.test.tsx
  src/components/MachineLink/MachineLink.tsx
  src/components/MachineLink/index.ts
  src/components/ModelDetailsLink/ModelDetailsLink.tsx
  src/components/UnitLink/UnitLink.test.tsx
  src/components/UnitLink/UnitLink.tsx
  src/components/UnitLink/index.ts
  src/components/hooks.ts
  src/pages/AdvancedSearch/CodeSnippetBlock/CodeSnippetBlock.test.tsx
  src/pages/AdvancedSearch/CodeSnippetBlock/CodeSnippetBlock.tsx
  src/pages/AdvancedSearch/ResultsBlock/ResultsBlock.test.tsx
  src/testing/factories/juju/jimm.ts
Labels: Review: QA +1, Review: Code +1 (with changes)

#1613 WD-5786 - Sort by most recent first
  src/components/AuditLogsTable/hooks.ts
  src/juju/jimm/JIMMV3.ts
Labels: Review: QA +1, Review: Code +1

#1615 WD-6180 - Fix topology position
  src/components/Topology/Topology.test.tsx
  src/components/Topology/Topology.tsx
Labels: Review: QA +1, Review: Code +1

#1614 WD-6179 - Disable username/password instead of help text
  src/panels/RegisterController/RegisterController.test.tsx
  src/panels/RegisterController/RegisterController.tsx
Labels: Review: QA +1, Review: Code +1

#1628 WD-6249 - feat: Disable charm radio input when no action is available
  src/panels/CharmsAndActionsPanel/CharmsAndActionsPanel.test.tsx
  src/panels/CharmsPanel/CharmsPanel.test.tsx
  src/panels/CharmsPanel/CharmsPanel.tsx
Labels: Review: QA +1, Review: Code +1 (with changes)

#1618 WD-6216 - refactor: Use ConfirmationModal from react-components
  src/components/Aside/_aside.scss
  src/components/ConfirmationModal/ConfirmationModal.test.tsx
  src/components/ConfirmationModal/ConfirmationModal.tsx
  src/components/ConfirmationModal/_confirmation-modal.scss
  src/panels/ActionsPanel/ActionsPanel.test.tsx
  src/panels/ActionsPanel/ActionsPanel.tsx
  src/panels/ActionsPanel/CharmActionsPanel.test.tsx
  src/panels/ActionsPanel/CharmActionsPanel.tsx
  src/panels/ConfigPanel/ConfigPanel.test.tsx
  src/panels/ConfigPanel/ConfigPanel.tsx
  src/panels/ConfigPanel/_config-panel.scss
  src/panels/types.ts
  src/scss/_breakpoints.scss
  src/scss/_vanilla-overrides.scss
Labels: Review: QA +1, Review: Code +1 (with changes)

#1612 WD-6219 - Enable cross model search with JIMM v4
  src/components/PrimaryNav/PrimaryNav.test.tsx
  src/components/PrimaryNav/PrimaryNav.tsx
  src/components/Routes/Routes.tsx
  src/pages/AdvancedSearch/AdvancedSearch.test.tsx
  src/store/general/actions.test.ts
  src/store/general/reducers.test.ts
  src/store/general/selectors.test.ts
  src/store/general/selectors.ts
  src/store/general/slice.ts
  src/store/general/types.ts
  src/store/middleware/model-poller.test.ts
  src/store/middleware/model-poller.ts
  src/testing/factories/general.ts
Labels: Review: QA +1, Review: Code +1

#1629 WD-6258 - Hide controls on read only models
  src/components/ModelTableList/CloudGroup.tsx
  src/components/ModelTableList/OwnerGroup.tsx
  src/components/ModelTableList/StatusGroup.tsx
  src/hooks/useCanConfigureModel.test.tsx
  src/hooks/useCanConfigureModel.ts
  src/pages/EntityDetails/App/App.test.tsx
  src/pages/EntityDetails/App/App.tsx
  src/pages/EntityDetails/Model/ApplicationsTab/LocalAppsTable/LocalAppsTable.test.tsx
  src/pages/EntityDetails/Model/ApplicationsTab/LocalAppsTable/LocalAppsTable.tsx
  src/pages/EntityDetails/Model/Model.tsx
  src/store/juju/utils/models.test.ts
  src/store/juju/utils/models.ts
  src/tables/tableHeaders.tsx
Labels: Review: QA +1, Review: Code +1

#1617 WD-6200 - reduce full status calls for Juju 3.2
  src/juju/types.ts
  src/juju/watchers.ts
  src/pages/EntityDetails/EntityDetails.tsx
  src/pages/EntityDetails/Model/Model.tsx
  src/pages/ModelDetails/ModelDetails.test.tsx
  src/pages/ModelDetails/ModelDetails.tsx
  src/store/juju/reducers.test.ts
  src/store/juju/slice.ts
  src/testing/factories/juju/model-watcher.ts
  src/utils/getMajorMinorVersion.test.ts
  src/utils/getMajorMinorVersion.ts
  src/utils/index.ts
Labels: Review: QA +1, Review: Code +1

#1631 WD-6271 - feat: Display names of apps when displaying charms in actions panel
  src/components/ModelDetailsLink/ModelDetailsLink.tsx
  src/components/ModelTableList/StatusGroup.tsx
  src/components/WebCLI/WebCLI.tsx
  src/panels/CharmsPanel/CharmApplicationsDetails/CharmApplicationsDetails.test.tsx
  src/panels/CharmsPanel/CharmApplicationsDetails/CharmApplicationsDetails.tsx
  src/panels/CharmsPanel/CharmApplicationsDetails/index.ts
  src/panels/CharmsPanel/CharmsPanel.test.tsx
  src/panels/CharmsPanel/CharmsPanel.tsx
  src/panels/ShareModelPanel/ShareModel.tsx
  src/scss/_utils.scss
  src/store/juju/selectors.ts
  src/store/juju/utils/models.ts
  src/utils/breakLines.test.ts
  src/utils/breakLines.ts
  src/utils/getUserName.test.ts
  src/utils/index.ts
Labels: Review: QA +1, Review: Code +1 (with changes)

#1638 WD-6278 - Fix additional JIMM controllers
  src/components/AuthenticationButton/AuthenticationButton.test.tsx
  src/components/AuthenticationButton/AuthenticationButton.tsx
  src/components/AuthenticationButton/index.ts
  src/components/LogIn/LogIn.test.tsx
  src/components/LogIn/LogIn.tsx
  src/components/ModelTableList/ModelTableList.test.tsx
  src/components/ModelTableList/shared.test.tsx
  src/components/ModelTableList/shared.tsx
  src/components/PrimaryNav/PrimaryNav.test.tsx
  src/components/PrimaryNav/PrimaryNav.tsx
  src/components/ToastCard/ToastCard.test.tsx
  src/components/ToastCard/ToastCard.tsx
  src/components/ToastCard/_toast-card.scss
  src/juju/api.test.ts
  src/juju/api.ts
  src/juju/jimm/JIMMV3.ts
  src/pages/ControllersIndex/ControllersIndex.test.tsx
  src/pages/ControllersIndex/ControllersIndex.tsx
  src/panels/ActionsPanel/CharmActionsPanel.tsx
  src/panels/ShareModelPanel/ShareModel.test.tsx
  src/panels/ShareModelPanel/ShareModel.tsx
  src/scss/custom/_status_icons.scss
  src/scss/index.scss
  src/store/general/reducers.test.ts
  src/store/general/selectors.test.ts
  src/store/general/selectors.ts
  src/store/general/slice.ts
  src/store/general/types.ts
  src/store/juju/selectors.test.ts
  src/store/juju/types.ts
  src/store/juju/utils/controllers.test.ts
  src/store/juju/utils/controllers.ts
  src/store/middleware/check-auth.ts
  src/store/middleware/model-poller.test.ts
  src/store/middleware/model-poller.ts
  src/testing/factories/general.ts
  src/testing/factories/juju/juju.ts
Labels: Review: QA +1, Review: Code +1

#1640 WD-6424 - feat: Handle model connection timeout
  src/pages/EntityDetails/EntityDetails.test.tsx
  src/pages/EntityDetails/EntityDetails.tsx
  src/pages/ModelDetails/ModelDetails.test.tsx
  src/pages/ModelDetails/ModelDetails.tsx
Labels: Review: QA +1, Review: Code +1 (with changes)
