Repository canonical/juju-dashboard, pull requests merged in 2023-08, with the labels that each got.

#1549 Add audit logs jimm api
  src/juju/api.test.ts
  src/juju/api.ts
  src/juju/jimm-facade.test.ts
  src/juju/jimm-facade.ts
  src/juju/types.ts
  src/pages/Logs/audit-logs-fake-data.ts
  src/store/juju/actions.test.ts
  src/store/juju/slice.ts
  src/store/middleware/model-poller.test.ts
  src/store/middleware/model-poller.ts
  src/testing/factories/juju/jimm.ts
Labels: Review: Code +1

#1548 WD-5216 - feat: Hide audit log views when not using JAAS
  src/components/LogIn/LogIn.tsx
  src/components/Logo/Logo.tsx
  src/components/PrimaryNav/PrimaryNav.test.tsx
  src/components/PrimaryNav/PrimaryNav.tsx
  src/components/Routes/Routes.tsx
  src/pages/EntityDetails/EntityDetails.test.tsx
  src/pages/EntityDetails/EntityDetails.tsx
  src/pages/EntityDetails/Model/Logs/Logs.test.tsx
  src/pages/EntityDetails/Model/Logs/Logs.tsx
  src/store/general/selectors.test.ts
  src/store/general/selectors.ts
Labels: Review: QA +1, Review: Code +1

#1547 WD-5211 - feat: Add Logs table to top level Logs page
  src/components/AuditLogsTable/AuditLogsTable.test.tsx
  src/layout/BaseLayout/_base-layout.scss
  src/pages/Logs/Logs.test.tsx
  src/pages/Logs/Logs.tsx
  src/scss/_breakpoints.scss
Labels: Review: QA +1, Review: Code +1 (with changes)

#1551 WD-5218 - Fetch audit logs
  src/components/AuditLogsTable/AuditLogsTable.test.tsx
  src/components/AuditLogsTable/AuditLogsTable.tsx
  src/components/LoadingSpinner/LoadingSpinner.test.tsx
  src/components/LoadingSpinner/LoadingSpinner.tsx
  src/components/LoadingSpinner/_loading-spinner.scss
  src/components/LoadingSpinner/index.ts
  src/pages/EntityDetails/EntityDetails.tsx
  src/pages/EntityDetails/Model/Logs/ActionLogs/ActionLogs.tsx
  src/pages/EntityDetails/Model/Logs/ActionLogs/_action-logs.scss
  src/pages/EntityDetails/Model/Model.test.tsx
  src/pages/EntityDetails/_entity-details.scss
  src/pages/Logs/Logs.test.tsx
  src/pages/Logs/audit-logs-fake-data.ts
  src/pages/ModelsIndex/ModelsIndex.test.tsx
  src/pages/ModelsIndex/ModelsIndex.tsx
  src/store/store.ts
Labels: Review: QA +1, Review: Code +1

#1552 WD-5478 - Store fetched audit events in Redux
  src/components/AuditLogsTable/AuditLogsTable.test.tsx
  src/components/AuditLogsTable/AuditLogsTable.tsx
  src/pages/EntityDetails/Model/Model.test.tsx
  src/pages/Logs/Logs.test.tsx
  src/store/juju/actions.test.ts
  src/store/juju/reducers.test.ts
  src/store/juju/selectors.test.ts
  src/store/juju/selectors.ts
  src/store/juju/slice.ts
  src/store/juju/types.ts
  src/store/middleware/check-auth.ts
  src/store/middleware/model-poller.test.ts
  src/store/middleware/model-poller.ts
  src/testing/factories/juju/juju.ts
Labels: Review: QA +1, Review: Code +1

#1554 Add AutocompleteInput component
  src/components/AutocompleteInput/AutocompleteInput.test.tsx
  src/components/AutocompleteInput/AutocompleteInput.tsx
  src/components/AutocompleteInput/index.ts
  src/store/juju/selectors.ts
Labels: Review: Code +1

#1553 Add audit event selectors
  src/store/juju/selectors.test.ts
  src/store/juju/selectors.ts
Labels: Review: Code +1

#1555 feat: Add refresh button to AuditLogsTable
  src/components/AuditLogsTable/AuditLogsTable.test.tsx
  src/components/AuditLogsTable/AuditLogsTable.tsx
Labels: Review: QA +1, Review: Code +1

#1558 WD-5543- Combine panel css
  src/components/Aside/Aside.tsx
  src/components/Aside/_aside.scss
  src/components/ModelTableList/StatusGroup.tsx
  src/components/Panel/Panel.test.tsx
  src/components/Panel/Panel.tsx
  src/components/Panel/_panel.scss
  src/components/PanelHeader/PanelHeader.test.tsx
  src/components/PanelHeader/PanelHeader.tsx
  src/panels/ActionsPanel/ActionsPanel.tsx
  src/panels/ActionsPanel/CharmActionsPanel.tsx
  src/panels/ActionsPanel/_actions-panel.scss
  src/panels/CharmsAndActionsPanel/CharmActionsPanelTitle/CharmActionsPanelTitle.test.tsx
  src/panels/CharmsAndActionsPanel/CharmActionsPanelTitle/CharmActionsPanelTitle.tsx
  src/panels/CharmsPanel/CharmsPanel.tsx
  src/panels/CharmsPanel/_charms-panel.scss
  src/panels/ConfigPanel/BooleanConfig.tsx
  src/panels/ConfigPanel/ConfigPanel.tsx
  src/panels/ConfigPanel/__snapshots__/ConfigPanel.test.tsx.snap
  src/panels/ConfigPanel/_config-panel.scss
  src/panels/RegisterController/RegisterController.tsx
  src/panels/ShareModelPanel/ShareModel.test.tsx
  src/panels/ShareModelPanel/ShareModel.tsx
  src/panels/ShareModelPanel/share-model.scss
  src/scss/_utils.scss
  src/scss/custom/_icons.scss
Labels: Review: QA +1, Review: Code +1 (with changes)

#1560 Pass audit log params
  src/juju/api.test.ts
  src/juju/api.ts
  src/store/middleware/model-poller.test.ts
  src/store/middleware/model-poller.ts
Labels: Review: QA +1, Review: Code +1

#1559 feat: Audit logs pagination
  src/components/AuditLogsTable/AuditLogsTable.test.tsx
  src/components/AuditLogsTable/AuditLogsTable.tsx
  src/components/AuditLogsTable/_audit-logs-table.scss
Labels: Review: QA +1, Review: Code +1

#1561 WD-5220 - Add audit logs filter panel
  src/animations/FadeIn.tsx
  src/components/ActionBar/ActionBar.test.tsx
  src/components/ActionBar/ActionBar.tsx
  src/components/ActionBar/_action-bar.scss
  src/components/ActionBar/index.ts
  src/components/AuditLogsTable/AuditLogsTable.test.tsx
  src/components/AuditLogsTable/AuditLogsTable.tsx
  src/components/AuditLogsTable/AuditLogsTableActions/AuditLogsTableActions.test.tsx
  src/components/AuditLogsTable/AuditLogsTableActions/AuditLogsTableActions.tsx
  src/components/AuditLogsTable/AuditLogsTableActions/_audit-logs-table-actions.scss
  src/components/AuditLogsTable/AuditLogsTableActions/index.ts
  src/components/AuditLogsTable/AuditLogsTableFilters/AuditLogsTableFilters.test.tsx
  src/components/AuditLogsTable/AuditLogsTableFilters/AuditLogsTableFilters.tsx
  src/components/AuditLogsTable/AuditLogsTableFilters/index.ts
  src/components/AuditLogsTable/_audit-logs-table.scss
  src/components/AuditLogsTable/consts.ts
  src/components/AuditLogsTable/hooks.test.tsx
  src/components/AuditLogsTable/hooks.ts
  src/pages/EntityDetails/Model/Logs/Logs.test.tsx
  src/pages/EntityDetails/Model/Logs/Logs.tsx
  src/pages/Logs/Logs.test.tsx
  src/pages/Logs/Logs.tsx
  src/panels/AuditLogsFilterPanel/AuditLogsFilterPanel.test.tsx
  src/panels/AuditLogsFilterPanel/AuditLogsFilterPanel.tsx
  src/panels/AuditLogsFilterPanel/Fields/Fields.test.tsx
  src/panels/AuditLogsFilterPanel/Fields/Fields.tsx
  src/panels/AuditLogsFilterPanel/Fields/index.ts
  src/panels/AuditLogsFilterPanel/index.ts
  src/panels/AuditLogsFilterPanel/types.ts
  src/panels/Panels.test.tsx
  src/panels/Panels.tsx
  src/scss/index.scss
  src/store/juju/selectors.test.ts
  src/store/juju/selectors.ts
  src/testing/utils.tsx
Labels: Review: QA +1, Review: Code +1

#1562 WD-5221- Fetch when filters change
  src/components/AuditLogsTable/AuditLogsTable.tsx
  src/components/AuditLogsTable/AuditLogsTableActions/AuditLogsTableActions.test.tsx
  src/components/AuditLogsTable/AuditLogsTableActions/AuditLogsTableActions.tsx
  src/components/AuditLogsTable/AuditLogsTableFilters/AuditLogsTableFilters.tsx
  src/components/AuditLogsTable/consts.ts
  src/components/AuditLogsTable/hooks.test.tsx
  src/components/AuditLogsTable/hooks.ts
  src/hooks/useQueryParams.test.tsx
  src/hooks/useQueryParams.ts
  src/panels/AuditLogsFilterPanel/AuditLogsFilterPanel.test.tsx
  src/panels/AuditLogsFilterPanel/AuditLogsFilterPanel.tsx
  src/panels/AuditLogsFilterPanel/Fields/Fields.test.tsx
  src/panels/AuditLogsFilterPanel/Fields/Fields.tsx
  src/store/juju/selectors.test.ts
  src/store/juju/selectors.ts
  src/store/juju/types.ts
Labels: Review: QA +1, Review: Code +1 (with changes)

#1565 WD-5780 - Add pagination to bottom of table
  src/components/ActionBar/_action-bar.scss
  src/components/AuditLogsTable/AuditLogsTable.test.tsx
  src/components/AuditLogsTable/AuditLogsTable.tsx
  src/components/AuditLogsTable/AuditLogsTableActions/AuditLogsTableActions.test.tsx
  src/components/AuditLogsTable/AuditLogsTableActions/AuditLogsTableActions.tsx
  src/components/AuditLogsTable/AuditLogsTableActions/_audit-logs-table-actions.scss
  src/components/AuditLogsTable/AuditLogsTablePagination/AuditLogsTablePagination.test.tsx
  src/components/AuditLogsTable/AuditLogsTablePagination/AuditLogsTablePagination.tsx
  src/components/AuditLogsTable/AuditLogsTablePagination/_audit-logs-table-pagination.scss
  src/components/AuditLogsTable/AuditLogsTablePagination/index.ts
  src/scss/custom/_icons.scss
  src/scss/index.scss
Labels: Review: QA +1, Review: Code +1

#1564 WD-5745 - Remove facade name and version filters
  src/components/AuditLogsTable/AuditLogsTableFilters/AuditLogsTableFilters.tsx
  src/components/AuditLogsTable/hooks.test.tsx
  src/panels/AuditLogsFilterPanel/AuditLogsFilterPanel.test.tsx
  src/panels/AuditLogsFilterPanel/AuditLogsFilterPanel.tsx
  src/panels/AuditLogsFilterPanel/Fields/Fields.test.tsx
  src/panels/AuditLogsFilterPanel/Fields/Fields.tsx
  src/panels/AuditLogsFilterPanel/types.ts
Labels: Review: QA +1, Review: Code +1

#1567 refactor: Audit logs limit redux
  src/components/AuditLogsTable/AuditLogsTable.tsx
  src/components/AuditLogsTable/AuditLogsTableActions/AuditLogsTableActions.test.tsx
  src/components/AuditLogsTable/AuditLogsTableActions/AuditLogsTableActions.tsx
  src/components/AuditLogsTable/AuditLogsTablePagination/AuditLogsTablePagination.test.tsx
  src/components/AuditLogsTable/AuditLogsTablePagination/AuditLogsTablePagination.tsx
  src/components/AuditLogsTable/consts.ts
  src/components/AuditLogsTable/hooks.ts
  src/store/juju/actions.test.ts
  src/store/juju/reducers.test.ts
  src/store/juju/selectors.ts
  src/store/juju/slice.ts
  src/store/juju/types.ts
  src/store/middleware/check-auth.ts
  src/testing/factories/juju/juju.ts
Labels: Review: QA +1, Review: Code +1 (with changes)

#1568 WD-5746 - fix: Fix pagination navigating to new blank page
  src/components/AuditLogsTable/AuditLogsTable.tsx
  src/components/AuditLogsTable/AuditLogsTablePagination/AuditLogsTablePagination.test.tsx
  src/components/AuditLogsTable/AuditLogsTablePagination/AuditLogsTablePagination.tsx
Labels: Review: QA +1, Review: Code +1 (with changes)

#1570 WD-5811 - feat: Add page component, route and side nav link
  src/components/PrimaryNav/PrimaryNav.test.tsx
  src/components/PrimaryNav/PrimaryNav.tsx
  src/components/PrimaryNav/PrimaryNavLink/PrimaryNavLink.test.tsx
  src/components/PrimaryNav/PrimaryNavLink/PrimaryNavLink.tsx
  src/components/PrimaryNav/PrimaryNavLink/index.ts
  src/components/Routes/Routes.tsx
  src/pages/AdvancedSearch/AdvancedSearch.test.tsx
  src/pages/AdvancedSearch/AdvancedSearch.tsx
  src/pages/AdvancedSearch/index.ts
  src/store/general/selectors.test.ts
  src/store/general/selectors.ts
  src/urls.ts
Labels: Review: QA +1, Review: Code +1

#1571 Revert "WD-5811 - feat: Add page component, route and side nav link"
  src/components/PrimaryNav/PrimaryNav.test.tsx
  src/components/PrimaryNav/PrimaryNav.tsx
  src/components/PrimaryNav/PrimaryNavLink/PrimaryNavLink.test.tsx
  src/components/PrimaryNav/PrimaryNavLink/PrimaryNavLink.tsx
  src/components/PrimaryNav/PrimaryNavLink/index.ts
  src/components/Routes/Routes.tsx
  src/pages/AdvancedSearch/AdvancedSearch.test.tsx
  src/pages/AdvancedSearch/AdvancedSearch.tsx
  src/pages/AdvancedSearch/index.ts
  src/store/general/selectors.test.ts
  src/store/general/selectors.ts
  src/urls.ts
Labels: Review: Code needed

#1572 Cross model queries page
  src/components/PrimaryNav/PrimaryNav.test.tsx
  src/components/PrimaryNav/PrimaryNav.tsx
  src/components/PrimaryNav/PrimaryNavLink/PrimaryNavLink.test.tsx
  src/components/PrimaryNav/PrimaryNavLink/PrimaryNavLink.tsx
  src/components/PrimaryNav/PrimaryNavLink/index.ts
  src/components/Routes/Routes.tsx
  src/pages/AdvancedSearch/AdvancedSearch.test.tsx
  src/pages/AdvancedSearch/AdvancedSearch.tsx
  src/pages/AdvancedSearch/index.ts
  src/store/general/selectors.test.ts
  src/store/general/selectors.ts
  src/urls.ts
Labels: Review: Code +1

#1573 Enable CI for the cross-model-queries branch.
  .github/workflows/actions.yml
Labels: Review: Code +1

#1569 WD-5797 - feat: Add ​​CrossModelQuery to JIMM API
  src/juju/api.test.ts
  src/juju/api.ts
  src/juju/jimm-facade.test.ts
  src/juju/jimm-facade.ts
  src/juju/types.ts
  src/store/juju/actions.test.ts
  src/store/juju/reducers.test.ts
  src/store/juju/selectors.test.ts
  src/store/juju/selectors.ts
  src/store/juju/slice.ts
  src/store/juju/types.ts
  src/store/middleware/check-auth.ts
  src/store/middleware/model-poller.test.ts
  src/store/middleware/model-poller.ts
  src/testing/factories/juju/juju.ts
Labels: Review: QA +1, Review: Code +1 (with changes)

#1574 refactor: Add getIsJuju and refactor PrimaryNav
  src/components/PrimaryNav/PrimaryNav.test.tsx
  src/components/PrimaryNav/PrimaryNav.tsx
  src/components/PrimaryNav/PrimaryNavLink/PrimaryNavLink.test.tsx
  src/components/PrimaryNav/PrimaryNavLink/PrimaryNavLink.tsx
  src/components/PrimaryNav/PrimaryNavLink/index.ts
  src/store/general/selectors.test.ts
  src/store/general/selectors.ts
Labels: Review: QA +1, Review: Code +1

#1575 WD-5812 - test: Add CrossModelQuery test factories
  src/testing/factories/juju/jimm-types.ts
  src/testing/factories/juju/jimm.ts
Labels: Review: Code +1 (with changes)

#1576 WD-5813 - Cross model search form
  src/pages/AdvancedSearch/AdvancedSearch.test.tsx
  src/pages/AdvancedSearch/AdvancedSearch.tsx
  src/pages/AdvancedSearch/SearchForm/SearchForm.test.tsx
  src/pages/AdvancedSearch/SearchForm/SearchForm.tsx
  src/pages/AdvancedSearch/SearchForm/index.ts
Labels: Review: QA +1, Review: Code +1

#1579 WD-5860 - feat: Extend Cross Model Query Factory
  src/testing/factories/juju/jimm-types.ts
  src/testing/factories/juju/jimm.ts
Labels: Review: Code +1

#1581 WD-5815 - Add search history
  docs/multipass-microk8s.md
  src/pages/AdvancedSearch/SearchForm/SearchForm.test.tsx
  src/pages/AdvancedSearch/SearchForm/SearchForm.tsx
  src/pages/AdvancedSearch/SearchForm/SearchHistoryMenu/SearchHistoryMenu.test.tsx
  src/pages/AdvancedSearch/SearchForm/SearchHistoryMenu/SearchHistoryMenu.tsx
  src/pages/AdvancedSearch/SearchForm/SearchHistoryMenu/index.ts
  src/pages/AdvancedSearch/SearchForm/types.ts
  src/scss/index.scss
Labels: Review: QA +1, Review: Code +1

#1580 WD-5816 WD-5817 - feat: Add results block with mode switcher
  src/layout/BaseLayout/_base-layout.scss
  src/pages/AdvancedSearch/AdvancedSearch.tsx
  src/pages/AdvancedSearch/ResultsBlock/ResultsBlock.test.tsx
  src/pages/AdvancedSearch/ResultsBlock/ResultsBlock.tsx
  src/pages/AdvancedSearch/ResultsBlock/index.ts
  src/scss/_breakpoints.scss
Labels: Review: QA +1, Review: Code +1 (with changes)

#1583 Handle error strings when fetching the status.
  src/juju/api.test.ts
  src/juju/api.ts
Labels: Review: Code +1

#1582 WD-5819 - feat: Add copy JSON button
  src/pages/AdvancedSearch/SearchForm/SearchForm.test.tsx
  src/pages/AdvancedSearch/SearchForm/SearchForm.tsx
  src/store/juju/slice.ts
Labels: Review: QA +1, Review: Code +1 (with changes)

#1586 WD-5820 - Add tree view
  package.json
  src/pages/AdvancedSearch/ResultsBlock/ResultsBlock.test.tsx
  src/pages/AdvancedSearch/ResultsBlock/ResultsBlock.tsx
  yarn.lock
Labels: Review: QA +1, Review: Code +1

#1584 WD-5814 - Add help
  src/pages/AdvancedSearch/SearchForm/QueryLink/QueryLink.test.tsx
  src/pages/AdvancedSearch/SearchForm/QueryLink/QueryLink.tsx
  src/pages/AdvancedSearch/SearchForm/QueryLink/index.ts
  src/pages/AdvancedSearch/SearchForm/SearchForm.tsx
  src/pages/AdvancedSearch/SearchForm/SearchHelp/SearchHelp.test.tsx
  src/pages/AdvancedSearch/SearchForm/SearchHelp/SearchHelp.tsx
  src/pages/AdvancedSearch/SearchForm/SearchHelp/index.ts
  src/pages/AdvancedSearch/SearchForm/SearchHistoryMenu/SearchHistoryMenu.test.tsx
  src/pages/AdvancedSearch/SearchForm/SearchHistoryMenu/SearchHistoryMenu.tsx
  src/pages/AdvancedSearch/SearchForm/_search-form.scss
Labels: Review: QA +1, Review: Code +1

#1591 WD-5823 - Display status icons
  src/components/Status/Status.test.tsx
  src/components/Status/Status.tsx
  src/pages/AdvancedSearch/ResultsBlock/ResultsBlock.test.tsx
  src/pages/AdvancedSearch/ResultsBlock/ResultsBlock.tsx
  src/pages/AdvancedSearch/ResultsBlock/_results-block.scss
  src/scss/custom/_status_icons.scss
Labels: Review: QA +1, Review: Code +1

#1589 WD-5821 - JSON tree theme
  src/pages/AdvancedSearch/ResultsBlock/ResultsBlock.tsx
Labels: Review: QA +1, Review: Code +1

#1590 WD-5941 - Display model name
  src/components/ModelDetailsLink/ModelDetailsLink.test.tsx
  src/components/ModelDetailsLink/ModelDetailsLink.tsx
  src/components/ModelDetailsLink/index.ts
  src/components/ModelTableList/CloudGroup.tsx
  src/components/ModelTableList/ModelSummary/ModelSummary.tsx
  src/components/ModelTableList/OwnerGroup.tsx
  src/components/ModelTableList/StatusGroup.tsx
  src/juju/api.ts
  src/pages/AdvancedSearch/ResultsBlock/ResultsBlock.test.tsx
  src/pages/AdvancedSearch/ResultsBlock/ResultsBlock.tsx
  src/store/juju/selectors.ts
Labels: Review: QA +1, Review: Code +1

#1592 WD-5959 - Link keys to the model tabs
  src/components/Breadcrumb/Breadcrumb.tsx
  src/components/ModelDetailsLink/ModelDetailsLink.test.tsx
  src/components/ModelDetailsLink/ModelDetailsLink.tsx
  src/components/ModelTableList/ModelSummary/ModelSummary.tsx
  src/pages/AdvancedSearch/ResultsBlock/ResultsBlock.test.tsx
  src/pages/AdvancedSearch/ResultsBlock/ResultsBlock.tsx
  src/pages/AdvancedSearch/ResultsModelLink/ResultsModelLink.test.tsx
  src/pages/AdvancedSearch/ResultsModelLink/ResultsModelLink.tsx
  src/pages/AdvancedSearch/ResultsModelLink/index.ts
  src/pages/EntityDetails/App/App.tsx
  src/pages/EntityDetails/EntityDetails.tsx
  src/urls.ts
Labels: Review: QA +1, Review: Code +1

#1594 WD-5824 - feat: Display relative date next to actual date
  src/pages/AdvancedSearch/ResultsBlock/ResultsBlock.test.tsx
  src/pages/AdvancedSearch/ResultsBlock/ResultsBlock.tsx
Labels: Review: QA +1, Review: Code +1 (with changes)

#1596 WD-5818 - Syntax highlighting
  package.json
  src/pages/AdvancedSearch/ResultsBlock/ResultsBlock.test.tsx
  src/pages/AdvancedSearch/ResultsBlock/ResultsBlock.tsx
  src/prismjs.d.ts
  yarn.lock
Labels: Review: QA +1, Review: Code +1

#1597 WD-5992 - feat: Display a message if no results found
  src/pages/AdvancedSearch/ResultsBlock/ResultsBlock.test.tsx
  src/pages/AdvancedSearch/ResultsBlock/ResultsBlock.tsx
Labels: Review: QA +1, Review: Code +1 (with changes)

#1595 WD-5869 - feat: Display search errors
  package.json
  src/pages/AdvancedSearch/AdvancedSearch.tsx
  src/pages/AdvancedSearch/CodeSnippetBlock/CodeSnippetBlock.test.tsx
  src/pages/AdvancedSearch/CodeSnippetBlock/CodeSnippetBlock.tsx
  src/pages/AdvancedSearch/CodeSnippetBlock/index.ts
  src/pages/AdvancedSearch/ErrorsBlock/ErrorsBlock.test.tsx
  src/pages/AdvancedSearch/ErrorsBlock/ErrorsBlock.tsx
  src/pages/AdvancedSearch/ErrorsBlock/_errors-block.scss
  src/pages/AdvancedSearch/ErrorsBlock/index.ts
  src/pages/AdvancedSearch/ResultsBlock/ResultsBlock.tsx
  src/pages/AdvancedSearch/types.ts
  yarn.lock
Labels: Review: QA +1, Review: Code +1 (with changes)

#1598 WD-6052 - Link charms to Charmhub
  src/pages/AdvancedSearch/CodeSnippetBlock/CodeSnippetBlock.test.tsx
  src/pages/AdvancedSearch/CodeSnippetBlock/CodeSnippetBlock.tsx
Labels: Review: QA +1, Review: Code +1
