Repository canonical/juju-dashboard, pull requests merged in 2024-06, with the labels that each got.

#1765 WD-11589 - refactor: remove nested components in StatusGroup
  src/components/ModelTableList/StatusGroup/StatusGroup.test.tsx
  src/components/ModelTableList/StatusGroup/StatusGroup.tsx
  src/components/ModelTableList/StatusGroup/WarningMessage/WarningMessage.test.tsx
  src/components/ModelTableList/StatusGroup/WarningMessage/WarningMessage.tsx
  src/components/ModelTableList/StatusGroup/WarningMessage/index.ts
Labels: Review: QA +1, Review: Code +1

#1763 WD-11704 - feat: add development proxy to JIMM
  .env.development
  .gitignore
  vite.config.ts
Labels: Review: QA +1, Review: Code +1

#1764 WD-11677 - docs: add JIMM setup
  HACKING.md
Labels: Review: QA +1, Review: Code +1 (with changes)

#1767 WD-11705 - feat: add API thunks for JIMM endpoints
  package.json
  src/global.d.ts
  src/juju/jimm/api.ts
  src/juju/jimm/thunks.test.ts
  src/juju/jimm/thunks.ts
  src/store/middleware/check-auth.ts
  src/testing/setup.ts
  yarn.lock
Labels: Review: QA +1, Review: Code +1

#1766 WD-11590 - refactor: remove nested components in CodeSnippetBlock
  src/pages/AdvancedSearch/CodeSnippetBlock/CodeSnippetBlock.tsx
  src/pages/AdvancedSearch/CodeSnippetBlock/Label/Label.test.tsx
  src/pages/AdvancedSearch/CodeSnippetBlock/Label/Label.tsx
  src/pages/AdvancedSearch/CodeSnippetBlock/Label/index.ts
  src/pages/AdvancedSearch/CodeSnippetBlock/Label/utils.ts
  src/pages/AdvancedSearch/CodeSnippetBlock/Value/Value.test.tsx
  src/pages/AdvancedSearch/CodeSnippetBlock/Value/Value.tsx
  src/pages/AdvancedSearch/CodeSnippetBlock/Value/index.ts
Labels: Review: QA +1, Review: Code +1

#1768 WD-11928 - refactor: authentication method enum
  HACKING.md
  public/config.demo.js
  public/config.js
  public/config.js.go
  src/components/LogIn/LogIn.test.tsx
  src/components/LogIn/LogIn.tsx
  src/index.test.tsx
  src/index.tsx
  src/juju/api-hooks/common.ts
  src/juju/api.test.ts
  src/juju/api.ts
  src/store/app/actions.test.ts
  src/store/app/actions.ts
  src/store/app/thunks.test.ts
  src/store/app/thunks.ts
  src/store/general/selectors.ts
  src/store/general/types.ts
  src/store/middleware/model-poller.test.ts
  src/store/middleware/model-poller.ts
  src/testing/factories/general.ts
  src/types.ts
Labels: Review: QA +1, Review: Code +1

#1770 WD-11706 - feat: display OIDC login form
  src/components/LogIn/IdentityProviderForm/IdentityProviderForm.tsx
  src/components/LogIn/IdentityProviderForm/index.ts
  src/components/LogIn/IdentityProviderForm/types.ts
  src/components/LogIn/LogIn.test.tsx
  src/components/LogIn/LogIn.tsx
  src/components/LogIn/OIDCForm/OIDCForm.test.tsx
  src/components/LogIn/OIDCForm/OIDCForm.tsx
  src/components/LogIn/OIDCForm/index.ts
  src/components/LogIn/OIDCForm/types.ts
  src/index.test.tsx
  src/index.tsx
  src/juju/jimm/thunks.ts
  src/store/middleware/model-poller.test.ts
  src/store/middleware/model-poller.ts
Labels: Review: QA +1, Review: Code +1

#1774 fix: dotrun workflow task
  .github/workflows/actions.yml
Labels: Review: QA +1, Review: Code +1

#1773 WD-12072 - docs: candid docs
  HACKING.md
Labels: Review: QA +1, Review: Code +1

#1771 WD-11591 - refactor: remove nested components in ControllersIndex
  src/pages/ControllersIndex/ControllersIndex.tsx
Labels: Review: QA +1, Review: Code +1

#1776 WD-11707 - feat: OIDC ws login
  HACKING.md
  package.json
  src/juju/api.test.ts
  src/juju/api.ts
  src/juju/jimm/JIMMV3.ts
  src/juju/jimm/JIMMV4.test.ts
  yarn.lock
Labels: Review: QA +1, Review: Code +1

#1778 WD-12178 - fix: handle 500 errors for the whoami endpoint
  src/store/middleware/model-poller.test.ts
  src/store/middleware/model-poller.ts
Labels: Review: QA needed, Review: Code needed

#1772 WD-11592 - refactor: remove nested components in ApplicationsTab
  src/pages/EntityDetails/Model/ApplicationsTab/AppOffersTable/AppOffersTable.test.tsx
  src/pages/EntityDetails/Model/ApplicationsTab/AppOffersTable/AppOffersTable.tsx
  src/pages/EntityDetails/Model/ApplicationsTab/AppOffersTable/index.ts
  src/pages/EntityDetails/Model/ApplicationsTab/AppOffersTable/types.ts
  src/pages/EntityDetails/Model/ApplicationsTab/ApplicationsTab.tsx
  src/pages/EntityDetails/Model/ApplicationsTab/ContentRevealTitle/ContentRevealTitle.test.tsx
  src/pages/EntityDetails/Model/ApplicationsTab/ContentRevealTitle/ContentRevealTitle.tsx
  src/pages/EntityDetails/Model/ApplicationsTab/ContentRevealTitle/index.ts
  src/pages/EntityDetails/Model/ApplicationsTab/RemoteAppsTable/RemoteAppsTable.test.tsx
  src/pages/EntityDetails/Model/ApplicationsTab/RemoteAppsTable/RemoteAppsTable.tsx
  src/pages/EntityDetails/Model/ApplicationsTab/RemoteAppsTable/index.ts
  src/pages/EntityDetails/Model/ApplicationsTab/RemoteAppsTable/types.ts
Labels: Review: QA +1, Review: Code +1

#1779 WD-11708 - feat: log out using OIDC
  src/store/app/thunks.test.ts
  src/store/app/thunks.ts
Labels: Review: QA +1, Review: Code +1

#1783 WD-11593 - refactor: remove nested components from ActionLogs
  src/pages/EntityDetails/Model/Logs/ActionLogs/ActionLogs.test.tsx
  src/pages/EntityDetails/Model/Logs/ActionLogs/ActionLogs.tsx
  src/pages/EntityDetails/Model/Logs/ActionLogs/ActionPayloadModal/ActionPayloadModal.test.tsx
  src/pages/EntityDetails/Model/Logs/ActionLogs/ActionPayloadModal/ActionPayloadModal.tsx
  src/pages/EntityDetails/Model/Logs/ActionLogs/ActionPayloadModal/index.ts
  src/pages/EntityDetails/Model/Logs/ActionLogs/ActionPayloadModal/types.ts
  src/pages/EntityDetails/Model/Logs/ActionLogs/types.ts
Labels: Review: QA +1, Review: Code +1
