Repository canonical/juju-dashboard, pull requests merged in 2024-03, with the labels that each got.

#1739 WD-9418 - Update the readme screenshot
  HACKING.md
  docs/images/dashboard.png
  src/panels/ConfigPanel/ConfigPanel.tsx
Labels: Review: Code +1

#1740 WD-9420 - Remove some references to jaas.ai
  CONTRIBUTING.md
  HACKING.md
  RELEASING.md
  src/layout/BaseLayout/BaseLayout.test.tsx
  src/layout/BaseLayout/BaseLayout.tsx
  src/static/images/logo/jaas-text.svg
Labels: Review: QA +1, Review: Code +1

#1738 WD-9417 - feat: update error handling after jujulib update to v6
  package.json
  src/components/secrets/SecretForm/SecretForm.test.tsx
  src/components/secrets/SecretForm/SecretForm.tsx
  src/juju/api.test.ts
  src/juju/api.ts
  src/juju/jimm/JIMMV4.ts
  src/pages/ModelDetails/ModelDetails.tsx
  src/panels/GrantSecretPanel/GrantSecretPanel.test.tsx
  src/panels/GrantSecretPanel/GrantSecretPanel.tsx
  src/panels/RemoveSecretPanel/RemoveSecretPanel.test.tsx
  src/panels/RemoveSecretPanel/RemoveSecretPanel.tsx
  src/store/juju/actions.test.ts
  src/store/juju/reducers.test.ts
  src/store/juju/slice.ts
  src/store/middleware/check-auth.ts
  src/store/middleware/model-poller.test.ts
  src/store/middleware/model-poller.ts
  yarn.lock
Labels: Review: QA +1, Review: Code +1 (with changes)

#1744 WD-9899 - refactor: use upstreamed FormikField
  package.json
  src/components/FormikField/FormikField.test.tsx
  src/components/FormikField/FormikField.tsx
  src/components/FormikField/index.ts
  src/components/secrets/RevisionField/RevisionField.tsx
  src/components/secrets/SecretForm/Fields/Fields.tsx
  src/panels/GrantSecretPanel/GrantSecretPanel.tsx
  src/panels/RemoveSecretPanel/Fields/Fields.tsx
  yarn.lock
Labels: Review: Code +1

#1746 WD-9981 - refactor: remove click propagation
  package.json
  src/panels/ActionsPanel/ActionsPanel.tsx
  src/panels/ActionsPanel/CharmActionsPanel.tsx
  src/panels/RemoveSecretPanel/Fields/Fields.tsx
  yarn.lock
Labels: Review: QA +1, Review: Code +1
