Repository canonical/juju-dashboard, pull requests merged in 2024-02, with the labels that each got.

#1696 WD-8412 - Hide secrets tab
  src/juju/api.test.ts
  src/juju/api.ts
  src/pages/EntityDetails/EntityDetails.test.tsx
  src/pages/EntityDetails/EntityDetails.tsx
  src/pages/EntityDetails/Model/Model.test.tsx
  src/pages/EntityDetails/Model/Model.tsx
  src/store/juju/actions.test.ts
  src/store/juju/reducers.test.ts
  src/store/juju/selectors.test.ts
  src/store/juju/selectors.ts
  src/store/juju/slice.ts
  src/store/juju/types.ts
  src/store/middleware/model-poller.ts
  src/testing/factories/juju/juju.ts
Labels: Review: QA +1, Review: Code +1

#1694 WD-8593 - handle optional juju types
  package.json
  src/pages/EntityDetails/Model/Logs/ActionLogs/ActionLogs.test.tsx
  src/pages/EntityDetails/Model/Logs/ActionLogs/ActionLogs.tsx
  src/store/juju/slice.ts
  src/store/juju/thunks.ts
  yarn.lock
Labels: Review: Code +1

#1693 WD-8546 - Create secrets
  package.json
  src/components/FormikField/FormikField.test.tsx
  src/components/FormikField/FormikField.tsx
  src/components/FormikField/index.ts
  src/juju/apiHooks.test.tsx
  src/juju/apiHooks.ts
  src/pages/EntityDetails/Model/Secrets/Secrets.test.tsx
  src/pages/EntityDetails/Model/Secrets/Secrets.tsx
  src/panels/AddSecretPanel/AddSecretPanel.test.tsx
  src/panels/AddSecretPanel/AddSecretPanel.tsx
  src/panels/AddSecretPanel/Fields/Fields.test.tsx
  src/panels/AddSecretPanel/Fields/Fields.tsx
  src/panels/AddSecretPanel/types.ts
  src/store/middleware/model-poller.ts
  yarn.lock
Labels: Review: QA +1, Review: Code +1

#1699 Store inline errors by key
  src/hooks/useInlineErrors.test.ts
  src/hooks/useInlineErrors.ts
  src/panels/ActionsPanel/ActionsPanel.tsx
Labels: Review: QA +1, Review: Code +1

#1697 WD-8617 - fix: Fix displaying the first colorless part of the message in WebCLI
  .eslintrc
  package.json
  src/components/WebCLI/Output.test.tsx
  src/components/WebCLI/Output.tsx
  src/components/WebCLI/__snapshots__/WebCLI.test.tsx.snap
  src/panels/ActionsPanel/ActionsPanel.tsx
  yarn.lock
Labels: Review: QA +1, Review: Code +1 (with changes)

#1702 WD-8522 - Link to applications
  src/components/AppLink/AppLink.tsx
  src/pages/EntityDetails/Model/Secrets/SecretsTable/SecretsTable.test.tsx
  src/pages/EntityDetails/Model/Secrets/SecretsTable/SecretsTable.tsx
Labels: Review: QA +1, Review: Code +1

#1700 WD-8566 - fetch new secrets
  src/juju/apiHooks.test.tsx
  src/juju/apiHooks.ts
  src/pages/EntityDetails/Model/Secrets/Secrets.test.tsx
  src/pages/EntityDetails/Model/Secrets/Secrets.tsx
  src/panels/AddSecretPanel/AddSecretPanel.test.tsx
  src/panels/AddSecretPanel/AddSecretPanel.tsx
Labels: Review: QA +1, Review: Code +1

#1701 WD-8396 - Copy secret IDs
  src/pages/EntityDetails/Model/Secrets/SecretsTable/SecretsTable.test.tsx
  src/pages/EntityDetails/Model/Secrets/SecretsTable/SecretsTable.tsx
Labels: Review: QA +1, Review: Code +1

#1698 WD-8625 - feat: Display errors in WebCLI
  src/components/WebCLI/Output.tsx
  src/components/WebCLI/WebCLI.test.tsx
  src/components/WebCLI/WebCLI.tsx
  src/hooks/useInlineErrors.test.ts
  src/hooks/useInlineErrors.ts
Labels: Review: QA +1, Review: Code +1

#1703 WD-8729 - feat: Display errors in Config Panel
  src/hooks/useInlineErrors.test.ts
  src/hooks/useInlineErrors.ts
  src/panels/ActionsPanel/ActionsPanel.tsx
  src/panels/ConfigPanel/ConfigPanel.test.tsx
  src/panels/ConfigPanel/ConfigPanel.tsx
Labels: Review: QA +1, Review: Code +1 (with changes)

#1707 WD-8398 - View secret contents
  src/components/FormikField/index.ts
  src/components/secrets/RevisionField/RevisionField.test.tsx
  src/components/secrets/RevisionField/RevisionField.tsx
  src/components/secrets/RevisionField/index.ts
  src/juju/apiHooks.test.tsx
  src/juju/apiHooks.ts
  src/pages/EntityDetails/Model/Secrets/SecretContent/SecretContent.test.tsx
  src/pages/EntityDetails/Model/Secrets/SecretContent/SecretContent.tsx
  src/pages/EntityDetails/Model/Secrets/SecretContent/index.ts
  src/pages/EntityDetails/Model/Secrets/Secrets.test.tsx
  src/pages/EntityDetails/Model/Secrets/SecretsTable/SecretsTable.test.tsx
  src/pages/EntityDetails/Model/Secrets/SecretsTable/SecretsTable.tsx
  src/store/juju/actions.test.ts
  src/store/juju/reducers.test.ts
  src/store/juju/selectors.test.ts
  src/store/juju/selectors.ts
  src/store/juju/slice.ts
  src/store/juju/types.ts
  src/testing/factories/juju/juju.ts
Labels: Review: QA +1, Review: Code +1

#1704 WD-8401 - Remove secrets
  src/juju/apiHooks.test.tsx
  src/juju/apiHooks.ts
  src/pages/EntityDetails/Model/Secrets/SecretsTable/SecretsTable.test.tsx
  src/pages/EntityDetails/Model/Secrets/SecretsTable/SecretsTable.tsx
  src/panels/Panels.test.tsx
  src/panels/Panels.tsx
  src/panels/RemoveSecretPanel/Fields/Fields.test.tsx
  src/panels/RemoveSecretPanel/Fields/Fields.tsx
  src/panels/RemoveSecretPanel/Fields/index.ts
  src/panels/RemoveSecretPanel/RemoveSecretPanel.test.tsx
  src/panels/RemoveSecretPanel/RemoveSecretPanel.tsx
  src/panels/RemoveSecretPanel/index.ts
  src/panels/RemoveSecretPanel/types.ts
Labels: Review: QA +1, Review: Code +1

#1709 WD-8400 - Add update secrets panel
  src/consts.ts
  src/juju/apiHooks.test.tsx
  src/juju/apiHooks.ts
  src/pages/EntityDetails/Model/Secrets/SecretContent/SecretContent.test.tsx
  src/pages/EntityDetails/Model/Secrets/SecretContent/SecretContent.tsx
  src/pages/EntityDetails/Model/Secrets/SecretsTable/SecretsTable.test.tsx
  src/pages/EntityDetails/Model/Secrets/SecretsTable/SecretsTable.tsx
  src/panels/AddSecretPanel/AddSecretPanel.tsx
  src/panels/AddSecretPanel/index.ts
  src/panels/AddSecretPanel/types.ts
  src/panels/AuditLogsFilterPanel/AuditLogsFilterPanel.test.tsx
  src/panels/AuditLogsFilterPanel/Fields/Fields.tsx
  src/panels/Panels.test.tsx
  src/panels/Panels.tsx
  src/panels/SecretFormPanel/Fields/Fields.test.tsx
  src/panels/SecretFormPanel/Fields/Fields.tsx
  src/panels/SecretFormPanel/Fields/index.ts
  src/panels/SecretFormPanel/SecretFormPanel.test.tsx
  src/panels/SecretFormPanel/SecretFormPanel.tsx
  src/panels/SecretFormPanel/index.ts
  src/panels/SecretFormPanel/types.ts
Labels: Review: QA +1, Review: Code +1

#1708 WD-8825 - feat: Display error in UserMenu
  src/components/LogIn/LogIn.test.tsx
  src/components/LogIn/LogIn.tsx
  src/components/UserMenu/UserMenu.test.tsx
  src/components/UserMenu/UserMenu.tsx
  src/index.tsx
  src/juju/api.test.ts
  src/juju/api.ts
  src/panels/ConfigPanel/ConfigPanel.test.tsx
  src/panels/ConfigPanel/ConfigPanel.tsx
Labels: Review: QA +1, Review: Code +1

#1710 WD-8828 - feat: Display errors in Action Logs
  src/pages/EntityDetails/Model/Logs/ActionLogs/ActionLogs.test.tsx
  src/pages/EntityDetails/Model/Logs/ActionLogs/ActionLogs.tsx
Labels: Review: QA +1, Review: Code +1

#1712 WD-8402 - grant/revoke secrets
  src/juju/apiHooks.test.tsx
  src/juju/apiHooks.ts
  src/pages/EntityDetails/Model/Secrets/SecretsTable/SecretsTable.test.tsx
  src/pages/EntityDetails/Model/Secrets/SecretsTable/SecretsTable.tsx
  src/panels/GrantSecretPanel/GrantSecretPanel.test.tsx
  src/panels/GrantSecretPanel/GrantSecretPanel.tsx
  src/panels/GrantSecretPanel/index.ts
  src/panels/Panels.test.tsx
  src/panels/Panels.tsx
  src/testing/factories/juju/juju.ts
Labels: Review: QA +1, Review: Code +1 (with changes)

#1711 WD-8829 - feat: display errors in Charms and Actions Panel
  src/index.test.tsx
  src/pages/ModelsIndex/ModelsIndex.test.tsx
  src/panels/ActionsPanel/ActionsPanel.test.tsx
  src/panels/CharmsAndActionsPanel/CharmsAndActionsPanel.test.tsx
  src/panels/CharmsAndActionsPanel/CharmsAndActionsPanel.tsx
  src/panels/CharmsPanel/CharmsPanel.test.tsx
  src/panels/CharmsPanel/CharmsPanel.tsx
  src/panels/ConfigPanel/ConfigPanel.test.tsx
Labels: Review: QA +1, Review: Code +1

#1713 WD-8858 - fix: fix notifications overlapping top navigation bar
  src/scss/_vanilla-overrides.scss
Labels: Review: QA +1, Review: Code +1

#1715 WD-8411 - Limit write actions for secrets
  src/hooks/useCanManageSecrets.test.tsx
  src/hooks/useCanManageSecrets.ts
  src/juju/api.test.ts
  src/juju/api.ts
  src/pages/EntityDetails/Model/Secrets/Secrets.test.tsx
  src/pages/EntityDetails/Model/Secrets/Secrets.tsx
  src/pages/EntityDetails/Model/Secrets/SecretsTable/SecretsTable.test.tsx
  src/pages/EntityDetails/Model/Secrets/SecretsTable/SecretsTable.tsx
  src/pages/ModelDetails/ModelDetails.tsx
  src/panels/Panels.test.tsx
  src/panels/Panels.tsx
Labels: Review: QA +1, Review: Code +1

#1716 WD-8753 - Use revision field in remove form
  src/panels/RemoveSecretPanel/Fields/Fields.tsx
Labels: Review: QA +1, Review: Code +1

#1714 WD-8855 - feat: display model-poller errors
  src/components/ConnectionError/ConnectionError.test.tsx
  src/components/ConnectionError/ConnectionError.tsx
  src/store/juju/actions.test.ts
  src/store/juju/reducers.test.ts
  src/store/juju/selectors.ts
  src/store/juju/slice.ts
  src/store/juju/types.ts
  src/store/middleware/check-auth.ts
  src/store/middleware/model-poller.test.ts
  src/store/middleware/model-poller.ts
  src/testing/factories/juju/juju.ts
Labels: Review: QA +1, Review: Code +1 (with changes)

#1717 WD-8929 - owner in access count
  src/pages/EntityDetails/Model/Secrets/SecretsTable/SecretsTable.test.tsx
  src/pages/EntityDetails/Model/Secrets/SecretsTable/SecretsTable.tsx
Labels: Review: QA +1, Review: Code +1

#1719 WD-8406 - Add secrets in the config panel
  src/components/secrets/SecretForm/Fields/Fields.test.tsx
  src/components/secrets/SecretForm/Fields/Fields.tsx
  src/components/secrets/SecretForm/Fields/index.ts
  src/components/secrets/SecretForm/SecretForm.test.tsx
  src/components/secrets/SecretForm/SecretForm.tsx
  src/components/secrets/SecretForm/index.ts
  src/components/secrets/SecretForm/types.ts
  src/pages/EntityDetails/Model/Secrets/SecretsTable/SecretsTable.tsx
  src/panels/ConfigPanel/SecretsPicker/SecretsPicker.test.tsx
  src/panels/ConfigPanel/SecretsPicker/SecretsPicker.tsx
  src/panels/SecretFormPanel/SecretFormPanel.test.tsx
  src/panels/SecretFormPanel/SecretFormPanel.tsx
  src/scss/_utils.scss
  src/store/juju/slice.ts
Labels: Review: QA +1, Review: Code +1

#1722 WD-8521 - Make secrets table responsive
  src/pages/EntityDetails/Model/Secrets/SecretsTable/SecretsTable.tsx
  src/pages/EntityDetails/Model/Secrets/SecretsTable/_secrets-table.scss
Labels: Review: QA +1, Review: Code +1 (with changes)

#1721 WD-8407 - config grant access
  src/components/secrets/SecretLabel/SecretLabel.test.tsx
  src/components/secrets/SecretLabel/SecretLabel.tsx
  src/components/secrets/SecretLabel/index.ts
  src/juju/api.ts
  src/panels/ActionsPanel/ActionsPanel.tsx
  src/panels/ActionsPanel/CharmActionsPanel.tsx
  src/panels/ConfigPanel/ConfigPanel.test.tsx
  src/panels/ConfigPanel/ConfigPanel.tsx
  src/panels/ConfigPanel/SecretsPicker/SecretsPicker.tsx
  src/panels/types.ts
  src/store/juju/selectors.ts
Labels: Review: QA +1, Review: Code +1

#1724 WD-8971 - Display secret name
  src/pages/EntityDetails/Model/Secrets/SecretContent/SecretContent.tsx
  src/panels/GrantSecretPanel/GrantSecretPanel.tsx
  src/panels/RemoveSecretPanel/RemoveSecretPanel.tsx
Labels: Review: QA +1, Review: Code +1

#1723 WD-8972 - Disable app-owned secret actions
  src/pages/EntityDetails/Model/Secrets/SecretsTable/SecretsTable.test.tsx
  src/pages/EntityDetails/Model/Secrets/SecretsTable/SecretsTable.tsx
  src/panels/ConfigPanel/ConfigPanel.tsx
  src/panels/ConfigPanel/SecretsPicker/SecretsPicker.test.tsx
  src/panels/ConfigPanel/SecretsPicker/SecretsPicker.tsx
  src/utils/index.ts
  src/utils/secretIsAppOwned.test.ts
  src/utils/secretIsAppOwned.ts
Labels: Review: QA +1, Review: Code +1

#1726 WD-9028 - Dedupe API hooks
  src/juju/apiHooks.test.tsx
  src/juju/apiHooks.ts
  src/utils/index.ts
  src/utils/toErrorString.test.ts
  src/utils/toErrorString.ts
Labels: Review: QA +1, Review: Code +1

#1729 Improve timeout promise
  src/juju/api.test.ts
  src/juju/api.ts
  src/juju/apiHooks.test.tsx
Labels: Review: QA +1, Review: Code +1

#1728 WD-9066 - split up secret hooks
  src/components/secrets/SecretForm/SecretForm.test.tsx
  src/components/secrets/SecretForm/SecretForm.tsx
  src/juju/api-hooks/common.test.tsx
  src/juju/api-hooks/common.ts
  src/juju/api-hooks/index.ts
  src/juju/api-hooks/secrets.test.tsx
  src/juju/api-hooks/secrets.ts
  src/pages/EntityDetails/Model/Secrets/SecretContent/SecretContent.test.tsx
  src/pages/EntityDetails/Model/Secrets/SecretContent/SecretContent.tsx
  src/pages/EntityDetails/Model/Secrets/Secrets.test.tsx
  src/pages/EntityDetails/Model/Secrets/Secrets.tsx
  src/panels/ConfigPanel/ConfigPanel.test.tsx
  src/panels/ConfigPanel/ConfigPanel.tsx
  src/panels/ConfigPanel/SecretsPicker/SecretsPicker.test.tsx
  src/panels/ConfigPanel/SecretsPicker/SecretsPicker.tsx
  src/panels/GrantSecretPanel/GrantSecretPanel.test.tsx
  src/panels/GrantSecretPanel/GrantSecretPanel.tsx
  src/panels/RemoveSecretPanel/RemoveSecretPanel.test.tsx
  src/panels/RemoveSecretPanel/RemoveSecretPanel.tsx
  src/panels/SecretFormPanel/SecretFormPanel.test.tsx
Labels: Review: Code +1

#1720 WD-9004 - feat: handle connection errors in WebCLI
  src/components/WebCLI/WebCLI.test.tsx
  src/components/WebCLI/WebCLI.tsx
  src/components/WebCLI/__snapshots__/WebCLI.test.tsx.snap
  src/components/WebCLI/connection.ts
Labels: Review: QA +1, Review: Code +1 (with changes)

#1731 WD-9101 - application API hooks
  src/juju/api-hooks/application.test.tsx
  src/juju/api-hooks/application.ts
  src/juju/api-hooks/index.ts
  src/juju/api.test.ts
  src/juju/api.ts
  src/panels/ConfigPanel/ConfigPanel.test.tsx
  src/panels/ConfigPanel/ConfigPanel.tsx
Labels: Review: QA +1, Review: Code +1

#1730 WD-9100 - action API hooks
  src/juju/api-hooks/actions.test.tsx
  src/juju/api-hooks/actions.ts
  src/juju/api-hooks/index.ts
  src/juju/api.test.ts
  src/juju/api.ts
  src/pages/EntityDetails/Model/Logs/ActionLogs/ActionLogs.test.tsx
  src/pages/EntityDetails/Model/Logs/ActionLogs/ActionLogs.tsx
  src/panels/ActionsPanel/ActionsPanel.test.tsx
  src/panels/ActionsPanel/ActionsPanel.tsx
  src/panels/ActionsPanel/CharmActionsPanel.test.tsx
  src/panels/ActionsPanel/CharmActionsPanel.tsx
Labels: Review: QA +1, Review: Code +1

#1733 WD-9168 - Handle sub-pixel media queries
  src/pages/AdvancedSearch/SearchForm/_search-form.scss
  src/scss/_breakpoints.scss
Labels: Review: QA +1, Review: Code +1

#1732 WD-9153 - Config panel components
  src/panels/ConfigPanel/BooleanConfig/BooleanConfig.test.tsx
  src/panels/ConfigPanel/BooleanConfig/BooleanConfig.tsx
  src/panels/ConfigPanel/BooleanConfig/index.ts
  src/panels/ConfigPanel/ChangedKeyValues/ChangedKeyValues.test.tsx
  src/panels/ConfigPanel/ChangedKeyValues/ChangedKeyValues.tsx
  src/panels/ConfigPanel/ChangedKeyValues/index.ts
  src/panels/ConfigPanel/ConfigField/ConfigField.test.tsx
  src/panels/ConfigPanel/ConfigField/ConfigField.tsx
  src/panels/ConfigPanel/ConfigField/index.ts
  src/panels/ConfigPanel/ConfigPanel.tsx
  src/panels/ConfigPanel/NumberConfig/NumberConfig.test.tsx
  src/panels/ConfigPanel/NumberConfig/NumberConfig.tsx
  src/panels/ConfigPanel/NumberConfig/index.ts
  src/panels/ConfigPanel/TextAreaConfig/TextAreaConfig.test.tsx
  src/panels/ConfigPanel/TextAreaConfig/TextAreaConfig.tsx
  src/panels/ConfigPanel/TextAreaConfig/index.ts
  src/panels/ConfigPanel/utils.test.ts
  src/panels/ConfigPanel/utils.ts
Labels: Review: QA +1, Review: Code +1

#1727 WD-9042 - Validate secrets
  src/juju/api-hooks/application.test.tsx
  src/juju/api-hooks/application.ts
  src/juju/api-hooks/common.test.tsx
  src/juju/api-hooks/common.ts
  src/juju/api.ts
  src/panels/ConfigPanel/BooleanConfig/BooleanConfig.test.tsx
  src/panels/ConfigPanel/BooleanConfig/BooleanConfig.tsx
  src/panels/ConfigPanel/ChangedKeyValues/ChangedKeyValues.tsx
  src/panels/ConfigPanel/ConfigField/ConfigField.test.tsx
  src/panels/ConfigPanel/ConfigField/ConfigField.tsx
  src/panels/ConfigPanel/ConfigPanel.test.tsx
  src/panels/ConfigPanel/ConfigPanel.tsx
  src/panels/ConfigPanel/NumberConfig/NumberConfig.test.tsx
  src/panels/ConfigPanel/NumberConfig/NumberConfig.tsx
  src/panels/ConfigPanel/SecretsPicker/SecretsPicker.tsx
  src/panels/ConfigPanel/TextAreaConfig/TextAreaConfig.test.tsx
  src/panels/ConfigPanel/TextAreaConfig/TextAreaConfig.tsx
  src/panels/ConfigPanel/types.ts
  src/panels/ConfigPanel/utils.test.ts
  src/panels/ConfigPanel/utils.ts
Labels: Review: QA +1, Review: Code +1

#1734 WD-9169 - Handle model store error
  src/juju/api.test.ts
  src/juju/api.ts
  src/store/middleware/check-auth.ts
Labels: Review: QA +1, Review: Code +1
