Repository canonical/juju-dashboard, pull requests merged in 2024-10, with the labels that each got.

#1803 WD-14879 - feat: before 0.13.0 release changes
  src/juju/jimm/api.ts
  src/juju/jimm/listeners.test.ts
  src/juju/jimm/listeners.ts
  src/juju/jimm/thunks.test.ts
  src/juju/jimm/thunks.ts
Labels: Review: QA needed, Review: Code +1

#1808 chore: update tics coverage frequency
  .github/workflows/tics-coverage.yml
Labels: Review: Code needed

#1807 WD-15784 - fix: fix issues observed in k8s charm
  src/components/EntityInfo/EntityInfo.test.tsx
  src/components/EntityInfo/EntityInfo.tsx
  src/components/EntityInfo/_entity-info.scss
  src/components/TruncatedTooltip/TruncatedTooltip.test.tsx
  src/components/TruncatedTooltip/TruncatedTooltip.tsx
  src/pages/AdvancedSearch/SearchForm/SearchHelp/SearchHelp.tsx
Labels: Review: QA +1, Review: Code +1

#1809 feat: update dashboard version to 0.13.1
  package.json
Labels: Review: Code +1

#1811 WD-16018 - doc: update instructions for running JIMM
  HACKING.md
Labels: Review: Code +1

#1810 WD-16020 - refactor: replace BrowserRouter with createBrowserRouter
  src/components/App/App.test.tsx
  src/components/App/App.tsx
  src/components/CaptureRoutes/CaptureRoutes.test.tsx
  src/components/CaptureRoutes/CaptureRoutes.tsx
  src/components/CaptureRoutes/index.ts
  src/components/LogIn/LogIn.test.tsx
  src/components/LogIn/LogIn.tsx
  src/components/Routes/Routes.tsx
  src/pages/PageNotFound/PageNotFound.test.tsx
Labels: Review: QA +1, Review: Code +1
