Repository canonical/juju-dashboard, pull requests merged in 2024-05, with the labels that each got.

#1754 WD-11351 - feat: use tag logo
  public/app-icon.png
  public/favicon.ico
  src/components/LogIn/LogIn.test.tsx
  src/components/LogIn/LogIn.tsx
  src/components/LogIn/_login.scss
  src/components/Logo/Logo.test.tsx
  src/components/Logo/Logo.tsx
  src/components/Logo/_logo.scss
  src/components/Logo/index.ts
  src/components/upstream/Panel/Panel.tsx
  src/layout/BaseLayout/BaseLayout.test.tsx
  src/layout/BaseLayout/BaseLayout.tsx
  src/static/images/logo/jaas-logo-black-on-white.svg
  src/static/images/logo/jaas-text-dark.svg
  src/static/images/logo/juju-logo-black-on-white.svg
  src/static/images/logo/juju-text-dark.svg
  src/static/images/logo/logo-mark.svg
Labels: Review: QA +1, Review: Code +1

#1756 WD-11355 - fix: remove overrides that have been fixed in Vanilla
  src/components/ChipGroup/_chip-group.scss
  src/components/ModelTableList/ModelSummary/ModelSummary.tsx
  src/components/WebCLI/_webcli.scss
  src/juju/api.test.ts
  src/juju/api.ts
  src/pages/EntityDetails/_entity-details.scss
  src/pages/ModelsIndex/_models.scss
  src/scss/_utils.scss
  src/scss/_vanilla-overrides.scss
  src/scss/_variables.scss
Labels: Review: QA +1, Review: Code +1 (with changes)

#1755 WD-11352 - ci: add TICS reporting
  .github/workflows/tics-coverage.yml
Labels: Review: Code +1

#1760 fix: upload coverage artefact
  .github/workflows/tics-coverage.yml
Labels: Review: Code +1

#1762 WD-11588 - refactor: Remove nested components in components/Login
  src/components/LogIn/IdentityProviderForm/IdentityProviderForm.test.tsx
  src/components/LogIn/IdentityProviderForm/IdentityProviderForm.tsx
  src/components/LogIn/IdentityProviderForm/index.ts
  src/components/LogIn/LogIn.test.tsx
  src/components/LogIn/LogIn.tsx
  src/components/LogIn/UserPassForm/UserPassForm.test.tsx
  src/components/LogIn/UserPassForm/UserPassForm.tsx
  src/components/LogIn/UserPassForm/index.ts
  src/components/LogIn/types.ts
Labels: Review: QA +1, Review: Code +1
