Repository canonical/juju-dashboard, pull requests merged in 2024-01, with the labels that each got.

#1676 WD-7718 - feat: Remove additional controllers feature
  HACKING.md
  src/juju/api.test.ts
  src/juju/api.ts
  src/pages/ControllersIndex/ControllersIndex.test.tsx
  src/pages/ControllersIndex/ControllersIndex.tsx
  src/pages/ControllersIndex/_controllers.scss
  src/panels/Panels.test.tsx
  src/panels/Panels.tsx
  src/panels/RegisterController/RegisterController.test.tsx
  src/panels/RegisterController/RegisterController.tsx
  src/panels/RegisterController/register-controller.scss
  src/store/app/actions.ts
  src/store/app/thunks.test.ts
  src/store/app/thunks.ts
  src/store/juju/types.ts
  src/store/middleware/model-poller.test.ts
  src/store/middleware/model-poller.ts
  src/testing/factories/juju/juju.ts
Labels: Review: QA +1, Review: Code +1 (with changes)

#1685 Update version to 0.12.0
  HACKING.md
  RELEASING.md
  package.json
Labels: Review: Code +1

#1683 WD-8392 - Fix dotrun install in GitHub action
  .github/workflows/actions.yml
Labels: Review: Code +1

#1684 WD-8394 - Add secrets tab
  src/pages/EntityDetails/EntityDetails.test.tsx
  src/pages/EntityDetails/EntityDetails.tsx
  src/pages/EntityDetails/Model/Model.test.tsx
  src/pages/EntityDetails/Model/Model.tsx
  src/pages/EntityDetails/Model/Secrets/Secrets.test.tsx
  src/pages/EntityDetails/Model/Secrets/Secrets.tsx
  src/pages/EntityDetails/Model/Secrets/index.ts
  src/urls.ts
Labels: Review: QA +1, Review: Code +1 (with changes)

#1682 WD-8294 - feat: Display connection and polling of models error
  src/store/app/thunks.test.ts
  src/store/app/thunks.ts
  src/store/middleware/check-auth.ts
Labels: Review: QA +1, Review: Code +1 (with changes)

#1686 WD-8309 - feat: Display error when trying to retrieve models info
  src/juju/api.test.ts
  src/juju/api.ts
  src/pages/ModelsIndex/ModelsIndex.test.tsx
  src/pages/ModelsIndex/ModelsIndex.tsx
  src/store/juju/actions.test.ts
  src/store/juju/reducers.test.ts
  src/store/juju/selectors.ts
  src/store/juju/slice.ts
  src/store/juju/types.ts
  src/store/middleware/model-poller.test.ts
  src/store/middleware/model-poller.ts
  src/testing/factories/juju/juju.ts
Labels: Review: QA +1, Review: Code +1 (with changes)

#1687 WD-8431 - Fetch and store secrets
  src/juju/api.test.ts
  src/juju/api.ts
  src/juju/apiHooks.test.tsx
  src/juju/apiHooks.ts
  src/juju/types.ts
  src/pages/EntityDetails/Model/Model.test.tsx
  src/pages/EntityDetails/Model/Secrets/Secrets.test.tsx
  src/pages/EntityDetails/Model/Secrets/Secrets.tsx
  src/store/juju/actions.test.ts
  src/store/juju/reducers.test.ts
  src/store/juju/selectors.test.ts
  src/store/juju/selectors.ts
  src/store/juju/slice.ts
  src/store/juju/types.ts
  src/store/types.ts
  src/testing/factories/juju/juju.ts
Labels: Review: QA +1, Review: Code +1

#1688 WD-8308 - feat: Add comments to errors that should continue to only be logged to the console
  src/hooks/useLocalStorage.ts
  src/juju/api.ts
  src/pages/EntityDetails/Model/Logs/ActionLogs/ActionLogs.tsx
  src/pages/ModelDetails/ModelDetails.tsx
  src/store/middleware/check-auth.ts
Labels: Review: Code +1 (with changes)

#1689 WD-8395 - Add secrets table
  src/components/AuditLogsTable/AuditLogsTable.tsx
  src/components/RelativeDate/RelativeDate.test.tsx
  src/components/RelativeDate/RelativeDate.tsx
  src/components/RelativeDate/index.ts
  src/pages/EntityDetails/Model/Logs/ActionLogs/ActionLogs.tsx
  src/pages/EntityDetails/Model/Secrets/Secrets.test.tsx
  src/pages/EntityDetails/Model/Secrets/Secrets.tsx
  src/pages/EntityDetails/Model/Secrets/SecretsTable/SecretsTable.test.tsx
  src/pages/EntityDetails/Model/Secrets/SecretsTable/SecretsTable.tsx
  src/pages/EntityDetails/Model/Secrets/SecretsTable/index.ts
Labels: Review: QA +1, Review: Code +1

#1690 WD-8541 - fix: Scroll to the top of Config Panel if error occurs
  src/components/ScrollOnRender/ScrollOnRender.test.tsx
  src/components/ScrollOnRender/ScrollOnRender.tsx
  src/hooks/useScrollOnRender.test.ts
  src/hooks/useScrollOnRender.ts
  src/setupTests.js
Labels: Review: QA +1, Review: Code +1 (with changes)

#1692 WD-8399 - Create add secrets panel
  src/pages/EntityDetails/Model/Secrets/Secrets.test.tsx
  src/pages/EntityDetails/Model/Secrets/Secrets.tsx
  src/panels/AddSecretPanel/AddSecretPanel.test.tsx
  src/panels/AddSecretPanel/AddSecretPanel.tsx
  src/panels/AddSecretPanel/Fields/Fields.test.tsx
  src/panels/AddSecretPanel/Fields/Fields.tsx
  src/panels/AddSecretPanel/Fields/index.ts
  src/panels/AddSecretPanel/index.ts
  src/panels/AddSecretPanel/types.ts
  src/panels/Panels.test.tsx
  src/panels/Panels.tsx
Labels: Review: QA +1, Review: Code +1
