Repository canonical/juju-dashboard, pull requests merged in 2024-07, with the labels that each got.

#1786 WD-11664 - refactor: remove nested components in ActionsPanel
  src/panels/ActionsPanel/ActionsPanel.test.tsx
  src/panels/ActionsPanel/ActionsPanel.tsx
  src/panels/ActionsPanel/ConfirmationDialog/ConfirmationDialog.test.tsx
  src/panels/ActionsPanel/ConfirmationDialog/ConfirmationDialog.tsx
  src/panels/ActionsPanel/ConfirmationDialog/index.ts
  src/panels/ActionsPanel/ConfirmationDialog/types.ts
  src/panels/ActionsPanel/types.ts
Labels: Review: QA +1, Review: Code +1 (with changes)

#1769 WD-11666 - refactor: remove nested components in ConfigPanel
  src/panels/ConfigPanel/ConfigPanel.test.tsx
  src/panels/ConfigPanel/ConfigPanel.tsx
  src/panels/ConfigPanel/ConfirmationDialog/ConfirmationDialog.test.tsx
  src/panels/ConfigPanel/ConfirmationDialog/ConfirmationDialog.tsx
  src/panels/ConfigPanel/ConfirmationDialog/index.ts
  src/panels/ConfigPanel/ConfirmationDialog/types.ts
  src/panels/ConfigPanel/types.ts
Labels: Review: QA +1, Review: Code +1 (with changes)

#1785 WD-11665 - refactor: remove nested components in CharmActionsPanel
  src/pages/EntityDetails/Model/Logs/ActionLogs/ActionPayloadModal/ActionPayloadModal.test.tsx
  src/panels/ActionsPanel/CharmActionsPanel/CharmActionsPanel.test.tsx
  src/panels/ActionsPanel/CharmActionsPanel/CharmActionsPanel.tsx
  src/panels/ActionsPanel/CharmActionsPanel/ConfirmationDialog/ConfirmationDialog.test.tsx
  src/panels/ActionsPanel/CharmActionsPanel/ConfirmationDialog/ConfirmationDialog.tsx
  src/panels/ActionsPanel/CharmActionsPanel/ConfirmationDialog/index.ts
  src/panels/ActionsPanel/CharmActionsPanel/ConfirmationDialog/types.ts
  src/panels/ActionsPanel/CharmActionsPanel/index.ts
Labels: Review: QA +1, Review: Code +1 (with changes)

#1752 WD-12909 - Use application layout from react-components
  package.json
  src/components/Aside/Aside.tsx
  src/components/AuditLogsTable/AuditLogsTablePagination/AuditLogsTablePagination.test.tsx
  src/components/Panel/Panel.tsx
  src/components/PrimaryNav/PrimaryNav.tsx
  src/components/PrimaryNav/_primary-nav.scss
  src/components/UserMenu/UserMenu.tsx
  src/components/secrets/SecretForm/Fields/Fields.test.tsx
  src/components/upstream/ApplicationLayout/AppAside/AppAside.test.tsx
  src/components/upstream/ApplicationLayout/AppAside/AppAside.tsx
  src/components/upstream/ApplicationLayout/AppAside/index.ts
  src/components/upstream/ApplicationLayout/AppMain/AppMain.test.tsx
  src/components/upstream/ApplicationLayout/AppMain/AppMain.tsx
  src/components/upstream/ApplicationLayout/AppMain/index.ts
  src/components/upstream/ApplicationLayout/AppNavigation/AppNavigation.test.tsx
  src/components/upstream/ApplicationLayout/AppNavigation/AppNavigation.tsx
  src/components/upstream/ApplicationLayout/AppNavigation/index.ts
  src/components/upstream/ApplicationLayout/AppNavigationBar/AppNavigationBar.test.tsx
  src/components/upstream/ApplicationLayout/AppNavigationBar/AppNavigationBar.tsx
  src/components/upstream/ApplicationLayout/AppNavigationBar/index.ts
  src/components/upstream/ApplicationLayout/AppStatus/AppStatus.test.tsx
  src/components/upstream/ApplicationLayout/AppStatus/AppStatus.tsx
  src/components/upstream/ApplicationLayout/AppStatus/index.ts
  src/components/upstream/ApplicationLayout/Application/Application.test.tsx
  src/components/upstream/ApplicationLayout/Application/Application.tsx
  src/components/upstream/ApplicationLayout/Application/index.ts
  src/components/upstream/ApplicationLayout/ApplicationLayout.test.tsx
  src/components/upstream/ApplicationLayout/ApplicationLayout.tsx
  src/components/upstream/ApplicationLayout/index.ts
  src/components/upstream/Panel/Panel.test.tsx
  src/components/upstream/Panel/Panel.tsx
  src/components/upstream/Panel/index.ts
  src/components/upstream/SideNavigation/SideNavigation.test.tsx
  src/components/upstream/SideNavigation/SideNavigation.tsx
  src/components/upstream/SideNavigation/SideNavigationBase/SideNavigationBase.test.tsx
  src/components/upstream/SideNavigation/SideNavigationBase/SideNavigationBase.tsx
  src/components/upstream/SideNavigation/SideNavigationBase/index.ts
  src/components/upstream/SideNavigation/SideNavigationItem/SideNavigationItem.test.tsx
  src/components/upstream/SideNavigation/SideNavigationItem/SideNavigationItem.tsx
  src/components/upstream/SideNavigation/SideNavigationItem/index.ts
  src/components/upstream/SideNavigation/SideNavigationLink/SideNavigationLink.test.tsx
  src/components/upstream/SideNavigation/SideNavigationLink/SideNavigationLink.tsx
  src/components/upstream/SideNavigation/SideNavigationLink/index.ts
  src/components/upstream/SideNavigation/SideNavigationText/SideNavigationText.test.tsx
  src/components/upstream/SideNavigation/SideNavigationText/SideNavigationText.tsx
  src/components/upstream/SideNavigation/SideNavigationText/index.ts
  src/components/upstream/SideNavigation/index.ts
  src/layout/BaseLayout/BaseLayout.tsx
  src/pages/AdvancedSearch/SearchForm/SearchForm.test.tsx
  src/pages/AdvancedSearch/SearchForm/SearchHistoryMenu/SearchHistoryMenu.test.tsx
  src/pages/EntityDetails/App/App.test.tsx
  src/pages/EntityDetails/Model/ApplicationsTab/LocalAppsTable/LocalAppsTable.test.tsx
  src/panels/ActionsPanel/CharmActionsPanel/CharmActionsPanel.test.tsx
  src/panels/AuditLogsFilterPanel/AuditLogsFilterPanel.test.tsx
  src/panels/CharmsPanel/CharmsPanel.test.tsx
  yarn.lock
Labels: Review: QA +1, Review: Code +1

#1789 WD-12713 - feat: handle oidc refresh and revoke
  .eslintrc
  src/consts.ts
  src/index.tsx
  src/juju/jimm/listeners.test.ts
  src/juju/jimm/listeners.ts
  src/juju/jimm/thunks.test.ts
  src/juju/jimm/thunks.ts
  src/pages/EntityDetails/EntityDetails.test.tsx
  src/pages/EntityDetails/EntityDetails.tsx
  src/store/app/thunks.test.ts
  src/store/app/thunks.ts
  src/store/listenerMiddleware.ts
  src/store/middleware/check-auth.ts
  src/store/middleware/model-poller.test.ts
  src/store/middleware/model-poller.ts
  src/store/store.ts
Labels: Review: QA +1, Review: Code +1

#1791 WD-13598 - build: update dashboard version to 0.13.0
  package.json
Labels: Review: Code +1

#1792 ci: update TICS Auth Secret in workflow
  .github/workflows/tics-coverage.yml
Labels: Review: Code +1
