Repository canonical/juju-dashboard, pull requests merged in 2024-11, with the labels that each got.

#1813 WD-16328 - feat: fix access to application details in dashboard charm
  package.json
  yarn.lock
Labels: Review: QA +1, Review: Code +1

#1812 WD-16080 - feat: add ReBAC Admin
  package.json
  src/components/PrimaryNav/PrimaryNav.tsx
  src/components/PrimaryNav/types.ts
  src/components/Routes/Routes.tsx
  src/layout/BaseLayout/BaseLayout.tsx
  src/pages/Permissions/Permissions.test.tsx
  src/pages/Permissions/Permissions.tsx
  src/pages/Permissions/index.ts
  src/scss/index.scss
  src/urls.ts
  vite.config.ts
  yarn.lock
Labels: Review: QA +1, Review: Code +1

#1818 feat: update dashboard version to 0.13.2
  package.json
Labels: Review: Code needed

#1815 WD-16060 - feat: add secondary navigation component
  src/components/PrimaryNav/PrimaryNav.tsx
  src/components/PrimaryNav/types.ts
  src/components/SecondaryNavigation/SecondaryNavigation.test.tsx
  src/components/SecondaryNavigation/SecondaryNavigation.tsx
  src/components/SecondaryNavigation/_secondary-navigation.scss
  src/components/SecondaryNavigation/index.ts
  src/components/SecondaryNavigation/types.ts
  src/layout/BaseLayout/BaseLayout.test.tsx
  src/layout/BaseLayout/BaseLayout.tsx
  src/layout/BaseLayout/_base-layout.scss
  src/pages/Permissions/Permissions.tsx
  src/pages/Permissions/types.ts
Labels: Review: Code +1

#1817 WD-16027 - feat: only display ReBAC Admin to JIMM admins
  package.json
  src/components/PrimaryNav/PrimaryNav.test.tsx
  src/components/PrimaryNav/PrimaryNav.tsx
  src/components/Routes/Routes.test.tsx
  src/components/Routes/Routes.tsx
  src/layout/BaseLayout/BaseLayout.tsx
  src/pages/AdvancedSearch/AdvancedSearch.tsx
  src/pages/AdvancedSearch/index.ts
  src/pages/AdvancedSearch/types.ts
  src/pages/ControllersIndex/ControllersIndex.tsx
  src/pages/ControllersIndex/index.ts
  src/pages/ControllersIndex/types.ts
  src/pages/EntityDetails/EntityDetails.tsx
  src/pages/EntityDetails/index.ts
  src/pages/EntityDetails/types.ts
  src/pages/Logs/Logs.tsx
  src/pages/Logs/index.ts
  src/pages/Logs/types.ts
  src/pages/ModelsIndex/ModelsIndex.tsx
  src/pages/ModelsIndex/index.ts
  src/pages/ModelsIndex/types.ts
  src/pages/Permissions/Permissions.tsx
  src/pages/Permissions/index.ts
  src/pages/Permissions/types.ts
  src/store/general/selectors.test.ts
  src/store/general/selectors.ts
  src/store/general/types.ts
  src/store/middleware/model-poller.test.ts
  src/store/middleware/model-poller.ts
  yarn.lock
Labels: Review: Code +1
