Repository canonical/juju-dashboard, pull requests merged in 2025-07, with the labels that each got.

#1999 feat: reconnect the CLI websocket when sending new commands
  src/components/WebCLI/WebCLI.test.tsx
  src/components/WebCLI/WebCLI.tsx
  src/components/WebCLI/connection.ts
  src/components/WebCLI/types.ts
Labels: Review: QA +1, Review: Code +1 (with changes)

#1984 feat(actions): create `update-changelog` action (WD-23113)
  .github/actions/cut-release-pr/index.js
  .github/actions/get-pr-severity/index.js
  .github/actions/update-changelog/action.yaml
  .github/actions/update-changelog/index.js
  actions/src/lib/changelog.test.ts
  actions/src/lib/changelog.ts
  actions/src/lib/release.ts
  actions/src/update-changelog/action.yaml
  actions/src/update-changelog/index.ts
  actions/src/update-changelog/main.test.ts
  actions/src/update-changelog/main.ts
Labels: Review: Code +1

#2004 chore: update outdated URLs with new ones
  src/components/ErrorBoundary/ErrorBoundary.tsx
  src/components/ErrorBoundary/__snapshots__/ErrorBoundary.test.tsx.snap
  src/components/WebCLI/__snapshots__/WebCLI.test.tsx.snap
  src/pages/ControllersIndex/ControllersIndex.tsx
  src/pages/EntityDetails/EntityDetails.tsx
  src/pages/EntityDetails/Model/ApplicationsTab/ApplicationsTab.tsx
  src/pages/EntityDetails/Model/Model.tsx
  src/pages/EntityDetails/Unit/Unit.tsx
  src/pages/ModelsIndex/ModelsIndex.tsx
  src/urls.ts
Labels: Review: QA needed, Review: Code +1

#2008 chore(ci): add Keycloak authentication
  e2e/fixtures/setup.ts
  e2e/helpers/auth/AuthImplementation.ts
  e2e/helpers/auth/Users.ts
  e2e/helpers/auth/backends/Keycloak.ts
  e2e/helpers/auth/backends/OIDC.ts
  e2e/helpers/auth/backends/utils.ts
  e2e/helpers/juju-cli.ts
  e2e/utils/getEnv.ts
Labels: Review: Code +1

#2014 feat: write build scripts for dashboard charms
  .github/actions/setup-k8s-charm/action.yml
  .github/actions/setup-machine-charm/action.yml
  charms/k8s-charm/build.sh
  charms/machine-charm/build.sh
  charms/scripts/update-machine-charm.sh
  docs/building-charms.md
  docs/multipass-microk8s.md
Labels: Review: Code +1 (with changes), e2e

#2020 chore: update RELEASE.md
  RELEASING.md
Labels: Review: Code needed

#2021 chore: update TiCS to use self-hosted runners
  .github/workflows/tics-coverage.yml
  .github/workflows/tiobe_archive.txt
Labels: Review: Code +1 (with changes)
