Repository canonical/juju-dashboard, pull requests merged in 2025-09, with the labels that each got.

#2061 feat: add haproxy-route interface for the machine charm
  charms/machine-charm/.flake8
  charms/machine-charm/lib/charms/haproxy/v1/haproxy_route.py
  charms/machine-charm/metadata.yaml
  charms/machine-charm/requirements.txt
  charms/machine-charm/src/charm.py
  charms/machine-charm/src/config.py
  charms/machine-charm/tests/test_charm.py
  charms/machine-charm/tox.ini
Labels: Review: Code +1, e2e

#2065 fix(ci): use `pull_request_target` for PR actions
  .github/workflows/create-cut-pr.yml
  .github/workflows/create-release-pr.yml
Labels: Review: Code +1

#2063 fix: alternate workaround for `node-util`, to remove `vite-plugin-node-polyfills`
  e2e/fixtures/setup.ts
  package.json
  src/store/middleware/model-poller.ts
  src/store/store.ts
  vite.config.ts
  yarn.lock
Labels: Review: QA +1, Review: Code +1, e2e

#2078 chore(lint): add no-redeclare rule
  eslint.config.mjs
  src/auth/Auth.ts
  src/auth/LocalAuth.ts
  src/components/AutocompleteInput/AutocompleteInput.tsx
  src/components/ConnectionError/ConnectionError.tsx
  src/components/DivButton/DivButton.tsx
  src/components/ErrorBoundary/ErrorBoundary.tsx
  src/components/Panel/Panel.test.tsx
  src/components/Panel/Panel.tsx
  src/components/Routes/Routes.tsx
  src/components/WebCLI/WebCLI.tsx
  src/index.tsx
  src/juju/api.ts
  src/pages/AdvancedSearch/CodeSnippetBlock/CodeSnippetBlock.tsx
  src/pages/ControllersIndex/ControllersIndex.tsx
  src/pages/EntityDetails/App/App.tsx
  src/pages/EntityDetails/EntityDetails.tsx
  src/pages/EntityDetails/Model/ApplicationsTab/LocalAppsTable/LocalAppsTable.tsx
  src/pages/EntityDetails/Model/ModelTabs/ModelTabs.tsx
  src/pages/EntityDetails/Model/Secrets/SecretContent/SecretContent.tsx
  src/pages/EntityDetails/Model/Secrets/Secrets.tsx
  src/pages/ModelsIndex/ModelsIndex.tsx
  src/pages/Permissions/Permissions.test.tsx
  src/pages/Permissions/Permissions.tsx
  src/panels/ConfigPanel/BooleanConfig/BooleanConfig.tsx
  src/panels/ConfigPanel/ConfigPanel.tsx
  src/panels/PanelInlineErrors/PanelInlineErrors.tsx
  src/store/app/actions.ts
  src/store/general/types.ts
  src/store/juju/utils/models.ts
  src/testing/factories/general.ts
  src/testing/factories/juju/ModelManagerV9.ts
Labels: Review: Code +1 (with changes)

#2085 fix(ci): correctly filter workflow run
  .github/workflows/release.yml
Labels: Review: Code needed

#2096 chore(CI): allow manually running TICS
  .github/workflows/tics-coverage.yml
Labels: Review: Code +1

#2093 fix: Deleted models are not updated
  src/store/juju/reducers.test.ts
  src/store/juju/slice.ts
Labels: Review: QA +1, Review: Code +1, e2e

#2092 feat(deps): upgrade dependencies to fix vulnerabilities
  charms/k8s-charm/requirements.txt
  charms/machine-charm/requirements.txt
  package.json
  yarn.lock
Labels: Review: Code +1 (with changes), e2e

#2109 chore(lint): add require-await rule
  eslint.config.mjs
  src/auth/Auth.ts
  src/store/app/thunks.ts
  src/store/juju/thunks.ts
  src/testing/setup.ts
Labels: Review: Code +1 (with changes)

#2106 chore(lint): add no-unsafe-argument rule
  eslint.config.mjs
  src/components/DonutChart/DonutChart.tsx
  src/components/WebCLI/connection.ts
  src/hooks/useQueryParams.ts
  src/juju/api.test.ts
  src/juju/api.ts
  src/store/juju/selectors.ts
  src/store/middleware/check-auth.test.ts
  src/store/middleware/model-poller.test.ts
Labels: Review: Code +1

#2105 chore(lint): add curly rule
  eslint.config.mjs
  src/components/ChipGroup/ChipGroup.tsx
  src/components/ModelTableList/ModelTable/ModelTable.tsx
  src/components/RadioInputBox/RadioInputBox.tsx
  src/hooks/useModelAttributes.ts
  src/juju/api.ts
  src/pages/EntityDetails/App/App.tsx
  src/pages/EntityDetails/Model/ApplicationsTab/SearchResults/SearchResults.tsx
  src/pages/EntityDetails/Model/Logs/ActionLogs/ActionLogs.tsx
  src/pages/EntityDetails/counts.ts
  src/pages/ModelsIndex/ModelsIndex.tsx
  src/panels/CharmsAndActionsPanel/CharmActionsPanelTitle/CharmActionsPanelTitle.tsx
  src/panels/ConfigPanel/SecretsPicker/SecretsPicker.tsx
  src/store/juju/selectors.ts
  src/store/juju/utils/models.ts
  src/tables/tableRows.tsx
Labels: Review: Code +1

#2115 chore(ci): retry postgres-openfga relation
  .github/actions/setup-jimm/action.yml
Labels: Review: Code +1, e2e

#2114 chore(lint): disable booleans for prefer-nullish-coalescing
  eslint.config.mjs
Labels: Review: Code +1

#2121 Upgrade to edge postgres charm
  .github/actions/setup-jimm/action.yml
Labels: Review: Code +1, e2e

#2119 fix lint rules for e2e files
  e2e/base/auth-validation.spec.ts
  e2e/fixtures/setup.ts
  e2e/helpers/action.ts
  e2e/helpers/actions/addModel.ts
  e2e/helpers/actions/deployApplication.ts
  e2e/helpers/actions/utils/give-access.ts
  e2e/helpers/auth/AuthImplementation.ts
  e2e/helpers/auth/Users.ts
  e2e/helpers/auth/backends/Candid.ts
  e2e/helpers/auth/backends/Keycloak.ts
  e2e/helpers/auth/backends/Local.ts
  e2e/helpers/auth/backends/OIDC.ts
  e2e/helpers/auth/backends/utils.ts
  e2e/helpers/juju-cli.ts
  e2e/jimm/rebac.spec.ts
  e2e/juju/web-cli.spec.ts
  e2e/utils/addFeatureFlags.ts
  e2e/utils/exec.ts
  e2e/utils/findLine.ts
  e2e/utils/generateRandomName.ts
  e2e/utils/getEnv.ts
  eslint.config.mjs
Labels: Review: Code +1 (with changes)
