Repository canonical/juju-dashboard, pull requests merged in 2025-02, with the labels that each got.

#1843 fix: Compute latest revision from revisions array
  src/components/secrets/RevisionField/RevisionField.test.tsx
  src/components/secrets/RevisionField/RevisionField.tsx
  src/components/secrets/SecretForm/SecretForm.tsx
  src/pages/EntityDetails/Model/Secrets/SecretContent/SecretContent.test.tsx
  src/pages/EntityDetails/Model/Secrets/SecretContent/SecretContent.tsx
  src/pages/EntityDetails/Model/Secrets/SecretsTable/SecretsTable.tsx
  src/panels/RemoveSecretPanel/Fields/Fields.test.tsx
  src/panels/RemoveSecretPanel/Fields/Fields.tsx
  src/panels/RemoveSecretPanel/RemoveSecretPanel.tsx
  src/panels/SecretFormPanel/SecretFormPanel.tsx
  src/store/juju/selectors.test.ts
  src/store/juju/selectors.ts
  src/utils/getLatestRevision.test.ts
  src/utils/getLatestRevision.ts
  src/utils/index.ts
Labels: Review: QA +1, Review: Code +1

#1849 WD-19117 - refactor: create hook for handling fetching permission
  src/components/PrimaryNav/PrimaryNav.test.tsx
  src/components/PrimaryNav/PrimaryNav.tsx
  src/juju/api-hooks/index.ts
  src/juju/api-hooks/permissions.test.tsx
  src/juju/api-hooks/permissions.ts
  src/store/juju/selectors.test.ts
  src/store/juju/selectors.ts
Labels: Review: QA +1, Review: Code +1

#1845 feat(logging): Use loglevel library for error handling
  package.json
  src/components/App/App.test.tsx
  src/components/LogIn/LogIn.test.tsx
  src/components/LogIn/UserPassForm/UserPassForm.test.tsx
  src/components/LogIn/UserPassForm/UserPassForm.tsx
  src/components/ShareCard/ShareCard.test.tsx
  src/components/ShareCard/ShareCard.tsx
  src/components/UserMenu/UserMenu.test.tsx
  src/hooks/useLocalStorage.test.ts
  src/hooks/useLocalStorage.ts
  src/hooks/useLogout.test.tsx
  src/hooks/useLogout.tsx
  src/hooks/useQueryParams.ts
  src/index.test.tsx
  src/index.tsx
  src/juju/api.test.ts
  src/juju/api.ts
  src/pages/EntityDetails/Model/Logs/ActionLogs/ActionLogs.test.tsx
  src/pages/EntityDetails/Model/Logs/ActionLogs/ActionLogs.tsx
  src/pages/ModelDetails/ModelDetails.test.tsx
  src/pages/ModelDetails/ModelDetails.tsx
  src/pages/Permissions/Permissions.test.tsx
  src/panels/ActionsPanel/ActionsPanel.test.tsx
  src/panels/ActionsPanel/ActionsPanel.tsx
  src/panels/ActionsPanel/ConfirmationDialog/ConfirmationDialog.test.tsx
  src/panels/ActionsPanel/ConfirmationDialog/ConfirmationDialog.tsx
  src/panels/CharmsAndActionsPanel/CharmsAndActionsPanel.test.tsx
  src/panels/CharmsAndActionsPanel/CharmsAndActionsPanel.tsx
  src/panels/ConfigPanel/ConfigPanel.test.tsx
  src/panels/ConfigPanel/ConfigPanel.tsx
  src/panels/ConfigPanel/ConfirmationDialog/ConfirmationDialog.test.tsx
  src/panels/ConfigPanel/ConfirmationDialog/ConfirmationDialog.tsx
  src/store/app/thunks.test.ts
  src/store/app/thunks.ts
  src/store/juju/thunks.ts
  src/store/middleware/check-auth.test.ts
  src/store/middleware/check-auth.ts
  src/store/middleware/model-poller.test.ts
  src/store/middleware/model-poller.ts
  src/store/store.ts
  src/testing/setup.ts
  src/utils/logger.ts
  yarn.lock
Labels: Review: Code needed

#1859 chore(deps): fix deprecated deps and peer requirements
  package.json
  src/pages/AdvancedSearch/ErrorsBlock/ErrorsBlock.tsx
  src/store/juju/selectors.ts
  src/store/juju/slice.ts
  yarn.lock
Labels: Review: Code +1

#1860 chore(deps): update to eslint v9
  .eslintrc
  .github/workflows/actions.yml
  .github/workflows/test.yml
  .github/workflows/tics-coverage.yml
  eslint.config.mjs
  package.json
  src/components/ErrorBoundary/ErrorBoundary.test.tsx
  src/components/WebCLI/Output/Output.tsx
  src/store/app/thunks.test.ts
  src/store/middleware/check-auth.ts
  yarn.lock
Labels: Review: Code +1

#1852 feat: check audit logs access via jimm
  src/pages/EntityDetails/EntityDetails.test.tsx
  src/pages/EntityDetails/EntityDetails.tsx
  src/pages/EntityDetails/Model/Logs/Logs.test.tsx
  src/pages/EntityDetails/Model/Logs/Logs.tsx
  src/pages/EntityDetails/Model/Model.test.tsx
  src/pages/EntityDetails/Model/ModelTabs/ModelTabs.test.tsx
  src/pages/EntityDetails/Model/ModelTabs/ModelTabs.tsx
  src/pages/EntityDetails/Model/ModelTabs/index.ts
  src/pages/EntityDetails/Model/ModelTabs/types.ts
Labels: Review: QA +1, Review: Code +1

#1853 feat: access buttons link to groups when using rebac
  src/components/AccessButton/AccessButton.test.tsx
  src/components/AccessButton/AccessButton.tsx
  src/components/AccessButton/index.ts
  src/components/AccessButton/types.ts
  src/components/ModelTableList/AccessButton/AccessButton.test.tsx
  src/components/ModelTableList/AccessButton/AccessButton.tsx
  src/components/ModelTableList/CloudGroup/CloudGroup.test.tsx
  src/components/ModelTableList/CloudGroup/CloudGroup.tsx
  src/components/ModelTableList/OwnerGroup/OwnerGroup.test.tsx
  src/components/ModelTableList/OwnerGroup/OwnerGroup.tsx
  src/components/ModelTableList/StatusGroup/StatusGroup.test.tsx
  src/components/ModelTableList/StatusGroup/StatusGroup.tsx
  src/components/PrimaryNav/PrimaryNav.tsx
  src/pages/EntityDetails/Model/Model.test.tsx
  src/pages/EntityDetails/Model/Model.tsx
  src/pages/EntityDetails/Model/types.ts
  src/pages/Permissions/Permissions.tsx
  src/urls.ts
Labels: Review: QA +1, Review: Code +1
