Repository canonical/juju-dashboard, pull requests merged in 2025-04, with the labels that each got.

#1916 feat: hoist login state
  src/auth/OIDCAuth.test.ts
  src/auth/OIDCAuth.ts
  src/components/LogIn/IdentityProviderForm/IdentityProviderForm.tsx
  src/components/LogIn/LogIn.tsx
  src/components/LogIn/OIDCForm/OIDCForm.test.tsx
  src/components/LogIn/OIDCForm/OIDCForm.tsx
  src/components/LogIn/UserPassForm/UserPassForm.test.tsx
  src/components/LogIn/UserPassForm/UserPassForm.tsx
  src/index.tsx
  src/juju/bakery.ts
  src/store/middleware/model-poller.test.ts
  src/store/middleware/model-poller.ts
Labels: Review: QA +1, Review: Code +1

#1917 chore(test): Add machine charm/local auth e2e workflow
  .github/actions/run-playwright/action.yml
  .github/actions/setup-juju/action.yml
  .github/actions/setup-machine-charm/action.yml
  .github/workflows/e2e-juju-machine-charm-local-auth.yml
  .github/workflows/end-to-end.yml
  .gitignore
  e2e/base/init.spec.ts
  package.json
  playwright.config.ts
  yarn.lock
Labels: Review: QA +1, Review: Code +1

#1926 feat(e2e): add basic auth tests for juju workflows
  e2e/base/init.spec.ts
  e2e/fixtures/setup.ts
  e2e/helpers/auth-helpers.ts
  tsconfig.json
Labels: Review: QA +1, Review: Code +1

#1927 feat(e2e): implement 'List controllers' test suite
  .github/workflows/e2e-juju-k8s-charm-local-auth.yml
  .github/workflows/e2e-juju-machine-charm-candid-auth.yml
  .github/workflows/e2e-juju-machine-charm-local-auth.yml
  e2e/base/controllers.spec.ts
  e2e/base/init.spec.ts
Labels: Review: QA +1, Review: Code +1

#1932 feat: create webhook notification action
  .github/actions/send-notification/action.yml
  .github/workflows/e2e-juju-k8s-charm-local-auth.yml
  .github/workflows/e2e-juju-machine-charm-candid-auth.yml
  .github/workflows/e2e-juju-machine-charm-local-auth.yml
  .github/workflows/end-to-end.yml
Labels: Review: QA +1, Review: Code +1

#1934 feat(e2e): implement 'auth validation' test suite
  .github/actions/setup-k8s-charm/action.yml
  .github/actions/setup-machine-charm/action.yml
  .github/workflows/e2e-juju-k8s-charm-local-auth.yml
  .github/workflows/e2e-juju-machine-charm-candid-auth.yml
  .github/workflows/e2e-juju-machine-charm-local-auth.yml
  e2e/base/auth-validation.spec.ts
  e2e/helpers/auth-helpers.ts
Labels: Review: Code +1 (with changes)

#1938 feat(e2e): Add test suite for Juju Web CLI
  e2e/base/models.spec.ts
  e2e/juju/web-cli.spec.ts
Labels: Review: QA +1, Review: Code +1 (with changes)

#1939 feat(e2e): Add test case for model access
  e2e/base/auth-validation.spec.ts
  e2e/base/controllers.spec.ts
  e2e/base/models.spec.ts
  e2e/helpers/auth-helpers.ts
  e2e/juju/web-cli.spec.ts
  package.json
  yarn.lock
Labels: Review: Code +1

#1941 feat(e2e): Add test suite for model access control
  e2e/base/models.spec.ts
  e2e/juju/model-access-control.spec.ts
Labels: Review: Code +1

#1945 fix(ci): use commit sha for pull request workflow
  .github/actions/prepare-action/action.yml
  .github/workflows/e2e-juju-k8s-charm-local-auth.yml
  .github/workflows/e2e-juju-machine-charm-candid-auth.yml
  .github/workflows/e2e-juju-machine-charm-local-auth.yml
Labels: Review: Code +1, e2e

#1942 chore(ci): add JIMM workflow
  .github/actions/run-playwright/action.yml
  .github/actions/setup-jimm/action.yml
  .github/actions/setup-jimm/cli-login.ts
  .github/actions/setup-k8s-charm/action.yml
  .github/actions/setup-machine-charm/action.yml
  .github/workflows/e2e-jimm-k8s-charm-oidc-auth.yml
  .github/workflows/end-to-end.yml
  e2e/base/auth-validation.spec.ts
  e2e/base/models.spec.ts
  e2e/helpers/auth-helpers.ts
  e2e/helpers/juju-helpers.ts
  e2e/helpers/user/oidc.ts
  e2e/utils/exec.ts
  e2e/utils/findLine.ts
Labels: Review: Code +1 (with changes), e2e
