Repository canonical/juju-dashboard, pull requests merged in 2025-01, with the labels that each got.

#1830 Merge ReBAC Admin feature branch
  HACKING.md
  package.json
  src/components/App/App.test.tsx
  src/components/App/App.tsx
  src/components/CaptureRoutes/CaptureRoutes.test.tsx
  src/components/CaptureRoutes/CaptureRoutes.tsx
  src/components/CaptureRoutes/index.ts
  src/components/LogIn/LogIn.test.tsx
  src/components/LogIn/LogIn.tsx
  src/components/PrimaryNav/PrimaryNav.test.tsx
  src/components/PrimaryNav/PrimaryNav.tsx
  src/components/PrimaryNav/types.ts
  src/components/Routes/Routes.test.tsx
  src/components/Routes/Routes.tsx
  src/components/SecondaryNavigation/SecondaryNavigation.test.tsx
  src/components/SecondaryNavigation/SecondaryNavigation.tsx
  src/components/SecondaryNavigation/_secondary-navigation.scss
  src/components/SecondaryNavigation/index.ts
  src/components/SecondaryNavigation/types.ts
  src/layout/BaseLayout/BaseLayout.test.tsx
  src/layout/BaseLayout/BaseLayout.tsx
  src/layout/BaseLayout/_base-layout.scss
  src/pages/AdvancedSearch/AdvancedSearch.tsx
  src/pages/AdvancedSearch/index.ts
  src/pages/AdvancedSearch/types.ts
  src/pages/ControllersIndex/ControllersIndex.tsx
  src/pages/ControllersIndex/index.ts
  src/pages/ControllersIndex/types.ts
  src/pages/EntityDetails/EntityDetails.tsx
  src/pages/EntityDetails/index.ts
  src/pages/EntityDetails/types.ts
  src/pages/Logs/Logs.tsx
  src/pages/Logs/index.ts
  src/pages/Logs/types.ts
  src/pages/ModelsIndex/ModelsIndex.tsx
  src/pages/ModelsIndex/index.ts
  src/pages/ModelsIndex/types.ts
  src/pages/PageNotFound/PageNotFound.test.tsx
  src/pages/Permissions/Permissions.test.tsx
  src/pages/Permissions/Permissions.tsx
  src/pages/Permissions/index.ts
  src/pages/Permissions/types.ts
  src/scss/index.scss
  src/store/general/selectors.test.ts
  src/store/general/selectors.ts
  src/store/general/types.ts
  src/store/middleware/model-poller.test.ts
  src/store/middleware/model-poller.ts
  src/urls.ts
  vite.config.ts
  yarn.lock
Labels: Review: Code +1

#1831 chore: set up local access to JIMM
  .env.development
  HACKING.md
  package.json
  public/config.jaas.js
  src/axios-instance.ts
  src/juju/jimm/api.ts
  src/pages/Permissions/Permissions.tsx
  vite.config.ts
  vite.dev.config.ts
  vite.jaas.config.ts
  yarn.lock
Labels: Review: QA +1, Review: Code +1

#1834 fix: log in before displaying 404 for some routes
  src/components/LogIn/LogIn.tsx
  src/components/LogIn/index.ts
  src/components/LogIn/types.ts
  src/components/Routes/Routes.test.tsx
  src/components/Routes/Routes.tsx
Labels: Review: QA +1, Review: Code +1

#1837 test(jimmEndpoint): Add unit tests
  src/juju/jimm/api.test.ts
Labels: Review: QA +1, Review: Code +1

#1839 chore(testing): Migrate code coverage to vitest-coverage-report-action
  .github/workflows/actions.yml
  .github/workflows/coverage.yml
  .github/workflows/test.yml
  HACKING.md
  README.md
  codecov.yml
  vite.config.ts
Labels: Review: QA +1, Review: Code +1 (with changes)

#1841 feat: add check relation middleware
  src/components/PrimaryNav/PrimaryNav.test.tsx
  src/components/PrimaryNav/PrimaryNav.tsx
  src/juju/api.test.ts
  src/juju/api.ts
  src/juju/jimm/JIMMV4.test.ts
  src/juju/jimm/JIMMV4.ts
  src/juju/jimm/api.test.ts
  src/juju/jimm/api.ts
  src/store/general/selectors.test.ts
  src/store/general/selectors.ts
  src/store/juju/actions.test.ts
  src/store/juju/reducers.test.ts
  src/store/juju/selectors.test.ts
  src/store/juju/selectors.ts
  src/store/juju/slice.ts
  src/store/juju/types.ts
  src/store/middleware/check-auth.ts
  src/store/middleware/model-poller.test.ts
  src/store/middleware/model-poller.ts
  src/testing/factories/general.ts
  src/testing/factories/juju/juju.ts
Labels: Review: QA +1, Review: Code +1

#1842 fix: don't refetch nav permissions
  src/components/PrimaryNav/PrimaryNav.test.tsx
  src/components/PrimaryNav/PrimaryNav.tsx
  src/store/juju/selectors.ts
Labels: Review: QA +1, Review: Code +1

#1840 fix(oidc): Display spinner in OIDC login button during loading
  src/components/LogIn/LogIn.test.tsx
  src/components/LogIn/OIDCForm/OIDCForm.test.tsx
  src/components/LogIn/OIDCForm/OIDCForm.tsx
  src/components/LogIn/types.ts
  src/pages/ControllersIndex/ControllersIndex.test.tsx
  src/store/general/reducers.test.ts
  src/store/general/selectors.test.ts
  src/store/general/selectors.ts
  src/store/general/slice.ts
  src/store/general/types.ts
  src/store/middleware/check-auth.ts
  src/store/middleware/model-poller.ts
  src/testing/factories/general.ts
Labels: Review: QA +1, Review: Code +1 (with changes)
