Repository canonical/juju-dashboard, pull requests merged in 2025-06, with the labels that each got.

#1979 fix: correct controller overview chart percentages
  src/pages/ControllersIndex/ControllerChart/ControllerChart.test.tsx
  src/pages/ControllersIndex/ControllerChart/ControllerChart.tsx
Labels: Review: Code +1

#1981 feat: add links to help commands in the CLI
  package.json
  src/components/JujuCLI/JujuCLI.test.tsx
  src/components/JujuCLI/JujuCLI.tsx
  src/components/WebCLI/Output/Output.test.tsx
  src/components/WebCLI/Output/Output.tsx
  src/components/WebCLI/Output/index.ts
  src/components/WebCLI/Output/types.ts
  src/components/WebCLI/WebCLI.test.tsx
  src/components/WebCLI/WebCLI.tsx
  src/components/WebCLI/__snapshots__/WebCLI.test.tsx.snap
  src/components/WebCLI/_webcli.scss
  src/components/WebCLI/connection.ts
  src/components/WebCLI/index.ts
  src/components/WebCLI/types.ts
  src/components/WebCLI/utils.tsx
  src/urls.ts
  yarn.lock
Labels: Review: QA needed, Review: Code +1

#1982 refactor: move dashboard-specific code out of WebCLI
  HACKING.md
  src/components/JujuCLI/JujuCLI.test.tsx
  src/components/JujuCLI/JujuCLI.tsx
  src/components/WebCLI/WebCLI.test.tsx
  src/components/WebCLI/WebCLI.tsx
Labels: Review: QA +1, Review: Code +1 (with changes)

#1889 feat: fetch and display the ReBAC model access
  src/components/EntityInfo/EntityInfo.tsx
  src/components/TruncatedTooltip/TruncatedTooltip.tsx
  src/hooks/useModelAccess.test.tsx
  src/hooks/useModelAccess.ts
  src/pages/EntityDetails/Model/Model.test.tsx
  src/pages/EntityDetails/Model/Model.tsx
  src/store/general/selectors.test.ts
  src/store/general/selectors.ts
Labels: Review: QA +1, Review: Code +1

#1989 chore(eslint): improve rules
  eslint.config.mjs
  package.json
  src/auth/CandidAuth.ts
  src/components/AuditLogsTable/AuditLogsTablePagination/AuditLogsTablePagination.tsx
  src/components/ConnectionError/ConnectionError.tsx
  src/components/DonutChart/DonutChart.tsx
  src/components/InfoPanel/InfoPanel.tsx
  src/components/LogIn/LogIn.tsx
  src/components/LogIn/UserPassForm/UserPassForm.tsx
  src/components/Panel/Panel.tsx
  src/components/ShareCard/ShareCard.tsx
  src/components/ToastCard/ToastCard.test.tsx
  src/components/Topology/Topology.tsx
  src/components/WebCLI/Output/Output.tsx
  src/components/WebCLI/WebCLI.tsx
  src/hooks/useLogout.tsx
  src/juju/api.ts
  src/pages/ControllersIndex/ControllersIndex.tsx
  src/pages/EntityDetails/Model/ApplicationsTab/LocalAppsTable/useTableSelect.tsx
  src/pages/EntityDetails/Model/ApplicationsTab/SearchResults/SearchResults.tsx
  src/pages/EntityDetails/Model/Logs/ActionLogs/ActionLogs.tsx
  src/pages/EntityDetails/Model/ModelTabs/ModelTabs.tsx
  src/panels/ActionsPanel/CharmActionsPanel/CharmActionsPanel.tsx
  src/panels/ActionsPanel/CharmActionsPanel/ConfirmationDialog/ConfirmationDialog.tsx
  src/panels/CharmsPanel/CharmsPanel.tsx
  src/panels/ConfigPanel/BooleanConfig/BooleanConfig.tsx
  src/panels/ConfigPanel/NumberConfig/NumberConfig.tsx
  src/panels/ConfigPanel/TextAreaConfig/TextAreaConfig.tsx
  src/panels/ShareModelPanel/ShareModel.tsx
  src/store/juju/slice.ts
  src/store/middleware/model-poller.ts
  src/testing/factories/juju/juju.ts
  yarn.lock
Labels: Review: Code +1

#1991 feat: display full scrollback in web CLI
  src/components/WebCLI/Output/Output.test.tsx
  src/components/WebCLI/Output/Output.tsx
  src/components/WebCLI/Output/consts.ts
  src/components/WebCLI/Output/types.ts
  src/components/WebCLI/WebCLI.tsx
  src/components/WebCLI/__snapshots__/WebCLI.test.tsx.snap
  src/components/WebCLI/_webcli.scss
Labels: Review: QA +1, Review: Code +1

#1993 feat(actions): common utilities
  .github/workflows/actions.yml
  actions/package.json
  actions/src/lib/changelog.test.ts
  actions/src/lib/changelog.ts
  actions/src/lib/git.ts
  actions/src/lib/github/index.ts
  actions/src/lib/github/pull-request.ts
  actions/src/lib/github/repository.ts
  actions/src/lib/github/types.ts
  actions/src/lib/index.ts
  actions/src/lib/util.ts
  actions/src/lib/versioning/branch.test.ts
  actions/src/lib/versioning/branch.ts
  actions/src/lib/versioning/index.ts
  actions/src/lib/versioning/labels.test.ts
  actions/src/lib/versioning/labels.ts
  actions/src/lib/versioning/severity.test.ts
  actions/src/lib/versioning/severity.ts
  actions/src/lib/versioning/types.ts
  actions/tsconfig.json
  actions/vite.config.ts
  eslint.config.mjs
  yarn.lock
Labels: Review: Code +1

#1996 feat: persist CLI history
  src/components/JujuCLI/JujuCLI.test.tsx
  src/components/JujuCLI/JujuCLI.tsx
  src/components/WebCLI/Output/types.ts
  src/components/WebCLI/WebCLI.test.tsx
  src/components/WebCLI/WebCLI.tsx
  src/store/juju/actions.test.ts
  src/store/juju/reducers.test.ts
  src/store/juju/selectors.test.ts
  src/store/juju/selectors.ts
  src/store/juju/slice.ts
  src/store/juju/types.ts
  src/store/middleware/check-auth.ts
  src/testing/factories/juju/juju.ts
Labels: Review: QA +1, Review: Code +1
