Repository canonical/juju-dashboard, pull requests merged in 2025-03, with the labels that each got.

#1847 feat(analytics): Implement usage analytics with react-ga4
  package.json
  src/components/App/App.test.tsx
  src/components/App/App.tsx
  src/components/CaptureRoutes/CaptureRoutes.test.tsx
  src/hooks/useAnalytics.test.ts
  src/hooks/useAnalytics.tsx
  src/store/middleware/model-poller.ts
  src/testing/setup.ts
  src/utils/analytics.test.ts
  src/utils/analytics.ts
  yarn.lock
Labels: Review: QA +1, Review: Code +1

#1873 fix: apply word break in config panel
  src/panels/ConfigPanel/_config-panel.scss
Labels: Review: QA +1, Review: Code +1

#1874 fix: correctly disable routes for disabled features
  src/components/CheckPermissions/CheckPermissions.test.tsx
  src/components/CheckPermissions/CheckPermissions.tsx
  src/components/CheckPermissions/index.ts
  src/components/CheckPermissions/types.ts
  src/components/Routes/Routes.test.tsx
  src/components/Routes/Routes.tsx
  src/layout/BaseLayout/BaseLayout.test.tsx
  src/layout/BaseLayout/BaseLayout.tsx
  src/layout/BaseLayout/index.ts
  src/layout/BaseLayout/types.ts
  src/pages/AdvancedSearch/AdvancedSearch.test.tsx
  src/pages/AdvancedSearch/AdvancedSearch.tsx
  src/pages/Logs/Logs.test.tsx
  src/pages/Logs/Logs.tsx
  src/pages/PageNotFound/PageNotFound.tsx
  src/pages/Permissions/Permissions.test.tsx
  src/pages/Permissions/Permissions.tsx
Labels: Review: QA +1, Review: Code +1 (with changes)

#1876 chore(docs): updated microk8s instructions
  HACKING.md
  docs/multipass-microk8s.md
Labels: Review: Code +1

#1878 fix: show error on initial model error
  src/pages/ModelsIndex/ModelsIndex.test.tsx
  src/pages/ModelsIndex/ModelsIndex.tsx
Labels: Review: QA +1, Review: Code +1 (with changes)

#1879 refactor(tests): migrate test queries from rebac-admin
  src/components/AuditLogsTable/AuditLogsTable.test.tsx
  src/pages/ModelsIndex/ModelsIndex.test.tsx
  src/pages/ModelsIndex/ModelsIndex.tsx
  src/panels/CharmsAndActionsPanel/CharmsAndActionsPanel.test.tsx
  src/panels/ConfigPanel/ConfigPanel.test.tsx
  src/testing/queries/index.ts
  src/testing/queries/notifications.ts
  src/testing/queries/queries.ts
  src/testing/queries/spinners.ts
  src/testing/queries/tables.ts
  src/testing/queries/within.ts
  src/testing/utils.tsx
Labels: Review: Code +1

#1882 refactor: rename rebac relation state
  src/components/PrimaryNav/PrimaryNav.test.tsx
  src/hooks/useCanConfigureModel.test.tsx
  src/juju/api-hooks/permissions.test.tsx
  src/pages/EntityDetails/Model/Logs/Logs.test.tsx
  src/pages/EntityDetails/Model/Model.test.tsx
  src/pages/EntityDetails/Model/ModelTabs/ModelTabs.test.tsx
  src/pages/Logs/Logs.test.tsx
  src/pages/Permissions/Permissions.test.tsx
  src/store/juju/reducers.test.ts
  src/store/juju/selectors.test.ts
  src/store/juju/selectors.ts
  src/store/juju/slice.ts
  src/store/juju/types.ts
  src/testing/factories/juju/juju.ts
Labels: Review: Code +1

#1883 fix: prevent action log modal from breaking out of stacking context
  src/pages/EntityDetails/Model/Logs/ActionLogs/ActionLogs.tsx
  src/pages/EntityDetails/Model/Logs/ActionLogs/_action-logs.scss
Labels: Review: QA +1, Review: Code +1 (with changes)

#1891 fix: actions panel reopen
  package.json
  yarn.lock
Labels: Review: QA +1, Review: Code +1

#1890 fix: flash of charm actions on load
  src/components/RadioInputBox/RadioInputBox.tsx
  src/components/RadioInputBox/_radio-input-box.scss
Labels: Review: QA +1, Review: Code +1

#1903 build: update dashboard version to 0.14.1
  package.json
  yarn.lock
Labels: Review: Code +1

#1905 feat: implement base `Auth` class
  src/auth/Auth.test.ts
  src/auth/Auth.ts
  src/auth/index.ts
Labels: Review: Code +1

#1902 refactor: replace async-limiter with a blocking loop
  package.json
  src/async-limiter.d.ts
  src/juju/api.ts
  vite.config.ts
  yarn.lock
Labels: Review: QA +1, Review: Code +1

#1892 refactor: remove memoised Redux selectors
  src/components/AuditLogsTable/hooks.ts
  src/components/InfoPanel/InfoPanel.tsx
  src/components/LogIn/IdentityProviderForm/IdentityProviderForm.tsx
  src/components/LogIn/LogIn.tsx
  src/components/ModelTableList/CloudGroup/CloudGroup.tsx
  src/components/ModelTableList/ModelTableList.test.tsx
  src/components/ModelTableList/OwnerGroup/OwnerGroup.tsx
  src/components/ModelTableList/StatusGroup/StatusGroup.tsx
  src/components/PrimaryNav/PrimaryNav.tsx
  src/components/secrets/SecretForm/SecretForm.tsx
  src/hooks/useAnalytics.tsx
  src/hooks/useCanConfigureModel.ts
  src/hooks/useCanManageSecrets.ts
  src/hooks/useModelStatus.ts
  src/juju/api-hooks/common.ts
  src/juju/api-hooks/permissions.ts
  src/juju/api-hooks/secrets.ts
  src/layout/BaseLayout/BaseLayout.tsx
  src/pages/ControllersIndex/ControllerOverview/ControllerOverview.tsx
  src/pages/ControllersIndex/ControllersIndex.tsx
  src/pages/EntityDetails/App/App.tsx
  src/pages/EntityDetails/EntityDetails.tsx
  src/pages/EntityDetails/Machine/Machine.tsx
  src/pages/EntityDetails/Model/ApplicationsTab/ApplicationsTab.tsx
  src/pages/EntityDetails/Model/ApplicationsTab/LocalAppsTable/LocalAppsTable.tsx
  src/pages/EntityDetails/Model/ApplicationsTab/LocalAppsTable/useTableSelect.tsx
  src/pages/EntityDetails/Model/ApplicationsTab/SearchResults/SearchResults.tsx
  src/pages/EntityDetails/Model/Logs/ActionLogs/ActionLogs.tsx
  src/pages/EntityDetails/Model/Logs/Logs.tsx
  src/pages/EntityDetails/Model/Model.tsx
  src/pages/EntityDetails/Model/ModelTabs/ModelTabs.tsx
  src/pages/EntityDetails/Model/Secrets/SecretContent/SecretContent.tsx
  src/pages/EntityDetails/Model/Secrets/Secrets.tsx
  src/pages/EntityDetails/Model/Secrets/SecretsTable/SecretsTable.tsx
  src/pages/EntityDetails/Unit/Unit.tsx
  src/pages/ModelDetails/ModelDetails.tsx
  src/pages/ModelsIndex/ModelsIndex.tsx
  src/panels/ActionsPanel/ActionsPanel.tsx
  src/panels/ActionsPanel/CharmActionsPanel/CharmActionsPanel.tsx
  src/panels/AuditLogsFilterPanel/Fields/Fields.tsx
  src/panels/CharmsAndActionsPanel/CharmActionsPanelTitle/CharmActionsPanelTitle.tsx
  src/panels/CharmsAndActionsPanel/CharmsAndActionsPanel.tsx
  src/panels/CharmsPanel/CharmApplicationsDetails/CharmApplicationsDetails.tsx
  src/panels/CharmsPanel/CharmsPanel.tsx
  src/panels/ConfigPanel/SecretsPicker/SecretsPicker.tsx
  src/panels/GrantSecretPanel/GrantSecretPanel.tsx
  src/panels/RemoveSecretPanel/Fields/Fields.tsx
  src/panels/RemoveSecretPanel/RemoveSecretPanel.tsx
  src/panels/ShareModelPanel/ShareModel.tsx
  src/store/juju/selectors.test.ts
  src/store/juju/selectors.ts
Labels: Review: QA +1, Review: Code +1 (with changes)

#1894 refactor: use native Redux store in tests
  package.json
  src/components/App/App.test.tsx
  src/components/AuditLogsTable/AuditLogsTable.test.tsx
  src/components/AuditLogsTable/AuditLogsTablePagination/AuditLogsTablePagination.test.tsx
  src/components/AuditLogsTable/hooks.test.tsx
  src/components/AuthenticationButton/AuthenticationButton.test.tsx
  src/components/PrimaryNav/PrimaryNav.test.tsx
  src/components/Routes/Routes.test.tsx
  src/components/hooks.test.tsx
  src/hooks/useCanConfigureModel.test.tsx
  src/hooks/useCanManageSecrets.test.tsx
  src/hooks/useModelStatus.test.tsx
  src/juju/api-hooks/actions.test.tsx
  src/juju/api-hooks/application.test.tsx
  src/juju/api-hooks/common.test.tsx
  src/juju/api-hooks/permissions.test.tsx
  src/juju/api-hooks/secrets.test.tsx
  src/juju/api.test.ts
  src/pages/AdvancedSearch/SearchForm/SearchForm.test.tsx
  src/pages/EntityDetails/Model/ApplicationsTab/LocalAppsTable/AppSearchBox/AppSearchBox.test.tsx
  src/pages/EntityDetails/Model/ApplicationsTab/LocalAppsTable/LocalAppsTable.test.tsx
  src/pages/EntityDetails/Model/ApplicationsTab/SearchResults/SearchResults.test.tsx
  src/pages/EntityDetails/Model/Secrets/SecretContent/SecretContent.test.tsx
  src/pages/EntityDetails/Model/Secrets/Secrets.test.tsx
  src/pages/Logs/Logs.test.tsx
  src/pages/ModelDetails/ModelDetails.test.tsx
  src/pages/PageNotFound/PageNotFound.test.tsx
  src/pages/Permissions/Permissions.test.tsx
  src/panels/ConfigPanel/ConfigPanel.test.tsx
  src/panels/ConfigPanel/SecretsPicker/SecretsPicker.test.tsx
  src/panels/ConfigPanel/TextAreaConfig/TextAreaConfig.test.tsx
  src/testing/setup.ts
  src/testing/utils.tsx
  yarn.lock
Labels: Review: Code +1 (with changes)

#1908 feat: implement `OIDCAuth` subclass
  src/auth/OIDCAuth.test.ts
  src/auth/OIDCAuth.ts
  src/auth/index.ts
  src/auth/mixins/index.ts
  src/auth/mixins/polling.test.ts
  src/auth/mixins/polling.ts
Labels: Review: Code +1

#1912 feat: implement `LocalAuth` subclass
  src/auth/LocalAuth.test.ts
  src/auth/LocalAuth.ts
  src/auth/index.ts
Labels: Review: Code +1
