Repository canonical/juju-dashboard, pull requests merged in 2025-08, with the labels that each got.

#2025 fix: machine charm instructions
  .gitignore
  RELEASING.md
  charms/k8s-charm/build.sh
  charms/machine-charm/build.sh
  charms/machine-charm/src/dist/app-icon.png
  charms/machine-charm/src/dist/assets/aws-DgUtC-sp.svg
  charms/machine-charm/src/dist/assets/index-DE1Q6qwC.css
  charms/machine-charm/src/dist/assets/index-DMn3FCgA.js
  charms/machine-charm/src/dist/assets/kubernetes-Bjcub02c.svg
  charms/machine-charm/src/dist/config.js
  charms/machine-charm/src/dist/favicon.ico
  charms/machine-charm/src/dist/ghost-bundle.svg
  charms/machine-charm/src/dist/index.html
  charms/machine-charm/src/dist/manifest.json
  charms/machine-charm/src/dist/version.json
  docs/building-charms.md
Labels: Review: Code +1

#2016 feat: script to generate charmhub token for CI
  .gitignore
  charms/generate-charmhub-token.sh
Labels: Review: Code +1

#2026 fix(k8s-charm): `upstream-source` for docker image
  charms/k8s-charm/build.sh
  charms/k8s-charm/metadata.yaml
Labels: Review: Code +1

#2031 fix: make `Git.exec` private to prevent second-order code execution
  actions/src/lib/git.ts
Labels: Review: Code +1

#2030 use `replaceAll` instead of `replace` to catch every instance of replaced values
  src/components/JujuCLI/JujuCLI.tsx
Labels: Review: Code +1

#2032 fix: add workflow permissions to actions
  .github/workflows/test-charms.yml
  .github/workflows/test-custom-actions.yml
Labels: Review: Code +1

#2033 fix: remove `redirect-to` support in WebCLI connection handling
  .github/actions/setup-k8s-charm/action.yml
  charms/k8s-charm/build.sh
  src/components/WebCLI/WebCLI.test.tsx
  src/components/WebCLI/connection.ts
Labels: Review: Code needed, e2e

#2017 chore(CI): Docker JIMM workflow
  .github/actions/run-playwright/action.yml
  .github/actions/setup-docker-dashboard/action.yml
  .github/workflows/e2e-jimm-docker-keycloak.yml
  .github/workflows/end-to-end.yml
  Dockerfile
  e2e/base/auth-validation.spec.ts
  e2e/base/models.spec.ts
  e2e/jimm/cross-model-queries.spec.ts
  nginx.conf
Labels: Review: Code +1, e2e

#2034 chore: Update docs with latest setup, build and QA information
  CONTRIBUTING.md
  HACKING.md
  RELEASING.md
Labels: Review: Code +1

#2048 chore: move disableControllerUUIDMasking into model-poller
  src/auth/Auth.ts
  src/auth/CandidAuth.test.ts
  src/auth/CandidAuth.ts
  src/pages/ModelsIndex/ModelsIndex.tsx
  src/store/middleware/model-poller.test.ts
  src/store/middleware/model-poller.ts
Labels: Review: QA +1, Review: Code +1, e2e

#2049 chore: Update docs for restarting local JIMM setup
  HACKING.md
Labels: Review: Code +1

#2056 feat: publish docker image to ghcr
  .github/workflows/release.yml
Labels: Review: Code +1

#2057 refactor: Consolidate redundant code on models list page
  .github/actions/setup-docker-dashboard/action.yml
  e2e/base/models.spec.ts
  e2e/juju/model-access-control.spec.ts
  src/components/ModelActions/ModelActions.test.tsx
  src/components/ModelActions/ModelActions.tsx
  src/components/ModelActions/index.ts
  src/components/ModelActions/types.ts
  src/components/ModelTableList/AccessColumn/AccessColumn.tsx
  src/components/ModelTableList/AccessColumn/index.ts
  src/components/ModelTableList/AccessColumn/types.ts
  src/components/ModelTableList/CloudGroup/CloudGroup.test.tsx
  src/components/ModelTableList/CloudGroup/CloudGroup.tsx
  src/components/ModelTableList/CloudGroup/index.ts
  src/components/ModelTableList/CloudGroup/types.ts
  src/components/ModelTableList/ModelTable/ModelTable.tsx
  src/components/ModelTableList/ModelTable/index.ts
  src/components/ModelTableList/ModelTableList.tsx
  src/components/ModelTableList/OwnerGroup/OwnerGroup.test.tsx
  src/components/ModelTableList/OwnerGroup/OwnerGroup.tsx
  src/components/ModelTableList/OwnerGroup/index.ts
  src/components/ModelTableList/OwnerGroup/types.ts
  src/components/ModelTableList/StatusGroup/StatusGroup.test.tsx
  src/components/ModelTableList/StatusGroup/StatusGroup.tsx
  src/components/ModelTableList/StatusGroup/index.ts
  src/components/ModelTableList/_model-table-list.scss
  src/components/ModelTableList/shared.test.tsx
  src/components/ModelTableList/shared.tsx
  src/components/ModelTableList/types.ts
Labels: Review: QA +1, Review: Code +1 (with changes)

#2059 test: update run playwright action and keycloak backend e2e test fix
  .github/actions/run-playwright/action.yml
  .github/workflows/e2e-jimm-docker-keycloak.yml
  e2e/helpers/auth/backends/Keycloak.ts
Labels: e2e

#2058 feat: env var configuration of dashboard image
  .github/actions/setup-docker-dashboard/action.yml
  .github/workflows/e2e-jimm-docker-keycloak.yml
  Dockerfile
  charms/k8s-charm/src/charm.py
  charms/k8s-charm/src/config.py
  charms/machine-charm/build.sh
  charms/machine-charm/src/charm.py
  charms/machine-charm/src/config.js.j2
  charms/machine-charm/src/config.py
  charms/machine-charm/src/nginx.conf.j2
  charms/machine-charm/tests/test_charm.py
  entrypoint
  public/config.js
  public/config.js.go
Labels: Review: Code needed, e2e
